### PR TITLE
Type hinting should not accept empty values

### PR DESCRIPTION
**Pull request by bazsi**
This is a more comprehensive fix to #2636

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
@bazsi oh actually it has a conflict (probably because of astyle PR merged). Could you please rebase ?

**Comment by bazsi** [comment]
I have rebased this to master, no other changes. Previous approves would be appreciated.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
