### PR TITLE
OSX warning elimination

### LINKED ISSUE #1174: logsource.c unused variable warnings with 3.8.1 on OS X (cur_ack_count/last_ack_count)
Release: 3.8.1
OS: OS X 10.11.6, Apple LLVM version 7.3.0 (clang-703.0.31)

When I built 3.8.1, I saw these unused variable warnings with logsource.c:

CC       lib/lib_libsyslog_ng_la-logsource.lo
lib/logsource.c:61:26: warning: unused variable 'last_ack_count' [-Wunused-variable]
  guint32 cur_ack_count, last_ack_count;
                         ^
lib/logsource.c:61:11: warning: unused variable 'cur_ack_count' [-Wunused-variable]
  guint32 cur_ack_count, last_ack_count;
          ^
2 warnings generated.

### LINKED ISSUE #1176: Multiple unused function warnings in modules/afsocket/transport-unix-socket.c with 3.8.1
When I compile 3.8.1 on OS X, I see multiple unused function warnings with modules/afsocket/transport-unix-socket.c:

CC       modules/afsocket/modules_afsocket_libafsocket_la-transport-unix-socket.lo
modules/afsocket/transport-unix-socket.c:38:1: warning: unused function '_add_nv_pair_int' [-Wunused-function]
_add_nv_pair_int(LogTransportAuxData *aux, const gchar *name, gint value)
^
modules/afsocket/transport-unix-socket.c:104:1: warning: unused function '_add_nv_pair_proc_read_unless_unset' [-Wunused-function]
_add_nv_pair_proc_read_unless_unset(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file, const gchar *unset_value)
^
modules/afsocket/transport-unix-socket.c:117:1: warning: unused function '_add_nv_pair_proc_read_argv' [-Wunused-function]
_add_nv_pair_proc_read_argv(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file)
^
modules/afsocket/transport-unix-socket.c:137:1: warning: unused function '_add_nv_pair_proc_readlink' [-Wunused-function]
_add_nv_pair_proc_readlink(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file)
^
4 warnings generated.

### PR DESCRIPTION
**Pull request by Kokan**
Fixes #1174

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
@furiel It just I feel uneasy when I see that macro. Just the other day I saw that surpassing one warning could mean that compiler avoid more than that actual warning.

I am going to drop that commit and avoid the issue all together, that cred pass anyway something that embedded into socket, but maybe it shouldn't be, that would solve a few problem.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
We talked about it IRL.
I'd summarize it, why I wouldn't merge this.
The _magic_ code, guarded by the macro `SYSLOG_NG_HAVE_CLOCK_GETTIME`, is heavily depend on a monotonic time(`CLOCK_MONOTONIC`) and in the compat we also define `CLOCK_MONOTONIC` when it is not available which could ends in strange behaviour.

So I wouldn't merge this as the original problem can be resolved in another way.

(and one more thing: it is good to know that syslog-ng can work even without this code part ;) )

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
