### PR TITLE
logpipe: free self->persist_name

### PR DESCRIPTION
**Pull request by ibmibmibm**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by furiel** [comment]
Thanks for the patch!

The patch adds the missing deallocation of the persist name in the free method of the logpipes. This suggests that the owner of the self->persist_name string is the logpipe. Which is great because it is true.
But this relationship is not visible in the implementation of log_pipe_set_persist_name: the grammar pre-strdups the persist_name, and the strdupped string is passed to the log_pipe_set_persist_name , then explicitely set for the logpipe. This can be a little confusing.

Can you fix this one as well? Instead of this, it should be log_pipe_set_persist_name that creates her own copy of the the persist_name parameter, and not the grammar.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
