### PR TITLE
WIP: undefined warnings fixes

### LINKED ISSUE #2677: warning elimination: undefined
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the undefined warning. I am splitting issue from the ticket #1965

     12 [-Wundef]
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #2677

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by furiel** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mehul-m-prajapati** [comment]
@furiel : I am not sure, how to fix these warnings for cmake. Can you guide me on this?

**Comment by furiel** [comment]
In general, it would be best if you could avoid any changes from explicit `#if` to `defined`. These are not equivalent: for example if I set `-DVARIABLE=0`, `defined` would be true, but `#if` would be false. Any such identifier that comes from syslog-ng would be best if handled as explicit value, and not `defined`. You can derive from it, but then please add an explanation about the reason.
An individual identifier might fail for various reasons. For example there is a trick in autotools that we typically forget:
`AX_PREFIX_CONFIG_H(syslog-ng-config.h, "SYSLOG_NG")` adds `SYSLOG_NG_` prefix to every identifiers automatically. So for example `HAVE_GETOPT_H` is mistyped, and `SYSLOG_NG_HAVE_GETOPT_H` would probably work. 
One special case: I did not find much about `SYSLOG_NG_HAVE_BROKEN_PREAD`, only in an older version of syslog-ng. This was introduced due to a compile error in HP-UX. You can define this for zero globally for now, and we add proper detection later.
If you are stuck with any specific identifiers, feel free to ask for help. There might be other nontrivial ones.

Identifiers from compiler can be changed to `defined`. Specifically, `defined (_AIX)` or `defined (__FreeBSD__)` is reasonable.

About cmake: these are the methods that we use to add identifiers to code (that I know of): [configure_file](https://cmake.org/cmake/help/v3.2/command/configure_file.html?highlight=cmakedefine), the other one is [target_compile_definitions](https://cmake.org/cmake/help/latest/command/target_compile_definitions.html). Please check these documentations, if they help you.
In case of cmake: it is possible that an identifier is missing because the a detection itself missing for it. In that case it would be best if you could write the detections too, or at least collect those in a separate issue, to avoid missing them later. In such cases, you can define those identifiers as zeroes.

**Comment by mehul-m-prajapati** [comment]
@furiel : Thanks for the detailed explanation. I will look into it and make the changes accrodingly.

**Comment by pzoleex** [comment]
@kira-syslogng add to whitelist

**Comment by pzoleex** [comment]
@mehul-m-prajapati 
From now you can trigger the test system via
"@kira-syslogng test this please;" command. You don't need to close/reopen or force push the pr (at least this is the theory, please try it)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mehul-m-prajapati** [comment]
@pzoleex : Thanks

**Comment by furiel** [comment]
@mehul-m-prajapati I created another PR (https://github.com/balabit/syslog-ng/pull/2806) based on your work. Thank you for your effort, I carried most parts with your signoff. I am closing this in favor or #2806.

**Pull request closed without merging**
