### PR TITLE
Add Elasticsearch 2 destination with Shield support

### PR DESCRIPTION
**Pull request by lbudai**
Support ElasticSearch 2 with Shield.

Example config:
```
destination d_elastic {
    elasticsearch2(
        client_lib_dir(/usr/share/elasticsearch/lib)
        client_mode("shield")
        cluster("es-syslog-ng")
        index("es-syslog-ng")
        port("9300")
        server("vagrant-es-server")
        type("slng_test_type")
        resource("/opt/syslog-ng-ose-3.8/etc/elasticsearch.yml")
    );
};
```

### CODE REVIEW

**Comment by ihrwein** [comment]
Could include a simple configuration snippet in the description of the PR, please? Thanks.

**Comment by lbudai** [comment]
Yep, originally it was cherry-picked, but I can modify it.

**Comment by lbudai** [comment]
I also rebased the PR against master.

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
