### PR TITLE
tlscontext: use getter function to access X509 verify param

### PR DESCRIPTION
**Pull request by lbudai**
ssl_ctx_st structure is a non-exported interface (ssl/ssl_locl.h)

Fixes: #1234

Signed-off-by: Laszlo Budai <stentor.bgyk@gmail.com>

I did not test the PR.

@czanik: could you test it?

### CODE REVIEW

**Comment by czanik** [comment]
Just finished testing: compilation still fails with openssl 1.1

**Comment by lbudai** [comment]
before merging this, I'd wait for an ACK from @czanik

**Comment by czanik** [comment]
Patched a git head, generated dist tgz (on a machine with openssl 1.0 if that matters), copied the resulting tgz to Fedora and tried to build it. Compilation fails now at a different location:
```
  CC       lib/compat/lib_libsyslog_ng_la-openssl_support.lo
In file included from /usr/include/inttypes.h:25:0,
                 from /usr/include/openssl/e_os2.h:249,
                 from /usr/include/openssl/ssl.h:45,
                 from ./lib/compat/openssl_support.h:28,
                 from lib/compat/openssl_support.c:1:
/usr/include/features.h:177:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
lib/compat/openssl_support.c: In function 'X509_get_extension_flags':
lib/compat/openssl_support.c:20:11: error: dereferencing pointer to incomplete type 'X509 {aka struct x509_st}'
   return x->ex_flags;
           ^~
lib/compat/openssl_support.c:21:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [Makefile:10052: lib/compat/lib_libsyslog_ng_la-openssl_support.lo] Error 1
make[1]: *** [Makefile:13531: all-recursive] Error 1
```

**Comment by czanik** [comment]
The problem seems to be, that there are multiple openssl versions on rawhide (and also in the build chroot, as some syslog-ng dependencies need 1.0 others 1.1) and this confuses syslog-ng:
```
bash-4.3# rpm -qa | grep openssl
compat-openssl10-1.0.2j-5.fc26.x86_64
openssl-devel-1.1.0c-4.fc26.x86_64
openssl-libs-1.1.0c-4.fc26.x86_64
```

**Comment by lbudai** [comment]
I'd close this PR and open a new one: #1281

**Pull request closed without merging**
