### PR TITLE
F/fix formatting results

### LINKED ISSUE #773: Integer overflow in numerical operations template function
Whilst trying to compute a rate, I stumbled upon an "undocumented feature".
Consider the following config:
```
@version:3.7
@include "scl.conf"

source s_stdin { file("/dev/stdin" flags(no-parse)); };
source s_internal { internal(); };

rewrite r_bar {
  set('$(/ "2147483648" "1")', value(result));
};
destination d_debug { file("/dev/stdout" template("$(format-json -s nv-pairs)\n")); };

log {
  source(s_stdin);
  source(s_internal);
  rewrite(r_bar);
  destination(d_debug);
};
```

The result is the following:

```
{"result":"-2147483648","SOURCE":"s_internal","PROGRAM":"syslog-ng","PID":"31443","MESSAGE":"Initializing destination file writer; template='/dev/stdout', filename='/dev/stdout'"}
```

Unsurprisingly, the result is correct if using `2147483647=2^32/2-1` as input

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #773

### CODE REVIEW

**Comment by bazsi** [comment]
the patch itself looks sane to me, however I miss a few testcases in test_basicfuncs, should be trivial to add.

**Comment by ihrwein** [comment]
You are right, I forgot to check them. Tomorrow I will extend them.

**Comment by lbudai** [comment]
@ihrwein : any update? :-)

**Comment by ihrwein** [comment]
@lbudai PR updated with 4 unit tests

**Comment by ihrwein** [comment]
@bazsi I added your suggestion and force pushed this branch

**Comment by bkil-syslogng** [comment]
`-Werror -Wconversion` would have caught this

**Pull request merged**
