### PR TITLE
Remove elastic v1 support

### PR DESCRIPTION
**Pull request by lbudai**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
I found a few additional places:

syslog-ng.conf.5.xml: 
```
<link linkend="configuring-destinations-elasticsearch">elasticsearch</link>
```

README.md:99
```
/usr/share/elasticsearch/lib/elasticsearch-1.4.0.jar
```

policy:69
```
modules/java-modules/(dummy|elastic|elastic-v2|hdfs|http|kafka|[^/]*$)
```

**Comment by lbudai** [comment]
@furiel: thanks!
(so I have to touch the policy file again :/ )

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
