### PR TITLE
gitignore: tags file and build directory

### PR DESCRIPTION
**Pull request by Kokan**
Inspired by https://github.com/balabit/syslog-ng/pull/2784 

well I use the `build` directory to build shame on me, but `ag` could exclude this directory from searching IF it is listed in `.gitignore`
the other `tags` as well
(I know I could create my own ignore file, but well..)

### CODE REVIEW

**Comment by furiel** [comment]
You can create global gitignore file. It works perfectly for me. Add something similar to you `.gitconfig.`

```
[core]
	excludesfile = /home/furiel/.gitignore_global
```

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by Kokan** [comment]
@furiel yeah I know, but that's what I want to avoid, I prefer to track in the same repository what I do not want to track (keep your enemies local).

**Comment by lbudai** [comment]
After .ctags is added, on today I also realized that I should had to add the .tags file to .gitignore :)
thanks

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by szemere** [comment]
Two other workarounds for this situation:

A)
**.gitignore** files could ignore themselves. (Unfortunately it is too late for us, to put it in the root directory, since we are already version tracking a .gitignore file there.)

```
syslog-ng$: ls -a foo/
.gitignore
bar

syslog-ng$: cat foo/.gitignore
.gitignore
bar
foobar
```
Neither `foo/bar.foo` or `foo/.gitignore` will show up in the output of a `git status` command.

B)
edit the `.git/info/exclude` file directly.


Version A is more transparent, but it only works with subdirectories. Version B works together with the already existing .gitignore file, but it smells a little bit.

**Pull request merged**
