### PR TITLE
Astyle for headers, minor travis improvement

### PR DESCRIPTION
**Pull request by Kokan**
* Astyle check apply for headers also
* Astyle excludeded afamqp, while it should have excluded only the rabbitmq-c submodule
* Travis now shows what should be changed in the style-check job (calling format and git diff)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Pls lets merge this after the plugin refactor, I would like to avoid rebasing it, as its a pretty large patchset.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by Kokan** [comment]
I tried the latest(`3.0.1`) `astyle` to see what improvement it has over the current `2.05.1`.

Based on the result (see below attached diff), I do not think it worth the effort now.

@bazsi patch is merged, so it is not blocked by it anymore.

```
$ astyle --version
Artistic Style Version 2.05.1
$ PATH=./:$PATH astyle --version
Artistic Style Version 3.0.1
$ PATH=./:$PATH ./scripts/style-checker.sh format
$ git diff
```

```diff
diff --git a/lib/debugger/debugger.c b/lib/debugger/debugger.c
index 20bec32f8..c433f423e 100644
--- a/lib/debugger/debugger.c
+++ b/lib/debugger/debugger.c
@@ -101,7 +101,7 @@ _display_source_line(LogExprNode *expr_node)
   if (f)
     {
       while (fgets(buf, sizeof(buf), f) && lineno < expr_node->line)
-               lineno++;
+        lineno++;
       if (lineno != expr_node->line)
         buf[0] = 0;
       fclose(f);
diff --git a/lib/gprocess.c b/lib/gprocess.c
index 56f82c671..c7509a09e 100644
--- a/lib/gprocess.c
+++ b/lib/gprocess.c
@@ -1502,7 +1502,7 @@ g_process_process_no_caps(const gchar *option_name G_GNUC_UNUSED, const gchar *v
 static GOptionEntry g_process_option_entries[] =
 {
   { "foreground",   'F', G_OPTION_FLAG_REVERSE, G_OPTION_ARG_NONE,     &process_opts.mode,              "Do not go into the background after initialization", NULL },
-  { "process-mode",   0,                     0, G_OPTION_ARG_CALLBACK, g_process_process_mode_arg ,     "Set process running mode", "<foreground|background|safe-background>" },
+  { "process-mode",   0,                     0, G_OPTION_ARG_CALLBACK, g_process_process_mode_arg,     "Set process running mode", "<foreground|background|safe-background>" },
   { "user",         'u',                     0, G_OPTION_ARG_STRING,   &process_opts.user,              "Set the user to run as", "<user>" },
   { "uid",            0,  G_OPTION_FLAG_HIDDEN, G_OPTION_ARG_STRING,   &process_opts.user,              NULL, NULL },
   { "group",        'g',                     0, G_OPTION_ARG_STRING,   &process_opts.group,             "Set the group to run as", "<group>" },
diff --git a/lib/logmsg/nvtable.h b/lib/logmsg/nvtable.h
index aefa86403..fa35d14e3 100644
--- a/lib/logmsg/nvtable.h
+++ b/lib/logmsg/nvtable.h
@@ -309,7 +309,7 @@ static inline gchar *
 nv_table_get_ofs_table_top(NVTable *self)
 {
   return (gchar *) &self->data[self->num_static_entries * sizeof(self->static_entries[0]) +
-                               self->index_size * sizeof(NVIndexEntry)];
+                                                        self->index_size * sizeof(NVIndexEntry)];
 }
 
 static inline gboolean
diff --git a/lib/logproto/tests/test_logproto.c b/lib/logproto/tests/test_logproto.c
index 740a169dc..205d5586c 100644
--- a/lib/logproto/tests/test_logproto.c
+++ b/lib/logproto/tests/test_logproto.c
@@ -52,7 +52,7 @@ test_log_proto_base(void)
 
   /* check if error state is not forgotten unless reset_error is called */
   proto->status = LPS_ERROR;
-  assert_proto_server_status(proto, proto->status , LPS_ERROR);
+  assert_proto_server_status(proto, proto->status, LPS_ERROR);
   assert_proto_server_fetch_failure(proto, LPS_ERROR, NULL);
 
   log_proto_server_reset_error(proto);
diff --git a/lib/parser/parser-expr.h b/lib/parser/parser-expr.h
index 3e6b2932e..f3f5cd621 100644
--- a/lib/parser/parser-expr.h
+++ b/lib/parser/parser-expr.h
@@ -62,7 +62,7 @@ log_parser_process(LogParser *self, LogMessage **pmsg, const LogPathOptions *pat
                    gssize input_len)
 {
   if (input_len < 0)
-        input_len = strlen(input);
+    input_len = strlen(input);
   return self->process(self, pmsg, path_options, input, input_len);
 }
 
diff --git a/lib/rewrite/rewrite-groupset.c b/lib/rewrite/rewrite-groupset.c
index ca8abbbd2..732862a2c 100644
--- a/lib/rewrite/rewrite-groupset.c
+++ b/lib/rewrite/rewrite-groupset.c
@@ -102,7 +102,7 @@ log_rewrite_groupset_clone(LogPipe *s)
 {
   LogRewriteGroupSet *self = (LogRewriteGroupSet *) s;
   LogRewriteGroupSet *cloned = (LogRewriteGroupSet *)log_rewrite_groupset_new(self->replacement,
-      log_pipe_get_config(&self->super.super) );
+                               log_pipe_get_config(&self->super.super) );
   value_pairs_unref(cloned->query);
   cloned->query = value_pairs_ref(self->query);
   cloned->vp_func = self->vp_func;
diff --git a/lib/template/compiler.c b/lib/template/compiler.c
index a131fcb10..fd7cc0d21 100644
--- a/lib/template/compiler.c
+++ b/lib/template/compiler.c
@@ -225,8 +225,8 @@ is_macro_name(gchar c)
 
 #define STEP_BY_TRUE(p, x) while(x) p++;
 
-                                  static void
-                                  log_template_compiler_add_elem(LogTemplateCompiler *self, gchar *start, gint macro_len, gchar *default_value)
+static void
+log_template_compiler_add_elem(LogTemplateCompiler *self, gchar *start, gint macro_len, gchar *default_value)
 {
   gint macro = log_macro_lookup(start, macro_len);
   if (macro == M_NONE)
diff --git a/lib/template/tests/test_template_compile.c b/lib/template/tests/test_template_compile.c
index 45ce1419a..d545df072 100644
--- a/lib/template/tests/test_template_compile.c
+++ b/lib/template/tests/test_template_compile.c
@@ -417,7 +417,7 @@ test_template_function_bad1(void)
   assert_failed_template_compile("$( hello \\tes\t\t\t value(xyz \"value with spaces\" 'test value with spa\"ces')",
                                  "Invalid template function reference, missing function name or inbalanced '(', error_pos='73'");
   assert_compiled_template(text =
-                           "error in template: $( hello \\tes\t\t\t value(xyz \"value with spaces\" 'test value with spa\"ces')",
+                             "error in template: $( hello \\tes\t\t\t value(xyz \"value with spaces\" 'test value with spa\"ces')",
                            default_value = NULL, macro = M_NONE, type = LTE_MACRO, msg_ref = 0);
 }
 
@@ -427,7 +427,7 @@ test_template_function_bad2(void)
   assert_failed_template_compile("$( hello \\tes\t\t\t value xyz \"value with spaces\" 'test value with spa\"ces'",
                                  "Invalid template function reference, missing function name or inbalanced '(', error_pos='72'");
   assert_compiled_template(text =
-                           "error in template: $( hello \\tes\t\t\t value xyz \"value with spaces\" 'test value with spa\"ces'",
+                             "error in template: $( hello \\tes\t\t\t value xyz \"value with spaces\" 'test value with spa\"ces'",
                            default_value = NULL, macro = M_NONE, type = LTE_MACRO, msg_ref = 0);
 }
 
diff --git a/lib/value-pairs/tests/test_value_pairs.c b/lib/value-pairs/tests/test_value_pairs.c
index 19396c3fe..978810878 100644
--- a/lib/value-pairs/tests/test_value_pairs.c
+++ b/lib/value-pairs/tests/test_value_pairs.c
@@ -113,7 +113,7 @@ testcase(const gchar *scope, const gchar *exclude, const gchar *expected, GPtrAr
       ValuePairsTransformSet *vpts = value_pairs_transform_set_new("*");
 
       for (i = 0; i < transformers->len; i++)
-             value_pairs_transform_set_add_func(vpts, g_ptr_array_index(transformers, i));
+        value_pairs_transform_set_add_func(vpts, g_ptr_array_index(transformers, i));
       value_pairs_add_transforms(vp, vpts);
     }
 
diff --git a/lib/value-pairs/value-pairs.c b/lib/value-pairs/value-pairs.c
index da79a68a3..359212bed 100644
--- a/lib/value-pairs/value-pairs.c
+++ b/lib/value-pairs/value-pairs.c
@@ -280,8 +280,8 @@ vp_msg_nvpairs_foreach(NVHandle handle, gchar *name,
   GString *sb;
 
   inc = (name[0] == '.' && (vp->scopes & VPS_DOT_NV_PAIRS)) ||
-  (name[0] != '.' && (vp->scopes & VPS_NV_PAIRS)) ||
-  (log_msg_is_handle_sdata(handle) && (vp->scopes & (VPS_SDATA + VPS_RFC5424)));
+        (name[0] != '.' && (vp->scopes & VPS_NV_PAIRS)) ||
+        (log_msg_is_handle_sdata(handle) && (vp->scopes & (VPS_SDATA + VPS_RFC5424)));
 
   for (j = 0; j < vp->patterns->len; j++)
     {
@@ -890,7 +890,7 @@ value_pairs_free (ValuePairs *vp)
   guint i;
 
   for (i = 0; i < vp->vpairs->len; i++)
-         vp_pair_conf_free(g_ptr_array_index(vp->vpairs, i));
+    vp_pair_conf_free(g_ptr_array_index(vp->vpairs, i));
 
   g_ptr_array_free(vp->vpairs, TRUE);
 
diff --git a/modules/afsmtp/afsmtp.c b/modules/afsmtp/afsmtp.c
index 475690734..aa0eab861 100644
--- a/modules/afsmtp/afsmtp.c
+++ b/modules/afsmtp/afsmtp.c
@@ -79,9 +79,9 @@ afsmtp_wash_string (gchar *str)
   gint i;
 
   for (i = 0; i < strlen (str); i++)
-         if (str[i] == '\n' ||
-             str[i] == '\r')
-           str[i] = ' ';
+    if (str[i] == '\n' ||
+        str[i] == '\r')
+      str[i] = ' ';
 
   return str;
 }
@@ -549,8 +549,8 @@ __check_rcpt_tos(AFSMTPDriver *self)
     {
       AFSMTPRecipient *rcpt = (AFSMTPRecipient *)l->data;
       gboolean rcpt_type_accepted = rcpt->type == AFSMTP_RCPT_TYPE_BCC ||
-      rcpt->type == AFSMTP_RCPT_TYPE_CC  ||
-      rcpt->type == AFSMTP_RCPT_TYPE_TO;
+                                    rcpt->type == AFSMTP_RCPT_TYPE_CC  ||
+                                    rcpt->type == AFSMTP_RCPT_TYPE_TO;
 
       if (rcpt->template && rcpt_type_accepted)
         {
diff --git a/modules/dbparser/pdbtool/pdbtool.c b/modules/dbparser/pdbtool/pdbtool.c
index e62621900..92b2720ee 100644
--- a/modules/dbparser/pdbtool/pdbtool.c
+++ b/modules/dbparser/pdbtool/pdbtool.c
@@ -862,7 +862,7 @@ pdbtool_walk_tree(RNode *root, gint level, gboolean program)
   gint i;
 
   for (i = 0; i < level; i++)
-         printf(" ");
+    printf(" ");
 
   if (root->parser)
     printf("@%s:%s@ ", r_parser_type_name(root->parser->type), log_msg_get_value_name(root->parser->handle, NULL));
@@ -879,10 +879,10 @@ pdbtool_walk_tree(RNode *root, gint level, gboolean program)
   printf("\n");
 
   for (i = 0; i < root->num_children; i++)
-         pdbtool_walk_tree(root->children[i], level + 1, program);
+    pdbtool_walk_tree(root->children[i], level + 1, program);
 
   for (i = 0; i < root->num_pchildren; i++)
-         pdbtool_walk_tree(root->pchildren[i], level + 1, program);
+    pdbtool_walk_tree(root->pchildren[i], level + 1, program);
 }
 
 static gint
@@ -976,10 +976,10 @@ pdbtool_dictionary_walk(RNode *root, const gchar *progname)
     }
 
   for (i = 0; i < root->num_children; i++)
-         pdbtool_dictionary_walk(root->children[i], progname);
+    pdbtool_dictionary_walk(root->children[i], progname);
 
   for (i = 0; i < root->num_pchildren; i++)
-         pdbtool_dictionary_walk(root->pchildren[i], progname);
+    pdbtool_dictionary_walk(root->pchildren[i], progname);
 }
 
 static GOptionEntry dictionary_options[] =
diff --git a/modules/java/proxies/java-destination-proxy.c b/modules/java/proxies/java-destination-proxy.c
index 8c5dbb797..904284a03 100644
--- a/modules/java/proxies/java-destination-proxy.c
+++ b/modules/java/proxies/java-destination-proxy.c
@@ -109,7 +109,7 @@ __load_destination_object(JavaDestinationProxy *self, const gchar *class_name, c
     }
 
   self->dest_impl.mi_on_message_queue_empty = CALL_JAVA_FUNCTION(java_env, GetMethodID, self->loaded_class,
-      "onMessageQueueEmptyProxy", "()V");
+                                              "onMessageQueueEmptyProxy", "()V");
   if (!self->dest_impl.mi_on_message_queue_empty)
     {
       msg_error("Can't find method in class",
@@ -151,10 +151,10 @@ __load_destination_object(JavaDestinationProxy *self, const gchar *class_name, c
     }
 
   self->dest_impl.mi_get_name_by_uniq_options = CALL_JAVA_FUNCTION(java_env,
-      GetMethodID,
-      self->loaded_class,
-      "getNameByUniqOptionsProxy",
-      "()Ljava/lang/String;"
+                                                GetMethodID,
+                                                self->loaded_class,
+                                                "getNameByUniqOptionsProxy",
+                                                "()Ljava/lang/String;"
                                                                   );
   if (!self->dest_impl.mi_get_name_by_uniq_options)
     {
diff --git a/modules/json/format-json.c b/modules/json/format-json.c
index 638fcd18e..86bab186a 100644
--- a/modules/json/format-json.c
+++ b/modules/json/format-json.c
@@ -165,10 +165,10 @@ tf_json_value(const gchar *name, const gchar *prefix,
       gsize v_len = value_len;
 
       if (type == TYPE_HINT_INT32 &&
-          (fail = !type_cast_to_int32(value, &i32 , NULL)) == TRUE)
+          (fail = !type_cast_to_int32(value, &i32, NULL)) == TRUE)
         r = type_cast_drop_helper(on_error, value, "int32");
       else if (type == TYPE_HINT_INT64 &&
-               (fail = !type_cast_to_int64(value, &i64 , NULL)) == TRUE)
+               (fail = !type_cast_to_int64(value, &i64, NULL)) == TRUE)
         r = type_cast_drop_helper(on_error, value, "int64");
       else if (type == TYPE_HINT_DOUBLE &&
                (fail = !type_cast_to_double(value, &d, NULL)) == TRUE)
diff --git a/tests/unit/test_logwriter.c b/tests/unit/test_logwriter.c
index f227e2f3b..a2ee2c8c2 100644
--- a/tests/unit/test_logwriter.c
+++ b/tests/unit/test_logwriter.c
@@ -206,7 +206,7 @@ Test(logwriter, test_logwriter)
 
   nr_of_cases = sizeof(test_cases) / sizeof(test_cases[0]);
   for (i = 0; i < nr_of_cases; i++)
-         _assert_logwriter_output(test_cases[i]);
+    _assert_logwriter_output(test_cases[i]);
 
   app_shutdown();
 }
diff --git a/tests/unit/test_msgparse.c b/tests/unit/test_msgparse.c
index e72e8bfba..760397a63 100644
--- a/tests/unit/test_msgparse.c
+++ b/tests/unit/test_msgparse.c
@@ -631,7 +631,7 @@ Test(msgparse, test_expected_sd_pairs_1)
     { ".SDATA.exampleSDID@0.eventSource", "Application"},
     { ".SDATA.exampleSDID@0.eventID", "1011"},
     { ".SDATA.examplePriority@0.class", "high"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -707,7 +707,7 @@ Test(msgparse, test_expected_sd_pairs_2)
   struct sdata_pair expected_sd_pairs_test_2[] =
   {
     { ".SDATA.exampleSDID@0.iut", "3"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -746,7 +746,7 @@ Test(msgparse, test_expected_sd_pairs_3)
     { ".SDATA.origin.ip", "exchange.macartney.esbjerg"},
     { ".SDATA.meta.sequenceId", "191732"},
     { ".SDATA.EventData@18372.4.Data", "MSEXCHANGEOWAAPPPOOL.CONFIG\" -W \"\" -M 1 -AP \"MSEXCHANGEOWAAPPPOOL5244fileserver.macartney.esbjerg CDG 1 7 7 1 0 1 1 7 1 mail.macartney.esbjerg CDG 1 7 7 1 0 1 1 7 1 maindc.macartney.esbjerg CD- 1 6 6 0 0 1 1 6 1 " },
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -775,7 +775,7 @@ Test(msgparse, test_expected_sd_pairs_4)
   struct sdata_pair expected_sd_pairs_test_4[] =
   {
     { ".SDATA.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.i", "ok_32"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -815,13 +815,13 @@ Test(msgparse, test_expected_sd_pairs_too_long)
   struct sdata_pair expected_sd_pairs_test_5[] =
   {
     { ".SDATA.a.i", "]\"\\"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct sdata_pair expected_sd_pairs_test_5b[] =
   {
     { ".SDATA.a.i", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -877,7 +877,7 @@ Test(msgparse, test_unescaped_too_long_message_parts)
   struct sdata_pair expected_sd_pairs_test_6[] =
   {
     { ".SDATA.a.i", "ok"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -978,7 +978,7 @@ Test(msgparse, test_expected_sd_pairs_tz_known)
   {
     /*{ ".SDATA.timeQuality.isSynced", "0"},
     { ".SDATA.timeQuality.tzKnown", "0"},*/
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -1010,7 +1010,7 @@ Test(msgparse, test_expected_sd_pairs_enterprise_id)
     /*{ ".SDATA.timeQuality.isSynced", "0"},
     { ".SDATA.timeQuality.tzKnown", "1"},*/
     { ".SDATA.origin.enterpriseId", "1.3.6.1.4.1"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
@@ -1041,7 +1041,7 @@ Test(msgparse, test_expected_sd_pairs_without_sd_param)
     /*{ ".SDATA.timeQuality.isSynced", "0"},
     { ".SDATA.timeQuality.tzKnown", "1"},*/
     { ".SDATA.origin.enterpriseId", "1.3.6.1.4.1"},
-    {  NULL , NULL}
+    {  NULL, NULL}
   };
 
   struct msgparse_params params[] =
```

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_COMMENT

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_STATUS
 No test results found.
Build FAILURE, $TEST_DESC_COMMENT

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_COMMENT

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_COMMENT

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
