### PR TITLE
warning elimination: pointer arithmetics

### LINKED ISSUE #1960: warning elimination: pointer arithmetics
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the pointer related warnings.
```
     16 [-Wpointer-arith]
     34 [-Wpointer-sign]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

### PR DESCRIPTION
**Pull request by tsunderino**
Resolve #1960

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
@tsunderino I am going to review the hole change, but one thing stands out as of now. Please update the cmake build as you did for autotools.

**Comment by furiel** [comment]
Oh I see the cmake update requested by @Kokan is yet to be added. Other than that, looks good to me.

**Comment by tsunderino** [comment]
@Kokan I've updated the cmake build, thanks for pointing that out!

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
