### PR TITLE
Small java code refactor

### PR DESCRIPTION
**Pull request by Kokan**
Just two small refactor in the java module.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
thanks for refactoring this

**Comment by Kokan** [comment]
@lbudai the force push remove your comments, there was only one I did not address about setting the `global_jvm` to `NULL` in the free. This patchset started not to have `global_jvm` at all, it made sense to first move that setting to where the singleton related code are. I would keep it as is.

**Comment by lbudai** [comment]
@Kokan : ok

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
