### PR TITLE
test_transport_mapper: rewrite test cases in criterion

### LINKED ISSUE #2614: convert test-transport-mapper to criterion
Use Criterion to rewrite this unit test.

- [ ] test-transport-mapper
- [ ] test-transport-mapper-inet
- [ ] test-transport-mapper-unix

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Resolves #2614

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
