### PR TITLE
Lib: rewrite merge-grammar script from Perl to Python

### PR DESCRIPTION
**Pull request by presidento**
Just because there were a TODO item about it, and I think this one is much more readable.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
This is really appreciated, and looks good. It fails on cmake though with
```
Traceback (most recent call last):
  File "../../lib/merge-grammar.py", line 35, in <module>
    grammar_file = os.path.join(os.environ['top_srcdir'], 'lib/cfg-grammar.y')
  File "/opt/python/2.7.13/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)

KeyError: 'top_srcdir'
```

**Comment by bazsi** [comment]
Once the build issues are fixed, this can go in, I am approving it in a second.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by presidento** [comment]
@bazsi done.

**Comment by presidento** [comment]
Thanks!

**Pull request merged**
