### PR TITLE
Docbook-XSL path caused errors for docbook.xsl file is placed different

### PR DESCRIPTION
**Pull request by gregory094**
paths on different platforms. Solved using online path to fetch DTD
file.

Solve: #428 

Signed-off-by: Gergo Nagy <gergo.nagy@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
I am not sure the build hosts reach the internet, even though we do include
the build products in our tarball. So if this works in debian/fedora
infrastructure, then this can be a good solution.


-- 
Bazsi

**Comment by lbudai** [comment]
One possible solution: get `docbook.xsl` in `autogen.sh` and we could provide the file in the release tarball.

**Comment by gregory094** [comment]
:+1: That's a good idea. Let's fetch the file in `autogen.sh` to doc/docbook.xsl and use that in doc/Makefile.am as an relative path. `make dist` can copy that file to the same location to provide tarball for offline installation of syslog-ng.

**Comment by algernon** [comment]
Fetching at autogen.sh time is okay-ish, as long as I can ask it not to do that, and supply my own path.

For Debian, I'd like to be able to build from a git checkout (thus, no make dist), without touching the network (because that doesn't work on buildds). I can teach the build scripts to supply the correct path, no problem, and I'd like to continue having that option available.

**Comment by gregory094** [comment]
Okey. What about fetching `docbook.xsl` from the web in `autogen.sh` and then one could use an option in `configure` whether he wants to build manpages from local? Or you can simply add `XSL_STYLESHEET` specifying the path to your file. 

**Example:**
`configure --xsl-stylesheet-path=<path>` (The default would be the fetched one)
**OR**
`configure XSL_STYLESHEET=<path>` (it's not so elegant I think)

**Comment by algernon** [comment]
My requirement is that `autogen.sh` must not fail without network access (provided I can pre-install everything it may need). Something like how `skip_submodules=1 ./autogen.sh` skips submodules, `skip_xsl=1 ./autogen.sh` could do something similar. Running `make` would still default to the path the file would have been downloaded to, but the download wouldn't happen.

With this setup, the default is to download and use it, but I can opt not to download the DTD, and use a preinstalled one.

**Comment by gregory094** [comment]
Fetching dependencies is not that simple that I've thought previously. We should clone all the docbook repo that is pretty big (~50Mb) so I wouldn't do that. In my opinion the best solution is making the generation of manpages optional using a `configure` enabler. 
Next to it I would add another option that can build the manpages online as I've showed that in my first solution. (It would solve the problem of non-debian users.) The default would be the present hardcoded path when one wants to compile docs using the option I've just mentioned.

**Pull request closed without merging**
