### PR TITLE
logsource: create AckTracker in log_source_init

### PR DESCRIPTION
**Pull request by lbudai**
I think it is better to open a dedicated PR for this small change.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@bazsi:  you are right, the motivation is that...

* short version: 
... I need two types of "ringbuffer" (or, `AckRecordContainer`) and I don't want to add a 9th parameter (`enable-dynamic-window`) to `log_source_options()`

* long version
In case of dynamic windowing we cannot use a fixed-size `Ringbuffer`, and I changed the code that uses a `list<AckRecord>` unconditionally, so even in the static case. I think it is problem as this linked list based implementation has a negative performance impact (and I think, it is possible to eliminate, or decrease the impact, but not now - due to lack of time). One of the key point was during the dynamic-window development is to guarantee that the static case won't be affected the changes, we want to be sure that we won't break anything with the new feature. Flow-control is like blood in human body: implementation is not too big(code of lines...), but it is everywhere, like a fractal, this is why we want to be very careful.
So I'm going to open another PR soon which is about refactoring the `LateAckTracker` and make it possible to create two kind of trackers: one uses a fixed size `Ringbuffer` as an `AckRecordStore`, the other will use the linked list based `AckRecordStore`.

**Pull request merged**
