### PR TITLE
python binding: optional return values (for lazies :))

### PR DESCRIPTION
**Pull request by tsunderino**
Closes: #2488

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
@kjira-syslog-ng: ok to est

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@tsunderino: thanks for the pull request.

What if someone just forget to return the result of an insert? 
What the original issue suggests (at least to me) is that we should let Python modules loose messages without any control. I know that this is true in many cases (when a Python library not propagates back a result), but after this PR our message is that we don’t care return values... and we encourage Python module developers to be ‘lazies’.

**Comment by pzoleex** [comment]
I agree with lbudai, if no return value it's a way to allow developers to lose messages even accidentally

**Comment by tsunderino** [comment]
@lbudai 
@pzoleex 
I agree with you in that message loss is possible if send() defaults to True, but the requested functionality might be useful for open() and init(). I think send() is the only call site where it is harmful.
If I understand the code correctly, syslog-ng drops the message if a parser returns False, so a default True for parse() can avoid message loss.

What do you think? Can I keep those changes or should I just close the full PR?

**Comment by lbudai** [comment]
@tsunderino: I think only the `send` method where this approach is problematic (so don't close the PR).

**Comment by furiel** [comment]
@tsunderino we discussed this topic in a team meeting, and concluded that we would prefer the strict signature in every methods. My original proposal is invalidated, that's why I am closing this PR. Despite the outcome, thank you for your contribution, we value the effort you made into the topic. We will contact you with a small swag as compensation.

**Comment by tsunderino** [comment]
@furiel Thanks for the gifts, I especially love the tshirt!
I understand your point, but the parse() method is still bothering me a bit. Wouldn't it be useful to return default True in case something bad happens during parsing the message?

**Comment by furiel** [comment]
Me feels returning false is better. My thought process is something like this: a filter parses a message, then based on business logic, permits or denies the message. In case the parsing part fails, that means the message does not fit even into the domain of the filter, hence the right thing is to drop the message. Letting through a message that cannot be controlled by a filter can still break things. Let's say, someone wants to write messages to a file, where the filename comes from a ${.patterndb.class}, and there is a filter that makes sure the template will be not empty. Letting through the message due to error and empty template would mean the message is still lost, because the syslog-ng cannot write to an empty filename.

**Comment by tsunderino** [comment]
I see, thanks for the thorough explanation.

**Pull request closed without merging**
