### PR TITLE
F/syslog debun extensions

### PR DESCRIPTION
**Pull request by jszigetvari**
contrib/syslog-debun: PKI information gathering and general improvements

    * PKI information gathering
    * extended scope of information gathered
    * bug fixes

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Great stuff here. Some notes.

I think it would make sense to request debug output to ISSUE_TEMPLATE.md so
that it is requested from those who open issues.

btw: is the debun script part of the installation image right now? I've
just checked and it isn't. So it should be moved out of contrib (maybe in
scripts/?) and then added to the installation packages, so it is really
easy for users to run. Right now, one would have to download it from github
explicitly. Not many people would do that.

also, the name of the script should be changed, it is "syslog-debun",
whereas we are shipping syslog-ng as a package, so it should be
syslog-ng-debun or something like that. Also, "debun" is not really
intuitive for first time users and it would probably make sense to display
a help screen when launching the script instead of going right into
information collection.

Cheers,
Bazsi

-- 
Bazsi

**Comment by czanik** [comment]
It is: see https://github.com/balabit/syslog-ng/pull/1485

A better name is very welcome. For now I put it next to documentation but with a better name it could be installed next to syslog-ng to the sbin directory.

**Comment by bazsi** [comment]
#1485 doesnt add this into the binaries only the source, so it won't be
available to most of the users.

**Comment by jszigetvari** [comment]
If that's okay for you, I will change the name in the next bunch of changes I'll make. (ETA: a few month's time.)
I just did not want to remove the legacy of @pasztor on my own, because he is the one who originally authored and added this script.

**Pull request merged**
