### PR TITLE
afsocket: simplify restoring writer from reload cache

### PR DESCRIPTION
**Pull request by presidento**
Based on the comments of @lbudai at https://github.com/balabit/syslog-ng/pull/1723#issuecomment-339361112.

This is only refactor, the behavior should be identical as the previous implementation.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by presidento** [comment]
@kira-syslogng retest this please.

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@presidento thanks!

**Pull request merged**
