### PR TITLE
stats-query: change separator to ; && follow-up tests

### PR DESCRIPTION
**Pull request by kvch**
Please note that changes in #1478 should be followed up after merging this.

Signed-off-by: Noémi Ványi <sitbackandwait@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests passed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests passed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests passed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests passed on test branch: master and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-stats-query-change-separator;

note: do not merge this pr even if this test passed, need more tests

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: pzolee-stats-query-change-separator and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kvch** [comment]
I addressed the problems in the code. It can be merged after the tests are complete and #1479 is integrated to master.

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-stats-query-change-separator;

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: pzolee-stats-query-change-separator and test suite: functions

**Pull request merged**
