### PR TITLE
Improve the performance of value-pairs

### PR DESCRIPTION
**Pull request by bazsi**
This improves $(format-json) performance in an artifical test by about 40%. 

It also contains  a couple of other changes:
  * value-pairs split (so it superseeds PR #850)
  * couple of internal value-pairs refactors
  * utf8utils performance improvements

There's still room for improvement, with this the heap operations weight at about 15-20% in the profile, thus reducing the number of allocations will result in further performance improvements.

@faxm0dem would probably be happy about this.

### CODE REVIEW

**Comment by juhaszviktor** [comment]
Except my some minor notes it looks good :+1:

**Comment by bazsi** [comment]
I have now rebased & retested this branch against latest master.

Please review (and merge once done :)

**Comment by bazsi** [comment]
This branch is pretty fragile as it moves code around a lot. I'd appreciate feedback, at least on the value-pairs split part (with no intended functional changes), so we can merge that.

If there's a problem with the perf improvement stuff, I can split it off.

**Comment by ihrwein** [comment]
Could you rebase it? After that my :+1:  is here.

**Comment by bazsi** [comment]
Now I have rebased it against master as of today. As I see there are two :+1: already, so once travis is done this can be merged.

**Comment by dnsjts** [comment]
:+1:

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
