### PR TITLE
Elastic 2 fix bulk silent drop

### PR DESCRIPTION
**Pull request by lbudai**
@faxm0dem : could you check this?
#1342 is conflicting, so I'm open this new PR
(if you tested my changes, you can rebase your branch against master and then cherry pick my commit ;) )

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by faxm0dem** [comment]
it works, but the error message in `internal()` source isn't very helpful. Not sure where the null pointer exception comes from...

```
Dec  7 15:28:49 syslogng syslog-ng[12591]: Connect to ccosvm0968.in2p3.fr:9200 [ccosvm0968.in2p3.fr/172.17.0.208] failed: connect timed out;
Dec  7 15:28:49 syslogng syslog-ng[12591]: Exception occured: java.lang.NullPointerException\x0a     at org.syslog_ng.elasticsearch_v2.messageprocessor.http.HttpBulkMessageProcessor.flush(HttpBulkMessageProcessor.java:63)\x0a     at org.syslog_ng.elasticsearch_v2.messageprocessor.http.HttpBulkMessageProcessor.send(HttpBulkMessageProcessor.java:76)\x0a     at org.syslog_ng.elasticsearch_v2.messageprocessor.http.HttpMessageProcessor.send(HttpMessageProcessor.java:62)\x0a      at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.send(ESHttpClient.java:152)\x0a      at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.send(ElasticSearchDestination.java:95)\x0a    at org.syslog_ng.StructuredLogDestination.sendProxy(StructuredLogDestination.java:35)\x0a;
```

**Comment by lbudai** [comment]
@faxm0dem : well... we can change the error message, but this is come from the jest library.
(and I didn't touch this part of the code :) )

**Comment by faxm0dem** [comment]
I also have quite often the following message:

```
Dec  8 08:30:28 syslogng syslog-ng[12591]: Exception occured: java.lang.NullPointerException\x0a;
Dec  8 08:30:28 syslogng syslog-ng[12591]: Read timed out;
```

**Comment by lbudai** [comment]
When we got an `IOException`, we catch it and `jestResult` variable will be `null`...

**Comment by lbudai** [comment]
PR is updated with this change (->return when we got `IOException`).

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by faxm0dem** [comment]
Unfortunately with this change, messages are silently dropped again.
Back to square one 👎

**Comment by lbudai** [comment]
@faxm0dem : the logic is the same as in your PR... so you should get error messages when 
 * `IOException` occurs, or
 *  client.execute fails.

So your messages are still dropped while you don't get the error messages? This means that your messages are lost in somewhere else... (I mean there is no `IOException` and client.execute does not report any failures).

**Comment by faxm0dem** [comment]
Yes, messages are silently dropped:

* No error message
* Processed stat goes up
* Queued stat stays zero

I will investigate this further next week - but not before Thursday.

**Comment by faxm0dem** [comment]
I tried to dig into this deeper, but I realized the log events from the java program never make it to the internal() or system() or even STDERR.
I can see the messages from jest at startup:

```
[main] INFO io.searchbox.client.JestClientFactory - Idle connection reaping disabled...
```

but nothing thereafter

**Comment by faxm0dem** [comment]
I tried a few things, to no avail: total silence from syslog-ng (on STDOUT/STDERR, internal() and system():

* `jvm-options('-Dlog4j.debug -Dlog4j.configuration=/etc/syslog-ng/log4j.properties')
* `slf4j group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.13'` in modules/java-modules/elastic-v2/build.gradle
* setting log4j12 to log to a file using /etc/syslog-ng/log4j.properties

The logfile is never created, and nothing is on STDOUT of syslog-ng, except the usual JEST messages

**Comment by faxm0dem** [comment]
could this somehow be connected to #1149?

**Comment by lbudai** [comment]
@faxm0dem : I don't think so.

**Comment by lbudai** [comment]
@faxm0dem : I'll only have time for working on this on Friday.

**Comment by faxm0dem** [comment]
@lbudai okay, thank you!

**Comment by lbudai** [comment]
@faxmodem: let me summarize the issue

1. in case of bulk insert (and also in case of non-bulk insert...) when an error occurs, syslog-ng does not report any error
2. in case of bulk insert when it fails, syslog-ng just drops the messages

Your patch focuses on 1st point.
2nd point is unfortunately cannot be resolved until syslog-ng does not support late ack mechanism in java site: currently when the messages are passed to the java destination, syslog-ng increase the processed counter and release the message. We don't keep a messages on the queue that are
passed to the java destination (this is the case for Python destinations), we just send an early ACK, so it is not possible to ACK messages in asynchronous way.

**Comment by faxm0dem** [comment]
I understand in case of an error, we lose the batch of messages (as defined in `flush-limit`). But we should at least avoid losing the subsequent batches!

**Comment by lbudai** [comment]
Agree, and this is why we want to return with `false` from `flush()` when exception occurs. The problem is that it seems that we don't get the exception.

**Comment by faxm0dem** [comment]
can you reproduce the behaviour that whatever you log, even in normal flow, it's dropped even on STDIO when running syslog-ng in the FG?

**Comment by lbudai** [comment]
I think I found the root cause.

Each time when the `flush()` (which is called by `send()`) returns with `false`, we increment a counter.
When the value of this counter reach a limit (max retries), syslog-ng drops the messages.
Unfortunately this mechanism is not working for elastic http bulk because the counter never reach the limit.
The reason of this is that we call `init()` in `ESHttpClient.open()` after the java dst is suspended, which is happen when an error is reported by send, and the `init` creates a new Bulk.Builder and reset messagecounter.
The next send will be succeeded as the messagecounter has been reseted (`send()` returning true until the batch size has not been reached, then it calls `flush` which fails again, java dst suspended again, then open is called which calls init, and it will happen again and again, until all the messages are dropped silently). 

After I fix it, there will be another issue: drop counter is incremented by 1, not by batch size.

**Comment by faxm0dem** [comment]
good catch! what about the logging?

**Comment by lbudai** [comment]
JEST logs the connection failures in my environment. (I'm just using iptables rules for producing connection errors.)

**Comment by faxm0dem** [comment]
interesting. can you clarify what logging libraries are used?
IIRC it's SLF4J using [slf4j-simple] which is the [simple](https://www.slf4j.org/apidocs/org/slf4j/impl/SimpleLogger.html) logger and only logs to the console.

If that's correct, it will only be visible when running syslog-ng in the fg?

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@faxm0dem : yep, it is visible only on console.
But I can see 'failed to connect' logs and 'Multiple failures while sending' in the `internal()` logs after my latest changes.

**Comment by lbudai** [comment]
When I added this to `jvm_options` :  `-Dorg.slf4j.simpleLogger.logFile=/tmp/jest-slf4j.log` , it put some logs to the given file, but only some initialization related lines... and other still logged to the console.

**Comment by lbudai** [comment]
@faxm0dem : finally I was able to use log4j  (and configure a fileappender).
JEST has a logger and JEST uses the org.apache.commons.http which actually logs those lines that we are really interesed in (->connection errors). The problem is that it's hard to load the `log4j.properties`.
Currently I'm loading it programmatically with the help of PropertyContainer (and trust me, I tried several ways, but did not work and I wanted to see whether it is working or not, so I choose a temporary solution)
.
In syslog-ng config I added these:

```
jvm_options("-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger -Dorg.apache.commons.logging.LogFactory=org.apache.commons.logging.impl.LogFactoryImpl -Dlog4j.debug=true");
```

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by faxm0dem** [comment]
I just tested your recent changes, and it works as expected as far as the queue is concerned, thank you!
However, I'm still unable to see output from Jest even after using the `jvm_options` in my syslog-ng.conf.

**Comment by lbudai** [comment]
@faxmodem: with my last patch (and notes) I was able to get log messages from JEST :
```
options {
 jvm_options("-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger
-Dorg.apache.commons.logging.LogFactory=org.apache.commons.logging.impl.LogFactoryImpl
-Dlog4j.debug=true -Dlog4j.configuration=/tmp/log4j.properties");
};
```

and log4j.properties:
```
log4j.logger.org.elasticsearch=WARN
log4j.logger.org.apache.http=DEBUG, slng, fout
log4j.logger.org.apache.http.wire=DEBUG, slng, fout
log4j.logger.org.apache.http.impl.conn=DEBUG, slng, fout
log4j.logger.org.apache.http.impl.client=DEBUG, slng, fout
log4j.logger.org.apache.http.client=DEBUG, slng, fout

log4j.appender.slng=org.syslog_ng.logging.SyslogNgInternalLogger

log4j.appender.fout=org.apache.log4j.FileAppender
log4j.appender.fout.File=/tmp/log4jjjj.log
log4j.appender.fout.layout=org.apache.log4j.PatternLayout
log4j.appender.fout.layout.ConversionPattern=%d{HH:mm:ss} %-5p %c{1}:%L
- %m%n
```

( DEBUG messages maybe won't be handled by `internal` as they are printed to stderr... )

**Pull request merged**
