### PR TITLE
DbldPackages: Add missing packages to DBLD

### PR DESCRIPTION
**Pull request by mitzkia**
- add packages to pass tests in Kira

Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by Kokan** [comment]
This is a nice example. This PR cannot be merged even though this fixes the `Build FAILURE` issue with Kira. As Kira still uses the docker image created from the master, which is not correct.
Also it is possible to merge something that is going to break Kira, but won't be discovered only after merged :)

**Comment by mitzkia** [comment]
Sorry, I forgot to mention, @Kokan is absolutely right. 
The goal of this PR is to pass Kira testcases on PRs.

The detail description why getent specific testcase fails on our balabit/syslog-ng-xenial:latest image:
 * We have updated our xenial:latest image to the recent DBLD
 * The failing testcase in Kira uses getent command, but it returns with nothing. 
 * This is because the getent command wanted to use /etc/protocols file, but it does not exist in our image. 
 * The netbase package will install this file.

**Comment by furiel** [comment]
$ dpkg --listfiles netbase | grep protocols 
/etc/protocols

That part sounds good to me. But why do we need `systemd-sysv`?

**Comment by mitzkia** [comment]
Yes, the systemd-sysv package we needed because we want to run Kira tests also on Artful, and this package will contains the necessary /sbin/init file for us. On other platforms (until Xenial) this is already exist.

**Comment by furiel** [comment]
Why do we need /sbin/init? Entrypoint as `$ sleep infinity` can be an alternative?

**Pull request merged**
