### PR TITLE
F/python

### PR DESCRIPTION
**Pull request by bazsi**
Please consider my Python related work for merging. It ports the Python module in the incubator to the syslog-ng proper. 

It's not yet complete, but I intended to submit the functional parts to make it more accessible for everyone else.

I still have upcoming work that I've left out of this branch (e.g. template function support and "root" level Python language support), however those still have critical issues.

This one has much less test coverage than I would prefer (e.g. exactly None), at least an end-to-end test would be great to have. It's really difficult to do unit-like testing as most of it is just glue code.

Anyway, I indend to add some testing to the func-test suite in the nearfuture.

Please merge!
Thanks.

### CODE REVIEW

**Comment by bazsi** [comment]
I have rebased this against the latest master and also added an automated testcase to functest, and a few fixes that I've found while adding the testcase :)

It should be a better form for merging.

**Comment by lbudai** [comment]
Thanks! I'll try to review the patch in this week( +end :-) ).

**Comment by lbudai** [comment]
Nice work :-)

I had a list of questions/notes, but size of my list reduces as refactors are coming
 and after 5dc8ca83778ff82afb099f41507e1ee7668cb355 notes are gone...
(maybe buf1, buf2 not the best names for variables, but... well... it is OK)

One question:
Is there any other way for importing a python class than setting PYTHONPATH before running syslog-ng?

**Comment by bazsi** [comment]
I have some followup work and a few fixes in f/python-template-functions

That should conclude the python module for a short term until I submit my debugger cli in python work I worked on today.

You can avoid having to set PYTHONPATH by installing the extension module using a setup.py or something. Maybe we should also add /etc/syslog-ng or a subdirectory automatically. How do you do that with the Java plugin?

**Comment by lbudai** [comment]
In Java dest. we have an option for setting the classpath.

**Pull request merged**
