### PR TITLE
3.6/f/fix journal replay

### PR DESCRIPTION
**Pull request by lbudai**
This is actually not my PR, I've just create it from Bazsi's branch.
[containing fixes for the journal replay issue for 3.6]

### CODE REVIEW

**Comment by ihrwein** [comment]
Is it ready for merge? If that's so I'd merge it.

**Comment by bazsi** [comment]
Looks good to me.

**Comment by lbudai** [comment]
Yes, it is.

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
