### PR TITLE
F/set target jvm

### PR DESCRIPTION
**Pull request by ihrwein**
This PR sets the source compatibility and target JVM level to 1.7. It makes possible to compile the Java modules with Oracle JDK 1.8 and running them with OpenJDK 1.7.

### CODE REVIEW

**Comment by faxm0dem** [comment]
thanks!

**Comment by ihrwein** [comment]
It's working :)

The problem was that I forgot to set `project.buildDir = syslogBuildDir` in the top level Gradle project.

@lbudai Please review it, after that I'll remove the eclipse related commit and squash the others.

**Comment by lbudai** [comment]
Thanks!
It seems good for me, but before merge, I'd check your modification in my OBS environment.

**Comment by lbudai** [comment]
I checked it, it is working.

**Pull request merged**
