### PR TITLE
Dbld support for debian stretch

### PR DESCRIPTION
**Pull request by bazsi**
This builds on #2188, so should only be merged after that.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@bazsi Something went wrong here, because after merging #2188, it turned out that this PR contains only one line of change:

```diff
--- a/dbld/images/required-apt/stretch.txt
+++ b/dbld/images/required-apt/stretch.txt
@@ -3,6 +3,7 @@
 # required for configure
 libsystemd-dev
 openjdk-8-jdk
+man-db
```

I'm going to rebase and force-push this branch.
I would also rename the commit message to "dbld: add man-db as dependency to the stretch image", if you agree.

**Comment by bazsi** [comment]
That change is basically a NOP, as man-db is already installed as a build dependency. I've added that patch because I had a local docker/apparmor related discrepancy, that I tried to resolve. That also caused me to get distracted and that's why I didn't finish these PRs.

With that, this can be closed.

**Pull request closed without merging**
