### PR TITLE
Fix accepting negative versions in syslog-ng's configuration file

### LINKED ISSUE #869: Negative config version numbers
I've just noticed that we support negative version numbers after `@version`. Is this intended? We use `strtol` for the parsing. Also, the `user_version`  field in GlobalConfig also a signed integer.

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #869

---

This change is [Reviewable](https://reviewable.io/reviews/balabit/syslog-ng/875)

### CODE REVIEW

**Comment by MrAnno** [comment]
:+1:

**Comment by ihrwein** [comment]
rebased

**Comment by dnsjts** [comment]
:+1:

**Comment by bkil-syslogng** [comment]
Boo!
```
@version: 42.4294957319
@version: 4294967299.7
@version: 72057594037927939.7
@version: 4.x
@version: 3.7.6.5.4.3.2.1.ignition.orbital.launch-successful!
@version: -1.1031
@version: 42.-9977
```

**Comment by bkil-syslogng** [comment]
Threw up by `-Wconversion`.
`-Wsign-conversion` also looked under your skirt and found your G.int spot.
The other overflows would probably have been available to Frama-C.

**Comment by lbudai** [comment]
@bkil-syslogng : could you implement the testcases?
and @ihrwein : could you fix it?

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by presidento** [comment]
Unfortunately it does not fix the original problem.

**Pull request closed without merging**
