### PR TITLE
dbld: use automake.11 in debian environment

### PR DESCRIPTION
**Pull request by lbudai**
release tarball requires automake1.11

Signed-off-by: Laszlo Budai <laszlo.budai@balabit.com>

### CODE REVIEW

**Comment by lbudai** [comment]
@presidento : thanks , fixed :)

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Is there more information available on why automake 1.11 is required? is it something in our makefiles/configure.ac?

**Comment by lbudai** [comment]
It's a kind of OBS issue.
My first attempt was succeed but there was a problem so I had to rebuild my packages and somehow the build has failed...

**Comment by bazsi** [comment]
I believe we should eliminate old automake versions (which this Docker based tarball generation should enable), but for now I am merging this.

**Comment by bazsi** [comment]
btw, travis failed because of network connectivity errors.

**Pull request merged**
