### PR TITLE
Ivykis update fixes 0.42.1 release issue with iv_events

### PR DESCRIPTION
**Pull request by Kokan**
There was an event scheduling bug in the latest 0.42 ivykis, which caused syslog-ng to crash #1672.
This change updates the lib/ivykis submodule to the latest commit, which contains the ivykis correction.

Signed-off-by: kokan <peter.kokai@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by Kokan** [comment]
There is a released version of this fix: v0.42.2 buytenh/ivykis@4d62405
I updated the commit to that, only difference is a version bump.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
