### PR TITLE
elastic-v2: Force a flush on send if an out-of-band flush failed

### PR DESCRIPTION
**Pull request by algernon**
Because `flush` can be - and is - called out of band, any error it may report does not get back to syslog-ng when called this way. This in turn can result in undeliverable messages being stuck in the bulk batch, until the retry mechanism kicks in. And that can take a long time.

To lower the severity of the problem, a new flag is introduced, which is set by `flush` when it fails. The next time `send` is called, if this flag is set, it will force a `flush`, to trigger the retry mechanism properly. Once the `flush` succeeds, the flag is cleared.

We rely on the retry mechanism provided by `LogThreadedDestDriver` to clear out undeliverable messages from under us.

This is not the best fix, isn't even a proper fix, but it reduces the impact of the problem considerably, thus addressing the main concerns of #1993.

### CODE REVIEW

**Comment by algernon** [comment]
I tested this a little, and it appears to Do The Right Thing™, but I'd appreciate if @mcorbin or @abalage could give it a try, and see if it makes the issue bearable. It won't fix it completely, but should drastically reduce its impact (or so I hope).

Thanks in advance!

**Comment by kira-syslogng** [comment]
failure

**Comment by algernon** [comment]
Closing this one, because it doesn't do what I expected it to do. Will open a new PR once I have something better. Sorry for the noise!

**Comment by abalage** [comment]
I tested it but I still experience the same issue, even with lower flush-limit(10).
Once it dropped something the disk buffers size stops decreasing but still something gets logged into Elastic.

**Pull request closed without merging**
