### PR TITLE
tests: unit/test_zone.c LogStamp uninitialized field fixed

### LINKED ISSUE #726: tests/unit/test_zone fails on Unix epoch
`make check` had a failing test.

    test assertion failed: strcmp(target->str, "1970-01-01T00:00:00+00:00") == 0 line: 774

It was caused by an uninitialized field in the testing struct.

### PR DESCRIPTION
**Pull request by u2yg**
fixes #726

### CODE REVIEW

**Comment by ihrwein** [comment]
The gcc build fails, the clang is OK. Can you reproduce this on your machine?

**Comment by u2yg** [comment]
It works for me. I think it was an intermittent issue with the build
machine. Can we restart the build somehow?

**Comment by bazsi** [comment]
Rebasing the branch should help.

**Comment by ihrwein** [comment]
:+1: (just rebase, please)

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
