### PR TITLE
F/dbparser multiline patterns

### PR DESCRIPTION
**Pull request by bazsi**
This series of patches make it possible to match Windows style multiline logs easily from patterndb.

### CODE REVIEW

**Comment by bazsi** [comment]
do you see anything that would prevent this from being merged?

thanks

**Comment by ihrwein** [comment]
:+1: @lbudai any thoughts?  (@fekete-robert can be also interested in this PR)

**Comment by fekete-robert** [comment]
Why is the name of the parser LNSTRING? What does LN stand for? (From its functionality, I'd suggest EOL, or EOLSTRING)

**Comment by lbudai** [comment]
:+1:

**Comment by bazsi** [comment]
LN is for line, but you might be right about this not really intuitive.

what about NLSTRING? NL for new-line, the name of '\n'. that captures the fact that it parses until newline, it's pretty in-line with QSTRING and ESTRING.

**Comment by fekete-robert** [comment]
Maybe NLSTRING would work as well. For me, EOL sounds more intuitive, but we could try a little in-house poll. 
Also, since we are talking about multiline messages, wouldn't we need a parser that catches everything to the end of the message, even if it is more than one line? Or ANYSTRING works that way?

**Comment by fekete-robert** [comment]
Well, from a quick non-representative 4-person lightning research it seems that people recognize NLSTRING and EOLSTRING about equally, LNSTRING a bit less.
Sidenote that came out: the naming of the ANYSTRING parser and the greedy() option of the csv-parser should be named similarly, because they do the same thing.

**Comment by bazsi** [comment]
ANYSTRING eats everything till the end-of-message, newlines included.

I would go for NLSTRING.

Thanks for the feedback.

**Comment by bazsi** [comment]
I have pushed the patches now to change LNSTRING to NLSTRING.

As I got positive feedback on the rest of the patches, I am merging this as soon as travis reports success.

**Comment by abalage** [comment]
Does "pdbtool match" support testing of multiline patterns?
Apparently it tries to match line by line.

tested on 3.8 HEAD

**Comment by bazsi** [comment]
yes, it does.

        <patterns>
          <pattern>Balabit-PC\Balabit: Security Microsoft Windows security
auditing.: [Success Audit] A new process has been created.

Subject:
 Security ID:  @LNSTRING:.winaudit.SubjectUserSid@
 Account Name:  @LNSTRING:.winaudit.SubjectUserName@
 Account Domain:  @LNSTRING:.winaudit.SubjectDomainName@
 Logon ID:  @LNSTRING:.winaudit.SubjectLogonId@

Process Information:
 New Process ID:  @LNSTRING:.winaudit.NewProcessId@
 New Process Name: @LNSTRING:.winaudit.NewProcessName@
 Token Elevation Type: @LNSTRING:.winaudit.TokenElevationType@
 Creator Process ID: @LNSTRING:.winaudit.ProcessId@
 Process Command Line: @LNSTRING:.winaudit.CommandLine@

Token Elevation Type indicates the type of token that was assigned to the
new process in accordance with User Account Control policy.</pattern>



@LNSTRING@ and accepting CRLF line-endings are fresh features in 3.8


-- 
Bazsi

**Pull request merged**
