### PR TITLE
F/freebsd10 java support

### PR DESCRIPTION
**Pull request by lbudai**

### CODE REVIEW

**Comment by czanik** [comment]
Just checked, but I still get:
```
===>  Building for syslog-ng-devel-3.8.0b1_1
gmake[2]: Entering directory '/root/syslog-ng-devel/work/syslog-ng-3.8.0beta1'
mkdir -p modules/java/syslog-ng-core/classes
  GEN      modules/java/syslog-ng-core/classes/org/syslog_ng/LogMessage.class
javavm: warning: The use of 'javavm' as a synonym for 'java' is deprecated
Unrecognized option: -d
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
gmake[2]: *** [Makefile:14932: modules/java/syslog-ng-core/classes/org/syslog_ng/LogMessage.class] Error 1
gmake[2]: Leaving directory '/root/syslog-ng-devel/work/syslog-ng-3.8.0beta1'
*** Error code 1
```

**Comment by lbudai** [comment]
@czanik : in my FreeBSD environment it works well...

Could you send me you configure script [in a mail] ?

**Comment by lbudai** [comment]
@czanik : yeah, in my environment I had a local change. I've fixed the m4 file, so it should work  [at this time I've compiled an unmodified code].

**Comment by czanik** [comment]
@lbudai : thanks, this time it compiled fine. :+1:

**Comment by lbudai** [comment]
@juhaszviktor : something happened with Travis, now it is working again

**Comment by bkil-syslogng** [comment]
@lbudai The dozens of things merged to `master` made queues that were checking `master` pile up. This, coupled with a rush hour and a general overload. Builds in my own repo got queued for 10-15 minutes each in that time period as well, but they otherwise ran fine.

**Comment by juhaszviktor** [comment]
:+1:

**Comment by bkil** [comment]
I've now checked, and the outage incident was indeed documented. It affected the sudo VM (i.e., non-container) builds and was caused by forced image updates.
* https://www.traviscistatus.com/incidents/11hp8bhkrkn7
* https://www.traviscistatus.com/incidents/2p40l49r3yxd

We should bookmark this for future reference:
* https://www.traviscistatus.com/

**Pull request merged**
