### PR TITLE
Log HTTP response error codes in HTTP destination

### PR DESCRIPTION
**Pull request by MrAnno**
Fixes: #669 

Signed-off-by: Laszlo Varady <laszlo.varady@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
This looks good to me, I was just wondering if we could make java logs a bit more integrated to syslog-ng internal logging style.

:+1:

**Comment by ihrwein** [comment]
:+1:

**Comment by lbudai** [comment]
@bazsi: you mean that we could use 
this one:
`HTTP response error; error_code ='404' `
instead of this:
`HTTP response code error: 404`
?

It's doable. @MrAnno ?

**Comment by bazsi** [comment]
I am not sure how java generated log messages appear in general. But yeah,
that's what I meant, and just for this log message but all of them.

This is fine, the formatting should change as a whole in a  unified manner.

**Comment by MrAnno** [comment]
Currently, the InternalMessageSender interface enables to send messages with different priorities but without any tags.

`msg_event_suppress_recursions_and_send(msg_event_create(pri, c_str, NULL));`

**Comment by bazsi** [comment]
I consider this an omission of the original implementation which should be
fixed. I wouldn't try to determine priorities when to do it, as there are
many things to improve and this is just one of them.

But java destinations should be just as integrated with syslog-ng as if
they were written in C.

**Comment by MrAnno** [comment]
Oh, I see. I will create a new issue about this.

**Comment by lbudai** [comment]
I'd merge this as-is, then a new PR should fix the java logmessage formatting issue.

**Comment by bazsi** [comment]
I agree.

-- 
Bazsi

**Comment by ihrwein** [comment]
I've merged it but I forget to ask for a rebase. I hope that the master is OK.

**Comment by lbudai** [comment]
we will see... :-)

**Comment by bkil-syslogng** [comment]
The integration protection that I have outlined earlier would have both caught this, and assured us whether this would be safe.

**Pull request merged**
