### PR TITLE
TLS improvements

### LINKED ISSUE #942: Syslog-ng TLS server: no shared cipher
Hello!
I attempted to create a secure logging system with mutual authentication using syslog-ng 3.7.2 in gentoo according to these manuals for [client](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/procedure-configuring-mutual-tls-client.html) and for [server](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/procedure-configuring-mutual-tls-client.html). The problem is when client tries to connect to server the server drops the connection with the **tls_error='SSL routines:ssl3_get_client_hello:no shared cipher'** and the client reports that handshake failed and closes the connection, however when using bare openssl in s_server and s_client mode with same configuration the connection establishes successfully. Also when I try to connect syslog-ng client to openssl s_server it`s working and openssl accepts connection, but when I try to connect openssl s_client to syslog-ng server, it fails with the same error (SSL routines:ssl3_get_client_hello:no shared cipher).

This is configuration for server:

```
@version: 3.7
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);
        stats_freq(43200);
        mark_freq(3600);
        use-dns(yes);
        keep-hostname(yes);
        use-uniqid(yes);
};

source s_system {
        system();
};
source s_internal {
        internal();
};

source s_net {
        syslog(
                ip("10.0.1.7")
                port("6514")
                transport("tls")
                tls(
                        peer-verify(required-trusted)
                        ca-dir('/etc/syslog-ng/keys/ca.d')
                        key-file('/etc/syslog-ng/keys/server.key')
                        cert-file('/etc/syslog-ng/keys/server.crt')
                        trusted-dn("C=UA,O=COMPANY,OU=SERVERS,CN=*,title=SYSLOG")
                ));
};

destination d_file {
        file("/var/log/messages");
};

log {
        source(s_system);
        source(s_internal);
        source(s_net);
        destination(d_file);
};
```

This is configuration for client:

```
@version: 3.7
@include "scl.conf"

options {
        threaded(yes);
        chain_hostnames(no);
        stats_freq(43200);
        mark_freq(3600);
        use-dns(yes);
        keep-hostname(yes);
        use-uniqid(yes);

};

source src {
        internal();
};

destination messages {
                file("/var/log/messages");
};

destination d_network {
        syslog(
                "10.0.1.7"
                port("6514")
                transport("tls")
                tls(
                        ca-dir('/etc/syslog-ng/keys/ca.d')
                        key-file('/etc/syslog-ng/keys/server.key')
                        cert-file('/etc/syslog-ng/keys/server.crt')
                )
        );
};

log {
        source(src);
        destination(d_network);
        destination(messages);
};
```

### PR DESCRIPTION
**Pull request by MrAnno**
This PR contains

- a medium-sized refactor in tlscontext
- minor fixes
- TLS features:
    - startup time `ssl-options()` and `peer-verify()` check
    - startup time `key_file`, `cert_file`, `ca_dir`, `crl_dir` and `cipher_suite` check
    - **ECDH  cipher support** (OpenSSL 1.0.1, 1.0.2, 1.1.0) with the `ecdh-curve-list()` option (only available >= 1.0.2)
        - for < 1.0.2, a hard-coded curve is used
        - for >= 1.0.2, automatic curve selection is used (the `ecdh-curve-list()` option can restrict this list)
    - **DH cipher support** with the `dhparam-file()` option
        - if the option is not specified, fallback RFC 3526 parameters are used

Example usage:
```
$ openssl dhparam -out /dh/dh2048.pem 2048

syslog(
  port(4444)
  transport(tls)
  tls(
    ecdh-curve-list("prime256v1:secp384r1") # <---- new
    dhparam-file("/dh/dh2048.pem") # <---- new
    ca-dir("/ca-dir")
    key-file("/key/key.pem")
    cert-file("/cert/cert.pem")
    cipher-suite("ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256") # <-- finally works
    peer-verify("required-trusted")
    ssl-options(no-sslv2, no-sslv3, no-tlsv1)
  )
);
```

This PR includes #1450 with minor modifications.

Important question:
**Should I remove the DH fallback mechanism?**
I'm using RFC 3526 parameters, but the `get_rfc3526_prime_2048()` function of OpenSSL is not officially documented.

TODO:
- [x] Write tests for Kira
- [x] Test manually with OpenSSL 1.0.1 (CentOS 7)
  - `ecdh-curve-list()` is ignored here
- [x] Test manually with OpenSSL 1.0.2 (Ubuntu 16.04)
- [x] Test manually with OpenSSL 1.1.0 (Arch Linux)

Fixes #942
@Viaguld @ouarak

--------------------------------------------------------------------------------------

#### Medium-sized refactor in tlscontext
  - tlscontext: move the declarations of variables to their initialization point
  - tlscontext: extract TLS context setup from setup_session()
  - tlscontext: refactor TLS peer certificate verification setup
  - tlscontext: extract TLS option setup from setup_context()
  - tlscontext: extract _print_tls_session_error() from setup_context()
  - tlscontext: make internal fields and methods private
  - tlscontext: move SSL context creation to tls_context_new()

#### Minor fixes
  - tlscontext: fix the type of ssl_error

#### Startup time option check
  - tlscontext: change the interface of lookup_verify_mode and lookup_options
  - tlscontext: add setters
  - afsocket: use the setters of TLSContext with parse-time error check
  - transport-mapper: add virtual init() function
  - tlscontext: make setup_context() public
  - afsocket: validate TLS options at init time

#### ECDH and DH support
  - tlscontext: add ECDH support
  - tlscontext: add optional curve_list
  - afsocket: add curve-list() option to grammar
  - tlscontext: add optional dhparam_file field
  - afsocket: add dhparam-file() option to grammar

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
This series is a huge improvement in the code structure and adds some good features. Kudos for doing this and for making the branch/commits to read like a prose. It was easy to review, and actually I was curious what the next patches would bring as i was reading the series.

Well done.

I have some nitpicks, but the code is good enough as it is.

**Comment by MrAnno** [comment]
@bazsi Thank you. :)

I had to force-push everything, it would have been hard to use fixup commits here.

You can execute `git diff` on the backup branch: MrAnno/syslog-ng@0c9f7aa5ad7421163bb273c95528e3ecedc1ac97
#### Changes
- lookup function --> tls_context_set_verify_mode_by_name
- lookup function --> tls_context_set_ssl_options_by_name
- _print_tls_session_error --> _print_and_clear_tls_session_error
- curve-list --> ecdh-curve-list
- ecdh ifdefs to compat/openssl --> openssl_ctx_setup_ecdh()

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by MrAnno** [comment]
Please don't merge this PR, I'm going to work on it next Friday.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by MrAnno** [comment]
@kira-syslogng retest this please test branch=mranno-tls-improvements;

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: mranno-tls-improvements and test suite: functions

**Comment by bazsi** [comment]
It still looks good to me. I dont want to merge it at this point, as I figure a release is in the works. I would do it after the release unless @lbudai overrides that.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by presidento** [comment]
We need before merge:
- update tests by @pzoleex 
- create alias for new TLS options by @MrAnno

**Comment by pzoleex** [comment]
the tests looks good for me

**Comment by MrAnno** [comment]
Done.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
