### PR TITLE
Fix message corruption caused by a bug in the subst() rewrite rule

### PR DESCRIPTION
**Pull request by MrAnno**
In case of `LogMatcherPcreRe`, the `matches` array may contain -1 values.

https://www.pcre.org/original/doc/html/pcreapi.html

>  It is possible for capturing subpattern number n+1 to match some part of the subject when subpattern n has not been used at all. For example, if the string "abc" is matched against the pattern (a|(z))(bc) the return from the function is 4, and subpatterns 1 and 3 are matched, but 2 is not. When this happens, both values in the offset pairs corresponding to unused subpatterns are set to -1.

> Offset values that correspond to unused subpatterns at the end of the expression are also set to -1. For example, if the string "abc" is matched against the pattern (abc)(x(yz)?)? subpatterns 2 and 3 are not matched. The return from the function is 2, because the highest used capturing subpattern number is 1, and the offsets for for the second and third capturing subpatterns (assuming the vector is large enough, of course) are set to -1. 

#### Config
```
rewrite r_indirect {
    set("indirect: ${MSG}", value(".indirect"));
};

rewrite r_test {
    subst('(a|(((((((((z))))))))))(bc)', ".", value(".indirect") type(pcre));
};

source s_s { file("/dev/stdin"); };
destination d_d { file ("/dev/stdout" template("${.indirect}")); };

log {
    source(s_s);
    rewrite(r_indirect);
    rewrite(r_test);
    destination(d_d);
};
```

#### Input
```
test: abc padding padding padding padding padding padding padding padding padding
```

#### Invalid indirect values (ofs, len)
```
Setting indirect value; msg='0x7de3ec0', name='2', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='3', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='4', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='5', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='6', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='7', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='8', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='9', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='0x7de3ec0', name='10', ref_handle='388', ofs='65535', len='0'
```

#### Valgrind output
```
Invalid read of size 2
   at 0x4C32720: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x5194FE0: g_string_insert_len (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
   by 0x4E7AF03: log_matcher_pcre_re_replace (logmatcher.c:754)
   by 0x4EBB123: log_matcher_replace (logmatcher.h:91)
   by 0x4EBB219: log_rewrite_subst_process (rewrite-subst.c:61)
   by 0x4EBA5E0: log_rewrite_queue (rewrite-expr.c:49)
   by 0x4EBA4BA: log_pipe_queue (logpipe.h:340)
   by 0x4EBA356: log_pipe_forward_msg (logpipe.h:303)
   by 0x4EBA6E0: log_rewrite_queue (rewrite-expr.c:60)
   by 0x4E7B531: log_pipe_queue (logpipe.h:340)
   by 0x4E7B3CD: log_pipe_forward_msg (logpipe.h:303)
   by 0x4E7B54A: log_pipe_queue (logpipe.h:344)
 Address 0x7de5f22 is 514 bytes inside a block of size 872 free'd
   at 0x4C2FD5F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x51797D7: g_realloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
   by 0x4ED41FA: nv_table_realloc (nvtable.c:698)
   by 0x4ECE30C: log_msg_set_value_indirect (logmsg.c:633)
   by 0x4ECE54A: log_msg_set_match_indirect (logmsg.c:669)
   by 0x4E7A81C: log_matcher_pcre_re_feed_backrefs (logmatcher.c:552)
   by 0x4E7AEAC: log_matcher_pcre_re_replace (logmatcher.c:748)
   by 0x4EBB123: log_matcher_replace (logmatcher.h:91)
   by 0x4EBB219: log_rewrite_subst_process (rewrite-subst.c:61)
   by 0x4EBA5E0: log_rewrite_queue (rewrite-expr.c:49)
   by 0x4EBA4BA: log_pipe_queue (logpipe.h:340)
   by 0x4EBA356: log_pipe_forward_msg (logpipe.h:303)
```

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Wow, I would really like to understand how the root cause was identified.

On Dec 6, 2017 16:59, "László Várady" <notifications@github.com> wrote:

In case of LogMatcherPcreRe, the matches array may contain -1 values.

https://www.pcre.org/original/doc/html/pcreapi.html

It is possible for capturing subpattern number n+1 to match some part of
the subject when subpattern n has not been used at all. For example, if the
string "abc" is matched against the pattern (a|(z))(bc) the return from the
function is 4, and subpatterns 1 and 3 are matched, but 2 is not. When this
happens, both values in the offset pairs corresponding to unused
subpatterns are set to -1.

Offset values that correspond to unused subpatterns at the end of the
expression are also set to -1. For example, if the string "abc" is matched
against the pattern (abc)(x(yz)?)? subpatterns 2 and 3 are not matched. The
return from the function is 2, because the highest used capturing
subpattern number is 1, and the offsets for for the second and third
capturing subpatterns (assuming the vector is large enough, of course) are
set to -1.

Reproduction steps:
TODO
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/balabit/syslog-ng/pull/1801
Commit Summary

   - logmatcher: fix message corruption caused by invalid indexing

File Changes

   - *M* lib/logmatcher.c
   <https://github.com/balabit/syslog-ng/pull/1801/files#diff-0> (18)

Patch Links:

   - https://github.com/balabit/syslog-ng/pull/1801.patch
   - https://github.com/balabit/syslog-ng/pull/1801.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/pull/1801>, or mute the thread

**Comment by MrAnno** [comment]
@bazsi It will be disappointing for you :)

This issue was reported by one of our users. All I saw was a damaged NVTable, and these lines:
```
Setting indirect value; msg='.', name='2', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='.', name='3', ref_handle='388', ofs='65535', len='0'
Setting indirect value; msg='.', name='4', ref_handle='388', ofs='65535', len='0'
```

So I reduced the config and found the appropriate `log_msg_set_match_indirect()` call.

**Comment by MrAnno** [comment]
I've attached reproduction steps to the PR description.

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_COMMENT

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_COMMENT

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
