### PR TITLE
Fix OpenSSL 1.1 support

### LINKED ISSUE #1921: syslog-ng fails to build with openssl 1.1.0 (built with --disable-deprecated) - error: unknown type name 'CRYPTO_THREADID'
# syslog-ng

## Version of syslog-ng

```
3.14.1
```

## Platform

Gentoo Linux (https://bugs.gentoo.org/646952)

# Issue

## Failure

```
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/syslog-ng-3.14.1 --htmldir=/usr/share/doc/syslog-ng-3.14.1/html --libdir=/usr/lib64 --disable-docs --disable-java --disable-java-modules --disable-riemann --enable-manpages --localstatedir=/var/lib/syslog-ng --sysconfdir=/etc/syslog-ng --with-embedded-crypto --with-ivykis=system --with-module-dir=/usr/lib64/syslog-ng --with-pidfile-dir=/var/run --with-systemdsystemunitdir=/lib/systemd/system --disable-amqp --without-librabbitmq-client --disable-linux-caps --disable-sql --disable-geoip --disable-http --enable-ipv6 --disable-json --disable-mongodb --without-mongoc --disable-legacy-mongodb-options --disable-pacct --disable-python --disable-redis --disable-smtp --disable-spoof-source --disable-systemd --enable-tcp-wrapper
...
make -j4
...

libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I./lib -I./modules -I./lib -I./modules -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I./lib/eventlog/src -I./lib/eventlog/src -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -Wno-pointer-sign -mtune=native -O2 -pipe -Wall -pthread -c modules/dbparser/timerwheel.c  -fPIC -DPIC -o modules/dbparser/.libs/modules_dbparser_libsyslog_ng_patterndb_la-timerwheel.o
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I./lib -I./modules -I./lib -I./modules -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I./lib/eventlog/src -I./lib/eventlog/src -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -Wno-pointer-sign -mtune=native -O2 -pipe -Wall -pthread -c modules/dbparser/patternize.c  -fPIC -DPIC -o modules/dbparser/.libs/modules_dbparser_libsyslog_ng_patterndb_la-patternize.o
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.  -I./lib -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I./lib/eventlog/src -I./lib/eventlog/src      -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -mtune=native -O2 -pipe -Wall -pthread -c -o lib/tests_loggen_loggen-crypto.o `test -f 'lib/crypto.c' || echo './'`lib/crypto.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.  -I./lib -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I./lib/eventlog/src -I./lib/eventlog/src      -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -mtune=native -O2 -pipe -Wall -pthread -c -o lib/compat/tests_loggen_loggen-openssl_support.o `test -f 'lib/compat/openssl_support.c' || echo './'`lib/compat/openssl_support.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.  -I./lib -I./modules -I./lib -I./modules    -fPIC -fvisibility=hidden -I./modules/native -I./modules/native -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I./lib/eventlog/src -I./lib/eventlog/src      -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -mtune=native -O2 -pipe -Wall -pthread -c -o modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o `test -f 'modules/native/native-grammar.c' || echo './'`modules/native/native-grammar.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I.  -I./lib -I./modules -I./lib -I./modules    -fPIC -fvisibility=hidden -I./modules/native -I./modules/native -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I./lib/eventlog/src -I./lib/eventlog/src      -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -mtune=native -O2 -pipe -Wall -pthread -c -o modules/native/modules_native_libsyslog_ng_native_connector_a-native-parser.o `test -f 'modules/native/native-parser.c' || echo './'`modules/native/native-parser.c
lib/compat/openssl_support.c:128:17: error: unknown type name 'CRYPTO_THREADID'
 _ssl_thread_id2(CRYPTO_THREADID *id)
                 ^~~~~~~~~~~~~~~
lib/compat/openssl_support.c: In function '_init_threadid_callback':
lib/compat/openssl_support.c:136:3: warning: implicit declaration of function 'CRYPTO_THREADID_set_callback' [-Wimplicit-function-declaration]
   CRYPTO_THREADID_set_callback(_ssl_thread_id2);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/compat/openssl_support.c:136:32: error: '_ssl_thread_id2' undeclared (first use in this function)
   CRYPTO_THREADID_set_callback(_ssl_thread_id2);
                                ^~~~~~~~~~~~~~~
lib/compat/openssl_support.c:136:32: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:16021: lib/compat/tests_loggen_loggen-openssl_support.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:16972: all-recursive] Error 1
make: *** [Makefile:6955: all] Error 2
```

### PR DESCRIPTION
**Pull request by MrAnno**
Building OpenSSL without support for deprecated APIs revealed additional API changes.

Fixes #1921

Reproduction:
1. Build OpenSSL 1.1 without deprecated API support:
```
./config no-deprecated --prefix=/tmp/openssl
make -j4
make install
```

2. Configure and build syslog-ng as follows:
```
env PKG_CONFIG_PATH=/tmp/openssl/lib/pkgconfig ./configure
make -j4
```

TODO:
- [x] CMake

### CODE REVIEW

**Comment by kira-syslogng** [comment]
success

**Comment by MrAnno** [comment]
This pull request reorganizes a few lines of OpenSSL compatibility code. I'm pretty sure it's correct, but I've only tested with OpenSSL 1.1.0h and 1.0.2o (the supported versions).

@czanik Do you have platforms where older/unsupported OpenSSL versions are used by default? If so, can you compile my branch please?

**Comment by czanik** [comment]
- RHEL/CentOS 6 has openssl 1.0.1e
- SLES 11 has 0.9.8j

We can EoL SLES 11 support in OSE, but RHEL 6 is still one of our most important platform after RHEL 7. It is supported for yet another few years and is the base for AWS Linux.

**Comment by MrAnno** [comment]
@czanik Thank you for the quick answer! :)

My change should work fine with older OpenSSL versions as well.
I'll check 1.0.1e, can you give a try and compile my branch on SLES 11 (0.9.8j)?

**Comment by czanik** [comment]
Patched git sources and generated a release tarball using dbld. Tested compile on SLES 11 SP4, and it failed:
```
[   33s]   CC       lib/tests_loggen_loggen-crypto.o
[   33s] libtool: link: gcc -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -o iv_signal_thread_test iv_signal_thread_test.o  ./../src/.libs/libivykis.a -lrt -lpthread_nonshared -pthread
[   33s] /bin/sh ./libtool  --tag=CC   --mode=link gcc  -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error   -o iv_wait_test iv_wait_test.o ./../src/libivykis.la 
[   33s]   CC       lib/compat/tests_loggen_loggen-openssl_support.o
[   33s] libtool: link: gcc -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -o iv_wait_test iv_wait_test.o  ./../src/.libs/libivykis.a -lrt -lpthread_nonshared -pthread
[   33s] /bin/sh ./libtool  --tag=CC   --mode=link gcc  -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error   -o server server.o ./../src/libivykis.la 
[   33s] lib/compat/openssl_support.c:56: error: expected ')' before '*' token
[   33s] lib/compat/openssl_support.c: In function '_init_threadid_callback':
[   33s] lib/compat/openssl_support.c:64: warning: implicit declaration of function 'CRYPTO_THREADID_set_callback'
[   33s] lib/compat/openssl_support.c:64: error: '_ssl_thread_id2' undeclared (first use in this function)
[   33s] lib/compat/openssl_support.c:64: error: (Each undeclared identifier is reported only once
[   33s] lib/compat/openssl_support.c:64: error: for each function it appears in.)
[   33s] make[2]: *** [lib/compat/tests_loggen_loggen-openssl_support.o] Error 1
[   33s] make[2]: *** Waiting for unfinished jobs....
[   33s] /bin/sh ./libtool  --tag=CC   --mode=link gcc  -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error   -o server_thread server_thread-server.o ./../src/libivykis.la 
[   33s] libtool: link: gcc -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -o server server.o  ./../src/.libs/libivykis.a -lrt -lpthread_nonshared -pthread
[   33s] libtool: link: gcc -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -o server_thread server_thread-server.o  ./../src/.libs/libivykis.a -lrt -lpthread_nonshared -pthread
[   33s] Making all in contrib
[   33s] Making all in iv_getaddrinfo
[   33s] gcc -DHAVE_CONFIG_H -I. -I../..  -D_GNU_SOURCE -I../../src/include -I../../src/include   -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -MT test.o -MD -MP -MF .deps/test.Tpo -c -o test.o test.c
[   33s] gcc -DHAVE_CONFIG_H -I. -I../..  -D_GNU_SOURCE -I../../src/include -I../../src/include   -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -MT iv_getaddrinfo.o -MD -MP -MF .deps/iv_getaddrinfo.Tpo -c -o iv_getaddrinfo.o iv_getaddrinfo.c
[   33s] mv -f .deps/test.Tpo .deps/test.Po
[   33s] mv -f .deps/iv_getaddrinfo.Tpo .deps/iv_getaddrinfo.Po
[   33s] /bin/sh ../../libtool  --tag=CC   --mode=link gcc  -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error   -o test test.o iv_getaddrinfo.o ../../src/libivykis.la -lrt -lpthread_nonshared 
[   33s] libtool: link: gcc -O2 -g -pthread -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -Wno-error -o test test.o iv_getaddrinfo.o  ../../src/.libs/libivykis.a -lrt -lpthread_nonshared -pthread
[   33s] make[6]: Nothing to be done for `all-am'.
[   33s] Making all in misc
[   33s] make[5]: Nothing to be done for `all'.
[   33s] Making all in man3
[   33s] make[5]: Nothing to be done for `all'.
[   33s] make[1]: *** [all-recursive] Error 1
[   33s] make: *** [all] Error 2
```

**Comment by MrAnno** [comment]
@czanik Oops, that's unpleasant. I've fixed this. Thank you very much for your help.

**Comment by kira-syslogng** [comment]
success

**Comment by lbudai** [comment]
@MrAnno , @czanik : another test before merge?

**Comment by MrAnno** [comment]
It compiles on CentOS 6.9 (OpenSSL 1.0.1e).

**Comment by lbudai** [comment]
ok, then I push the merge button

**Pull request merged**
