### PR TITLE
Wildcard filesource

### PR DESCRIPTION
**Pull request by lbudai**
Wildcard filesource implementation.
Created by juhaszviktor.

I've created also an UML, here it is:
syslog-ng-wildcard filesource

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by lbudai** [comment]
@kira-syslogng : retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
