### PR TITLE
F/fix news 3.8

### PR DESCRIPTION
**Pull request by faxm0dem**
just a few fixes to the changelog

### CODE REVIEW

**Comment by lbudai** [comment]
@faxm0dem : thanks for the fixes, I wouldn't merge it as this kind of release note (automatically generated) will be completely removed in the next few days.

Writing release notes takes lot of time, and we just wanted to release a beta and we used an automated tool  (as an experiment - and we know: this tool has failed) for generating the release notes (this is why I mentioned that it may contain false information).

The final 3.8 will have a real release note (I'll write it manually as in case of former releases).

**Comment by faxm0dem** [comment]
np I was writing my own personal favourite new features to tweet about ;-)

**Comment by lbudai** [comment]
@faxm0dem : I'll release another beta soon, at this time I'll use another changelog generator (it is still under development as part of one of our GSoC projects, but I think it is a better tool that we've used previously) . If you have the time, you could take a look at the result :-)

**Comment by kvch** [comment]
Closing this PR, because 3.8 was released with proper `NEWS.md`.

**Pull request closed without merging**
