### PR TITLE
Fix queue counters race cond

### PR DESCRIPTION
**Pull request by lbudai**

### CODE REVIEW

**Comment by lbudai** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Kira-performance-test: Build SUCCESS

**Pull request merged**
