### PR TITLE
small fixes in preparation for 3.18 release

### PR DESCRIPTION
**Pull request by furiel**
- few memory leaks
- invalid read during reload with invalid configuration
- http error code 4xx -> drop instead of retry. 
- updated news file with #2345 

Thanks @bazsi for help with the investigations and fix!

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
I've started an internal test too. Please wait until merge.

**Comment by gaborznagy** [comment]
Thanks, finished testing, everything is passed.
Ready for merge!

**Comment by MrAnno** [comment]
@gaborznagy Thanks for the review/internal tests!

**Pull request merged**
