### PR TITLE
packaging: remove separate scl.conf

### LINKED ISSUE #1760: Can't get name by unique options; Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
# syslog-ng

## Version of syslog-ng

```
syslog-ng 3 (3.11.1)
Installer-Version: 3.11.1
Revision:
Compile-Date: Nov 15 2017 22:07:54
Module-Directory: /usr/local/lib/syslog-ng
Module-Path: /usr/local/lib/syslog-ng
Available-Modules: date,syslogformat,kvformat,disk-buffer,afstomp,confgen,json-plugin,linux-kmsg-format,afamqp,mod-java,stardate,csvparser,pseudofile,graphite,afprog,afuser,system-source,snmptrapd-parser,cef,tfgetent,dbparser,cryptofuncs,basicfuncs,affile,add-contextual-data,afsocket,map-value-pairs
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
Enable-Systemd: off
```

## Platform

FreeBSD 11.1 amd64

# Issue

Can't start when defining `elasticsearch2` destinations, trying to test elasticsearch with https://logz.io:

      client_mode("http")
      cluster_url("http://listener.logz.io:8070?token=token")

## Failure

```
Starting syslog_ng.
[main] INFO io.searchbox.client.AbstractJestClient - Setting server pool to a list of 1 servers: [http://listener.logz.io:8070?token=token]
[main] INFO io.searchbox.client.JestClientFactory - Using multi thread/connection supporting pooling connection manager
[main] INFO io.searchbox.client.JestClientFactory - Using default GSON instance
[main] INFO io.searchbox.client.JestClientFactory - Node Discovery disabled...
[main] INFO io.searchbox.client.JestClientFactory - Idle connection reaping disabled...
[2017-11-15T23:05:43.246738] Exception occured: java.lang.NullPointerException\x0a      at org.syslog_ng.elasticsearch_v2.client.http.ESHttpClient.getClusterName(ESHttpClient.java:162)\x0a    at org.syslog_ng.elasticsearch_v2.ElasticSearchDestination.getNameByUniqOptions(ElasticSearchDestination.java:108)\x0a       at org.syslog_ng.LogDestination.getNameByUniqOptionsProxy(LogDestination.java:97)\x0a;
[2017-11-15T23:05:43.246778] Can't get name by unique options;
[2017-11-15T23:05:43.246783] Name by uniq options is empty;
[2017-11-15T23:05:43.246795] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
/usr/local/etc/rc.d/syslog-ng: WARNING: failed to start syslog_ng
```

## Configuration

```
@version:3.11
@module mod-java
@include "scl.conf"
options {
    flush_lines(0);
    keep_hostname(yes);
    normalize_hostnames(yes);
    threaded(yes);
};
source      s_local   { system(); internal();   };
source      s_network { syslog(transport(tcp)); };
destination d_all { file ("/var/log/all.log"); };
destination d_elastic {
  elasticsearch2(
    client_mode("http")
    cluster_url("http://listener.logz.io:8070?token=token")
    index("syslog-ng_${YEAR}.${MONTH}.${DAY}")
    type("MY-TYPE")
    cluster("test")
    flush-limit("1000")
    template("$(format-json --scope rfc5424 --scope nv-pairs --exclude DATE --key ISODATE)")
    time-zone("UTC")
  );
};
log { source(s_network); destination(d_elastic); };
log { source(s_local); destination(d_all); };
```

Just in case java version:

```
java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### PR DESCRIPTION
**Pull request by lbudai**
Fixes #1760
Signed-off-by: Laszlo Budai <laszlo.budai@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
why do we have a separate scl.conf for the Debian package? I think we should just use the one in the scl/ directory. Am I missing something?

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by gaborznagy** [comment]
Fixes: #1760.

**Comment by lbudai** [comment]
@bazsi: it was part of the original packaging, I guess.
(in my fork I removed it, currently it is building, if works, then will udpate this PR)

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
It's working, so I think this PR is ready to merge.

**Comment by MrAnno** [comment]
lbudai/syslog-ng/pull/29 fixes the Travis CI build

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
