### PR TITLE
F/date parser stamp

### PR DESCRIPTION
**Pull request by bazsi**
Make it possible to specify the time-stamp type for date-parser()

### CODE REVIEW

**Comment by bazsi** [comment]
the clang build seem to have failed in the java build for some reason, but the gcc one seems to be ok.  Can we merge it this way? Does anyone know why the java build fails? The logs seem to be missing important details.

**Comment by czanik** [comment]
FreeBSD uses clang, just as Apple. So I'd prefer to have it working also with clang.

**Comment by ihrwein** [comment]
I think it's just a temporary problem with travis or AWS. I found this in the logs:

```
[1m> Building 22%[22m[14D[0K* What went wrong:
[1m> Building 22%[22m[14D[0KCould not resolve all dependencies for configuration ':common:testCompile'.
[1m> Building 22%[22m[14D[0K[33m> [39m
[1m> Building 22%[22m[14D[0K[1A[2CCould not resolve junit:junit:4.12.
[1m> Building 22%[22m[14D[0K  Required by:
[1m> Building 22%[22m[14D[0K      java-modules:common:unspecified
[1m> Building 22%[22m[14D[0K   
[1m> Building 22%[22m[14D[0K[1A[3C[33m> [39m
[1m> Building 22%[22m[14D[0K[1A[5CCould not GET 'https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom'.
```

I restarted the builds, hope it helps.

**Comment by ihrwein** [comment]
Now the gcc build fails with the same error ... :+1:

**Comment by bazsi** [comment]
how can you restart builds?


-- 
Bazsi

**Comment by ihrwein** [comment]
1. Log in in Travis with your GitHub account
1. You will see "Restart build" button under the Settings label (arrow in a circle)

image

**Pull request merged**
