### PR TITLE
pseudofile: fix potential fd leak on write error occurs

### PR DESCRIPTION
**Pull request by ibmibmibm**
Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
nice catch. thanks for submitting this patch.

**Pull request merged**
