### PR TITLE
Fix byteorder handling on bigendian systems in netmask6 filter

### LINKED ISSUE #476: Fix netmask6 filter on bigendian systems

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #476 

Signed-off-by: Tibor Benke <tibor.benke@balabit.com>

### CODE REVIEW

**Comment by ihrwein** [comment]
port-to: 3.6/master
port-to: 3.7/master

**Comment by lbudai** [comment]
:+1:

**Comment by ihrwein** [comment]
rebased

**Comment by dnsjts** [comment]
:+1:

**Comment by ihrwein** [comment]
@dnsjts Could you merge it, please?

**Pull request merged**
