### PR TITLE
Custom LGTM.com query for detecting uses of gmtime that are not covered by a lock

### PR DESCRIPTION
**Pull request by sjvs**
Here's an example of how to use LGTM's custom queries after a discussion here: https://discuss.lgtm.com/t/suppressions-in-c-code/1525/10

If you like the custom query: feel free to merge this so it's automatically run by LGTM.com. If you'd rather not have a custom query: feel fee to close this PR.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by bazsi** [comment]
ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@sjvs : thanks for the PR!

#2414 will make Travis happy

**Comment by sjvs** [comment]
@lbudai @bazsi: I think the tests have passed now. Mind having a look at merging this?

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@sjvs Thank you!

**Pull request merged**
