### PR TITLE
logreader/logwriter: fix race condition of idle timer and scheduled I/O job

### PR DESCRIPTION
**Pull request by gaborznagy**
There is a race condition between scheduled I/O operations in worker threads and closing the idle connections (response/ack_timeout timer).
There is no protection - in afsocket source-driver - to not destroy connections(readers), which have scheduled I/O operation (not like when we reap writers on file dest. side).

The idle timer is not stopped, just when an I/O operation finished and we would like to re-schedule the next action on source side (update_watches() ).
The timer can trigger a connection closing, although there is schedule I/O operation.

Timer should be stopped when we schedule an I/O.
This way we eliminate the race condition between 2 sides.
We do stop I/O polling (see calling log_reader_stop_watches() in log_reader_io_handle_in()), so stopping the idle timer makes sens.

UPDATE:
    About stop_idle_timer cals in update_watches:
    Initially I thought that calling idle_timer is unnecessary in update_watches,
    since we stop the timer in io_handle. I've ven put an assertion to the timer registration,
    disabling timer re-registering.
    I forgot that in case of suspend, we will call an update_watches again, where an idle_timer
    registration will fail due to the assertion.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by gaborznagy** [comment]
@kira-syslogng retest this please;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
@alltilla kindly pointed out that we should make LogReader and LogWriter symmetric.
Also the issue can occur there as well.

I'll add it soon and rerun some additional tests. marking as WIP until.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by gaborznagy** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
About stop_idle_timer calls in update_watches:
Initially I thought that calling idle_timer is unnecessary in update_watches, since we stop the timer in io_handle. 
I've even put an assertion to the timer registration, disabling timer re-registering.
I forgot that in case of suspend, we will call an update_watches again, where an idle_timer registration will fail due to the assertion.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
This pull request **fixes 1 alert** when merging b48c6a6b3876c347bf3bdf20ca3b7f1d1c535499 into b1620af43b0a749bd0631ee01e345623b280f195 - [view on LGTM.com](https://lgtm.com/projects/g/balabit/syslog-ng/rev/pr-2a17fc355f53f301eaab87a78d60e62c7309787b)

**fixed alerts:**

* 1 for Ambiguously signed bit\-field member

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by gaborznagy** [comment]
I have executed all additional test cases and they PASSED.
Removing WIP flag.

**Pull request merged**
