### PR TITLE
allow using new keywords in older config versions

### PR DESCRIPTION
**Pull request by bazsi**
The SCL does contain new keywords and doing conditionals there is more than difficult, not to mention that there's really no point.

This patch series tries to push all keywords to external modules and clean up the core keyword set (e.g. the null keyword that historically caused the entire keyword versioning is pushed down to csv and sql modules), which hopefully decreases the chances of a conflict between a keyword and a user identifier.

With all this in place, the patchset also removes keyword versioning entirely, eg. we would accept template-function even if we are running an older config version.

The changes are fragile, as there's a lot of boilerplate in this code and it is difficult to test, so I'd request careful review and if at all possible trying to use the new code with existing configurations.

### CODE REVIEW

**Comment by bazsi** [comment]
This should fix #796

**Comment by faxm0dem** [comment]
> With all this in place, the patchset also removes keyword versioning entirely

What user-perspective consequences does this imply?

**Comment by bazsi** [comment]
Sorry for not responding sooner with regards to the user perspective.

There shouldn't be too much of an issue really, before this patch keywords that were introduced later than the "@version" tag  were not recognized as keywords and assumed to be mere identifiers.

This was implemented as at one point SLES had a default syslog-ng configuration that had a "null" destination, and with syslog-ng 3.0 we introduced "null" as a keyword causing parsing failures in SLES:

```
destination null {
};
```
When we introduced the "null" keyword this caused the above configuration to fail.

The use of identifiers in the syslog-ng configuration grammar is not really widespread, they are only used as the names of sources/destinations/filters/parsers/rewrite rules, sometimes in generic options

By pushing most of the keywords to syslog-ng plugins, the collisions they would introduce are most likely avoided, as most new functionality will be pushed into plugins. By the time the parser of the plugin starts we don't often use identifiers.

And the conflict can always be worked around by placing the relevant token in quotes:

```
destination "null" {
};
```

With all this said, I think it is not really a risky change, apart from any implementation mistakes I may have made, but I reviewed stuff a couple of times and I invited the others to do the same.

**Comment by ihrwein** [comment]
:+1:

**Comment by bazsi** [comment]
@ihrwein if you are confident enough please merge it as well, or will @lbudai have a peek as well?

**Comment by faxm0dem** [comment]
thanks @bazsi for the explanation

**Comment by ihrwein** [comment]
@bazsi I'd wait till @lbudai take a look at it. After that I'll merge it.

**Comment by lbudai** [comment]
Hi,

I like this idea and I think, the code is OK.

Before we merge it, we should create an installer and give it to PZoli to run some(*lots* of) tests on it.

**Comment by lbudai** [comment]
I've created a `f/allow-new-keywords-with-old-config-versions-rebased-to-master` branch: there was a conflict in `modules/dbparser/dbparser-parser.c`, I've resolved it (didn't want to force push your branch).

**Comment by bazsi** [comment]
Feel free to force push my branches in this case. A comment would be nice,
but you can do it, do we won't have to bounce branches and PRs around.

**Comment by lbudai** [comment]
@bazsi: ok, then next time we will do it as you suggested.

**Comment by ihrwein** [comment]
I'm closing this as the rebased version is merged :)

**Pull request closed without merging**
