### PR TITLE
Simplify devshell - depend on #2188

### PR DESCRIPTION
**Pull request by szemere**
Since devshell is not using the common `all.txt,{distro}*.txt` pattern, removed the extra directories, and moved the install steps into a single place, inside the `devshell.dockerfile`

With #2188, we added explicit version numbers to all the older platforms, so removed the no longer required `all.txt`.
Added `travis.txt` as a separate platform, since we want to alter from trusty in this special case, and want to use the latest versions during the testing.

Test on DockerHub: https://hub.docker.com/r/szemere/syslog-ng-devshell/builds/bgsj2nawgugrayb7idhjglu/

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by szemere** [comment]
DBLD renvewal makes this PR obsolote.

**Pull request closed without merging**
