### PR TITLE
Fix compilation error on BSD

### LINKED ISSUE #1543: git head does not compile on FreeBSD
# syslog-ng

## Version of syslog-ng

git head snapshot as of June 16, 16:30

## Platform

FreeBSD 11.0 amd64

# Issue

## Failure

Does not compile. Using a self generated dist tgz from git head (used successfully on RPM distros) replacing 3.9.1 release source in /usr/ports/distfiles.

```
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I./lib -I./modules -I./lib -I./modules -I./modules/affile -I./modules/affile -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -pthread -I/usr/local/include/eventlog -I/usr/local/include -I/usr/include -I./lib/ivykis/src/include -I./lib/ivykis/src/include -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -pipe -fstack-protector -fno-strict-aliasing -Wall -pthread -MT modules/affile/modules_affile_libaffile_la-file-reader.lo -MD -MP -MF modules/affile/.deps/modules_affile_libaffile_la-file-reader.Tpo -c modules/affile/file-reader.c  -fPIC -DPIC -o modules/affile/.libs/modules_affile_libaffile_la-file-reader.o
mv -f modules/affile/.deps/modules_affile_libaffile_la-file-reader.Tpo modules/affile/.deps/modules_affile_libaffile_la-file-reader.Plo
/bin/sh ./libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I.  -I./lib -I./modules -I./lib -I./modules -I./modules/affile -I./modules/affile -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -pthread  -I/usr/local/include/eventlog  -I/usr/local/include  -I/usr/include   -I./lib/ivykis/src/include -I./lib/ivykis/src/include -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -O2 -pipe  -fstack-protector -fno-strict-aliasing -Wall -pthread -MT modules/affile/modules_affile_libaffile_la-wildcard-source.lo -MD -MP -MF modules/affile/.deps/modules_affile_libaffile_la-wildcard-source.Tpo -c -o modules/affile/modules_affile_libaffile_la-wildcard-source.lo `test -f 'modules/affile/wildcard-source.c' || echo './'`modules/affile/wildcard-source.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I./lib -I./modules -I./lib -I./modules -I./modules/affile -I./modules/affile -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -pthread -I/usr/local/include/eventlog -I/usr/local/include -I/usr/include -I./lib/ivykis/src/include -I./lib/ivykis/src/include -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -pipe -fstack-protector -fno-strict-aliasing -Wall -pthread -MT modules/affile/modules_affile_libaffile_la-wildcard-source.lo -MD -MP -MF modules/affile/.deps/modules_affile_libaffile_la-wildcard-source.Tpo -c modules/affile/wildcard-source.c  -fPIC -DPIC -o modules/affile/.libs/modules_affile_libaffile_la-wildcard-source.o
modules/affile/wildcard-source.c:328:60: error: use of undeclared identifier
      'O_LARGEFILE'
  self->file_reader_options.file_open_options.open_flags = DEFAULT_SD_OP...
                                                           ^
modules/affile/wildcard-source.c:28:67: note: expanded from macro
      'DEFAULT_SD_OPEN_FLAGS'
#define DEFAULT_SD_OPEN_FLAGS (O_RDONLY | O_NOCTTY | O_NONBLOCK | O_LARGEFILE)
                                                                  ^
1 error generated.
gmake[4]: *** [Makefile:11221: modules/affile/modules_affile_libaffile_la-wildcard-source.lo] Error 1
gmake[3]: *** [Makefile:14975: all-recursive] Error 1
gmake[2]: *** [Makefile:6107: all] Error 2
gmake[2]: Leaving directory '/usr/ports/sysutils/syslog-ng-devel/work/syslog-ng-3.9.1'
*** Error code 1
```

## Steps to reproduce

Compile syslog-ng git head on FreeBSD 11.0

### PR DESCRIPTION
**Pull request by MrAnno**
Fixes #1543
Tested on macOS.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by furiel** [comment]
I suggest including lfs.h into affile-common.h. As I see, affile-common.h is included at least indirectly to all relevant places.

**Comment by MrAnno** [comment]
Good idea, thanks.

**Comment by MrAnno** [comment]
Reconsidering this suggestion, relying on the transitive nature of the include directive is not the best idea.
@furiel What do you think?

**Comment by gaborznagy** [comment]
I don't think this is a bad design, I think affile-common.h should be considered as an interface.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
FYI: I am refactoring the affile-common.h interface to actually hide file
opening away from the actual affile source/dest proper. I don't mind which
solution you choose, file open flags should not be exposed to higher level
code, which I am trying to achieve with the refactor.

-- 
Bazsi

**Pull request merged**
