### PR TITLE
afinet_dest: add missing libnet_context destroy to afinet

### PR DESCRIPTION
**Pull request by szemere**
Added missing libnet_destroy() to afinet.

Signed-off-by: Laszlo Szemere <laszlo.szemere@balabit.com>

### CODE REVIEW

**Comment by szemere** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
Good catch.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@szemere : thanks :)

**Pull request merged**
