### PR TITLE
global options: support generator plugin

### PR DESCRIPTION
**Pull request by Kokan**
Fix
* generator plugin was not accepted in options block
* multiple semicolons were not accepted in a few place (for example in options)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
I can't think of a good use case, but we support plugins in context `LL_CONTEXT_OPTIONS`, so this functionality may turn out to be useful.

I validated the PR with this not-so-useful example block, but the last semicolon causes some problems:
```
block options setup-dns(use-dns()) {
	keep-hostname(no);
	use-dns(`use-dns`);
	use-fqdn(`use-dns`);
	dns-cache(`use-dns`);
};

options {
	setup-dns(use-dns(yes));
};
```

```
Error parsing global options, syntax error, unexpected ';'
12---->         setup-dns(use-dns(yes));
12---->                                ^
```

Removing the semicolon either after `dns-cache()` or after `setup-dns()` makes it work.

**Comment by Kokan** [comment]
I do not think either that there is *real* usecase - which cannot be solved better.
This was triggered via the mail list: https://lists.balabit.hu/pipermail/syslog-ng/2019-May/025294.html
(where actually somebody wanted to use it)

But even if it is not useful, it is an implementation bug; as generator plugin should act the same way as any other plugin.

The issue you found I consider as a general generator plugin bug, it does only replaces the `generator-name()` part and not the whole `generator-name();`, therefore it creates two `;;`, which is not accepted in every place.

**Comment by MrAnno** [comment]
I agree that the lack of the `cfg_lexer_push_context` call is a bug-like thing.
The underscore issue I mentioned is another bug, but it makes the whole functionality (that you've enabled) hard to use.

Do we want to fix the underscore issue in this PR or you prefer postponing it?

**Comment by Kokan** [comment]
well I planned to solve that issue when there is proper pre-processing;I'll give it a try, though if I do not like the patches I'll postpone the fix. (will report back on conclusion)

**Comment by Kokan** [comment]
I've found a way (not how initially wanted) to handle the multiple semicolon issue.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
Oh, that is tricky :)

**Pull request merged**
