### PR TITLE
syslog-ng.8.xml: remove unneeded default-modules section

### PR DESCRIPTION
**Pull request by gcsideal**
Signed-off-by: Laszlo Boszormenyi (GCS) <gcs@debian.org>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by furiel** [comment]
@kira-syslogng ok to test

**Comment by furiel** [comment]
@gcsideal there are two other occurrences in [L277](https://github.com/balabit/syslog-ng/blob/16b70ab09de98d5ff503ec53ef5d8451a9e39dd4/doc/man/syslog-ng.8.xml#L177) and [L287](https://github.com/balabit/syslog-ng/blob/16b70ab09de98d5ff503ec53ef5d8451a9e39dd4/doc/man/syslog-ng.8.xml#L287).

Can you update them as well?

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
Thanks for the update. The changes look good to me. For some reason the travis fails, but that must not be related to your change. It is also fails on master: https://travis-ci.org/balabit/syslog-ng/builds/476232652. I look into it.

**Pull request merged**
