### PR TITLE
Fix unit test with function pointer dereference in case of ASLR, Criterion

### PR DESCRIPTION
**Pull request by Kokan**
The `test_diskq_statistics` could crash under certain conditions.
If the linux ASLR is enabled, and the compiler creates executable
that is position independent(`-fPIC`).

The function pointer could became invalid, in the unit test.
As the Criterion does *fork* and *exec* before executing tests.

Additionally the parameters are created in the *parent*,
and passed down to the *child* process, which - because of ASLR -
possible stores the referenced function in a different address.

This patch does not solves the above issue, but hides this behaviour
with additionally calling the function pointer passed by
via function pointer.

Because of this, a `@PLT` trampoline function is created, which
address is used, that can be made position independent hence
valid after *fork* plus *exec* if compiled with `-fno-pie`,
which is done in our case.

There is a nice post about related topics: https://www.macieira.org/blog/2012/01/sorry-state-of-dynamic-libraries-on-linux/

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by Kokan** [comment]
@furiel sorry I've kept it as WIP as I want to write a proper description for both github PR gui and git commit, as that commit solves an actual issue, which is not communicated (the fixing) and why.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
