### PR TITLE
Implement serialization of log messages

### PR DESCRIPTION
**Pull request by juhaszviktor**
This is the first patchset for using disk buffer.
Disk buffer will use this serializer

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
@juhaszviktor I tried `make check` but it fails with this:
```
  CCLD     tests/unit/test_logwriter
  CCLD     tests/unit/test_zone
  CCLD     tests/unit/test_persist_state
  CCLD     tests/unit/test_value_pairs
gcc: error: modules/builtin-serializer/tests/test_nvtable_serialize.o: No such file or directory
gcc: fatal error: no input files
compilation terminated.
make[3]: *** [modules/builtin-serializer/tests/test_nvtable_serialize] Error 4
make[3]: *** Waiting for unfinished jobs....
```
(Travis fails with a Python.h inclusion, probably rebasing to master later on will help because I recall we had a fix for that.) I'm moving onto reviewing individual commits and/or the file structure of the move and adjustments now.

**Comment by bkil-syslogng** [comment]
@juhaszviktor Please cherry pick my copyright declaration improvements from my doodling branch:
https://github.com/bkil-syslogng/syslog-ng/commit/22008daf1831973bee9658d9694d82efce5ea48d
https://github.com/bkil-syslogng/syslog-ng/commit/fee3949d8fed8c7995a95607f3b98e679b57f852

Depending on merge order, we will also need to add your module to the list of GPLv2+SSL files like so:
https://github.com/bkil-syslogng/syslog-ng/commit/358bcacabda9e5df5efe743b161ee376d67f4534

To ease reviewing, please wait until the end before you squash commits & force push. (Normal push is okay with me)

**Comment by bkil-syslogng** [comment]
Please update and try to cherry pick the copyright declarations again. I've threaded the two cherry picks to a new branch, I guess it should make it more sensible (and it should also work via gitk):
https://github.com/bkil-syslogng/syslog-ng/tree/logmsg_serialization-tamasnagy-bk0

**Comment by juhaszviktor** [comment]
Thx

**Comment by bkil-syslogng** [comment]
Travis highlights a compilation error.

**Comment by juhaszviktor** [comment]
Fixed

**Comment by juhaszviktor** [comment]
After consulting with @bazsi, I've updated the PR.

**Comment by ihrwein** [comment]
Adam and me finished the review.

**Comment by lbudai** [comment]
I think it requires much-much work to got my :+1: , but I think we need diskbuffer to be ported,
so I'd say, we can merge it...

Any other opinion?

**Comment by lbudai** [comment]
@bazsi: I'd handle diskbuffer as legacy code and wouldn't block the 'merge' with cleaning it up.

**Comment by ihrwein** [comment]
:+1: but I'm not proud of it.

**Comment by bazsi** [comment]
Just go ahead, I wouldnt want to block tgat either. We will continue with
cleanups as they are deemed important enough.

One thing I felt strongly about is the separation into a module. This or
does away with that right?

**Comment by lbudai** [comment]
Yeah, module separation was a good idea.

**Comment by juhaszviktor** [comment]
:+1: module separation is dropped, so We can merge it :)

**Pull request merged**
