### PR TITLE
Loggen packaging

### PR DESCRIPTION
**Pull request by norberttak**
This PR is to fix package generation related errors around loggen plugins.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@norberttak: change the header of the commits
```
module: subject

body
```

**Comment by norberttak** [comment]
I updated the commit messages accordingly

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by norberttak** [comment]
@kira-syslogng test this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
