### PR TITLE
C_ missing macros: AMPM, USEC, MSEC, HOUR12

### PR DESCRIPTION
**Pull request by Kokan**
The time stamp macros has like `S_` and `R_` had `AMPM`, `USEC`, `MSEC` and `HOUR12` options (example `R_AMPM`), but the `C_` macros are missing those values.
This patch adds those macros to the `C_` as well.

### CODE REVIEW

**Comment by mitzkia** [comment]
@kira-syslogng test this please;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by furiel** [comment]
@kira-syslogng test this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
