### PR TITLE
fix java version check ('test' has '=', not '==' as operator)

### PR DESCRIPTION
**Pull request by schweikert**
configure --enable-java doesn't work for me (syslog-ng 3.7.2):

    checking for JAVA_VERSION... ./configure: 16173: test: 1: unexpected operator

### CODE REVIEW

**Comment by lbudai** [comment]
Hi,

thank you for the patch.
We follow the following commit message format in our commits:
```
module: msg

<signed-off-by>
```

Could you update your commit message? Thanks!
( we have a guide, hided under this link: https://github.com/balabit/syslog-ng/blob/master/CONTRIBUTING.md :-)  )

**Comment by schweikert** [comment]
I have adapted the commit message.

**Comment by juhaszviktor** [comment]
:+1:  Big welcome for your contribution

**Comment by lbudai** [comment]
@schweikert : Thank you!

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
