### PR TITLE
Add SSL support for AMQP module

### PR DESCRIPTION
**Pull request by LarryWax**
This enable using SSL when using AMQP module.
Four config options were added:
- "**ssl_cacrt**" : path of the CA certificate in PEM format, setting this will enable SSL. Default value is an empty string. (SSL off)
-  "**ssl_key**" : path of private key in PEM format. This is effective only if "ssl_usercrt" is also set.
-  "**ssl_usercrt**" : path of user certificate in PEM format. This is effective only if "ssl_key" is also set.
-  "**ssl_verify**" : yes/no value, enable or disable peer verification. Default is enabled.
 
Signed-off-by: Giuseppe D'Anna <larrymadewax@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by presidento** [comment]
Thank you for the patch, we will check it soon.

**Comment by presidento** [comment]
@kira-syslogng: ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by LarryWax** [comment]
Any news on this?

**Comment by presidento** [comment]
@kira-syslogng retest this please.

**Comment by presidento** [comment]
@LarryWax For consistency it would be better to use the same keywords which are in [riemann](https://github.com/balabit/syslog-ng/blob/fcd9286b9001a6c305cc1a63afc4c7e3c120b54a/modules/riemann/riemann-parser.c#L45), [afsocket](https://github.com/balabit/syslog-ng/blob/fcd9286b9001a6c305cc1a63afc4c7e3c120b54a/modules/afsocket/afsocket-parser.c#L46) and [http](https://github.com/balabit/syslog-ng/pull/1437/files#diff-78e5252f55fd26196ad2388712a71d7cR41) modules. Otherwise it looks good to me.

**Comment by LarryWax** [comment]
@presidento I did not notice this detail, seems legit to me. 
Will fix this ASAP, thanks for your feedback :)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request closed without merging**
