### PR TITLE
F/rimemann timeout

### LINKED ISSUE #498: Riemann destination does not handle closing TCP connection very well
There is an issue in the underlying riemann_c_client that is used, that it does not check whether the TCP connection is alive or not: https://github.com/algernon/riemann-c-client/issues/9

This will result that if you have for example AWS ELB in front of riemann, which will issue TCP FIN after e.g. 60 seconds on no activity, the TCP connection dies, but syslog-ng does not realize it and keeps trying to send with old connection.

### PR DESCRIPTION
**Pull request by ihrwein**
Add timeout() parameter to Riemann destination.

Fixes #498

### CODE REVIEW

**Comment by algernon** [comment]
Would it be possible to bump the riemann-c-client requirement to 1.2.0+? EPEL has newer, so does Debian stable.

**Comment by algernon** [comment]
Also, it may be worth considering bumping that to 1.6.0, because that introduces TLS support, which would be another neat thing to have in the future. EPEL has 1.6.1, but Debian stable is at 1.2 - but I can easily make an official backport (on backports.debian.org) of the latest version.

**Comment by ihrwein** [comment]
@algernon That would be the best option, but Ubuntu 14.04 ships only `1.1.1`. Do you have a contact to the Ubuntu package maintainers?

**Comment by algernon** [comment]
Right, ubuntu. They should be pulling from Debian, so the next LTS will likely have something more recent. No idea if they have anything like backports.

**Comment by ihrwein** [comment]
@algernon , @lbudai I've updated my PR.

**Comment by algernon** [comment]
Looks good to me.

**Comment by lbudai** [comment]
Thanks! ( especially not forgetting to open #504 :-) )

**Pull request merged**
