### PR TITLE
Pytest: Renaming pytest_framework to python_functional

### PR DESCRIPTION
**Pull request by mitzkia**
- Realized that the initial reference naming of new python
functional tests was not lucky

Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by mitzkia** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by folti** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
In this PR I would not introduce any other changes. There was a plan to split testcases and lib into separate directories, but it is not trivial (even if it possible). I would skip it from this PR.

**Pull request merged**
