### PR TITLE
lib: build shouldn't fail on systems  where criterion is not available

### PR DESCRIPTION
**Pull request by lbudai**
Signed-off-by: Laszlo Budai <laszlo.budai@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by furiel** [comment]
Part of: #1878 
https://github.com/balabit/syslog-ng/pull/1878/commits/bf102f4a478cb4067508be212e0bdbc5b424d45c
If we do not want to merge #1878 now, feel free to merge this in, I will rebase later. :)

**Comment by furiel** [comment]
@lbudai could you check #1878, maybe this pr and that one has conflicting goals.
 The purpose of #1878 is to disable all kind of test targets if criterion is missing. One one hand it is great, because otherwise we silently left out unit tests. On the other hand, if the test targets are hard dependency of the package generation, #1878 can become a release blocker regression.

**Comment by lbudai** [comment]
@kira-syslogng retest this please;

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
