### PR TITLE
Add multi-instance support to systemd service file

### PR DESCRIPTION
**Pull request by jszigetvari**
contrib/systemd/syslog-ng@service: added templated service file
contrib/systemd/syslog-ng@default: added template parameter file
contrib/systemd/syslog-ng.service: removed old service file

    * introduced multi-instance support to systemd service file
    * WARNING: packaging/installer scripts will have to be updated
    * parameter files have to be installed to /etc/default or
      /etc/sysconfig
    * parameter file have to be named like: syslog-ng@instancename
    * service installation looks like: systemctl enable syslog-ng@default
    * service template has to be installed to /etc/systemd/system

Signed-off-by: Janos SZIGETVARI <jszigetvari@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by presidento** [comment]
What is the rationale behind it?

**Comment by jszigetvari** [comment]
@presidento there are several use cases that benefit from running multiple instances of syslog-ng. For these, this templated service file offers an elegant solution.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
