### PR TITLE
python: http-destination

### LINKED ISSUE #534: HTTP destination driver in Python
Implement a HTTP destination driver in Python

From OSE mail list:
```
Scheidler, Balázs <balazs.scheidler@balabit.com>
9:25 PM (10 hours ago)

to Syslog-ng 
Not right now but I'd love to see this function. And it can be implemented in Python or Java, so should be quite easy.

On Jun 25, 2015 8:19 PM, "westlake" <westlake2012@videotron.ca> wrote:
is it possible to send http-put traffic as a destination with syslog-ng?
```
thanks

### PR DESCRIPTION
**Pull request by gregory094**
HTTP destination implemented that can use `PUT` and
`POST` methods to send `LogMessage` data to
an HTTP server.

Currently only one HTTP destination can be run per syslog-ng
instance. The parameters can be given editing the 'http.py' file.
(After solving issue #535 these arguments can be loaded from the config file and more than one destination can be run per syslog-ng instance.)

fixes #534

Python destinations was moved to `python/modules` directory.

### CODE REVIEW

**Comment by bazsi** [comment]
If we consider this production grade we should move the modules under pylib and install it.

And then provide an scl wrapper to make it easy to use and that will let us change the implementation underneath to c/java/rust later to get more performance.

**Comment by gregory094** [comment]
+1 for the scl wrapper

**Comment by gregory094** [comment]
depends on #535

**Comment by gregory094** [comment]
This patch should be modified after merging #535 in order to use args from config.
What about an scl wrapper around it?

**Comment by lbudai** [comment]
@gregory094 : could you update this PR?

**Pull request closed without merging**
