### PR TITLE
riemann: Add support for TLS connections

### LINKED ISSUE #504: riemann: support TLS
After we bumped the required libriemann-client version to 1.6.0, we may implement TLS support in Riemann destination.

### PR DESCRIPTION
**Pull request by algernon**
Fixes #504.

### CODE REVIEW

**Comment by lbudai** [comment]
Thanks algernon!

**Comment by fekete-robert** [comment]
@algernon 
Hi, silly question: are the cert/cacert/key options standalone options, or do you have to set them within the type(tls) option?

Thanks!

**Comment by algernon** [comment]
The latter, you have to set them within the `type(tls)` option: `type(tls cacert("...") cert("...") key("..."))`

**Comment by fekete-robert** [comment]
Thanks a lot!
Could you check it if I got it right in the docs?

https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-destination-riemann.html#idp39208128

Also, I've seen that you added support for the timeout option in riemann,
but was not able to find its default value (I guess we try to resend the
message when it expires, right?)

Have a nice evening!

**Comment by algernon** [comment]
Regarding the timeout: the default is to not time out at all. The timeout affects blocking operations like `read()` and `write()`, and if we time out, that registers as any other error, and syslog-ng will follow the usual retry mechanism.

As for the docs, unfortunately, the syntax is wrong. It's not `type(tls(cacert(...)))`, but `type(tls cacert(...))`: that is, the TLS options are on the same level as `tls` itself, within `type()`. They're optional arguments for the `type()` option.

**Comment by bazsi** [comment]
Could we perhaps make this a bit more like the afsocket module?

Eg. tls(...)

Or is there something in Riemann I miss which explains the type thing?

**Comment by algernon** [comment]
IIRC, I had problems with `tls()`. Conflicts in the grammar or somesuch. I don't mind the syntax changing, but I don't have the time (or motivation, to be honest) to submit a patch.

**Comment by fekete-robert** [comment]
Thanks a lot for the review!

**Pull request merged**
