### PR TITLE
afsocket: use the log_dest_driver_queue_method for queueing

### PR DESCRIPTION
**Pull request by lbudai**
Otherwise processed stats counter won't be updated.

Fixes: #1409

Signed-off-by: Laszlo Budai <laszlo.budai@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by pzoleex** [comment]
@kira-syslogng retest this please test branch=pzolee-ose-stats;test=functions/other-functions/statistics/;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by lbudai** [comment]
@kira-syslogng retest this please test branch=pzolee-ose-stats;test=functions/other-functions/statistics/;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
