### PR TITLE
eventlog: avoid linking to old system libevtlog libraries

### PR DESCRIPTION
**Pull request by MrAnno**
`eventlog` is not an external library anymore.
Instead of adding an `-levtlog` ld flag, this patch adds the internal `libevtlog` explicitly as a dependency.

### CODE REVIEW

**Comment by mochrul** [comment]
I would like to mention, that I'm still waiting for a patch from Bazsi to relicense libevtlog. Then the whole so can be eliminated.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
I know, would get there eventually :)

-- 
Bazsi

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
