### PR TITLE
debian: Fixed wrong man files

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by bazsi** [comment]
why is it better to install the .xml files? does dh_installman support conversion from docbook to groff?

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by presidento** [comment]
@jpereira thank you for your contribution. We have talked about it IRL, and concluded that this would increase the build dependencies, so we would like to stay with the original file format.

**Pull request closed without merging**
