### PR TITLE
Master Travis breakage due to a warning in test_basicfuncs

### PR DESCRIPTION
**Pull request by bkil-syslogng**

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
The breakage occurred due to an interference of these two (i.e., missing rebasing between the two steps):
https://github.com/balabit/syslog-ng/pull/1041
https://github.com/balabit/syslog-ng/pull/976

We could write tests to catch these in the future via a new Travis matrix element.

**Comment by bkil-syslogng** [comment]
Travis passed. Please merge.

**Comment by bazsi** [comment]
I have commited an identical patch to master directly, when I saw that master was turning red. Travis is still chewing that patch, but I hope it makes it green.

**Comment by bazsi** [comment]
I am closing this once travis is green.

**Comment by bazsi** [comment]
Closing as travis became green.

**Pull request closed without merging**
