### PR TITLE
Use msg_trace() when emitting trace information

### PR DESCRIPTION
**Pull request by MrAnno**
I think our debug log is flooded, so I've opened this PR to
- make it possible to enable trace messages with the `--trace` or `-t` command line flag, even if syslog-ng was not compiled in debug mode
- move frequent, per-message internal messages to the trace log level.

This won't have any performance implications, because we already have 166 debug messages compared to 10 existing trace messages.

My intention is to make our debug logs manageable in case there are more than 10-20 messages passing through syslog-ng. This way we can ask for debug logs from production environments without generating ~15-50 lines of debug information for each incoming message (15 using a trivial configuration, 50 with a non-trivial one).

But of course, when trace is required, it can be enabled without recompiling syslog-ng:
```sh
sbin/syslog-ng -Fdevt
# or
sbin/syslog-ng-ctl --set=1 trace
```

My guidelines I followed:
1. Leave all nonfrequent events on debug level, they are extremely useful.
2. Leave a few frequent (per-message) debug messages that are absolutely necessary for debugging.
   For example: source suspend/wakeup events, incoming/outgoing log entries, destination queue full events, the result of filters/parsers, throttling information, etc.
3. Move all other per-message "trace information" to the trace level.
   For example: starting/ending filters/parsers/rewrites/etc, setting an NV-pair in a message, ... 

Questions:
- **What do you think of the guidelines above?**
- **Please have a look at the output of `git grep msg_debug` and `git grep msg_trace` executed on my branch. Do you agree with those changes?**

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by szemere** [comment]
Forwarding the words of @mitzkia : I would move the following messages from debug to trace too:

`lib/parser/parser-expr.c:  msg_debug(">>>>>> parser rule evaluation begin",`
`lib/filter/filter-pipe.c:  msg_debug(">>>>>> filter rule evaluation begin",`
(Of course with the closing parts.)

**Comment by MrAnno** [comment]
The result of rewrites/filters has been on debug lever for a very long time. Are you sure?

**Comment by mitzkia** [comment]
I would say to put that messages also on trace because:
 - symmetry (same type of messages: ">>>>", "<<<<" can be appear on same level)
 - the debug log will be cleaner :)

**Comment by MrAnno** [comment]
Okay, will do :)

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
