### PR TITLE
F/introduce template options in rewrite rules

### LINKED ISSUE #652: rewrite rules don't honor time-zone
It seems to me this is a bug.
Ideally, one should be able to set `time-zone()` in a rewrite-rule.

#### config
```
@version:3.7
@include "scl.conf"

options {
  threaded(yes);
  time_zone("UTC");
};

source s_stdin { file('/dev/stdin'); };
rewrite r_utcdate { set("${ISODATE}", value('UTCDATE')); };
destination d_stdout { file('/dev/stdout' template ("ISODATE=${ISODATE} UTCDATE=${UTCDATE}\n")); };

log {
  source(s_stdin);
  rewrite(r_utcdate);
  destination(d_stdout);
};
```
#### Output
```
[2015-08-24T09:51:42.651988] syslog-ng starting up; version='3.7.1'
test
[2015-08-24T09:51:44.894269] Incoming log entry; line='test'
[2015-08-24T09:51:44.894394] Rewrite expression evaluation result; value='UTCDATE', new_value='2015-08-24T09:51:44+02:00', rule='r_utcdate', location='/etc/syslog-ng/syslog-ng-rewrite-timezone.conf:10:21'
[2015-08-24T09:51:44.894491] Initializing destination file writer; template='/dev/stdout', filename='/dev/stdout'
[2015-08-24T09:51:44.894800] Outgoing message; message='ISODATE=2015-08-24T07:51:44+00:00 UTCDATE=2015-08-24T09:51:44+02:00\x0a'
ISODATE=2015-08-24T07:51:44+00:00 UTCDATE=2015-08-24T09:51:44+02:00
```

### PR DESCRIPTION
**Pull request by ihrwein**
rewrite-set: enable template options

Fixes #652

### CODE REVIEW

**Comment by ihrwein** [comment]
@lbudai @bazsi We would be happy if you can look at this. The last commit should work like the previous one but it doesn't.  We need that change to support template options not only after the first templatable parameter. The grammar accepts configurations with it but the timezone isn't honored.

Sample configuration:
```
@version:3.7
@include "scl.conf"

options {
  threaded(yes);
  time_zone("UTC");
};

source s_stdin { file('/dev/stdin'); };
rewrite r_utcdate { set("$ISODATE" value('UTCDATE')  time-zone("+02:00") ); };
destination d_stdout { file('/dev/stdout' template ("ISODATE=${ISODATE} UTCDATE=${UTCDATE}\n")); };

log {
  source(s_stdin);
  rewrite(r_utcdate);
  destination(d_stdout);
};
```

If we stay at the second commit's state this config snippet works:
```
rewrite r_utcdate { set("$ISODATE" time-zone("+02:00") value('UTCDATE')  ); }
```

**Comment by bazsi** [comment]
The refined version does look better, and I don't know why it doesn't work.

I was under the impression that lasttemplateoptions is not properly initialized but the refined version looks good and the second one is more suspicious. I would use a debugger because nothing else pops out.

**Comment by ihrwein** [comment]
I found two problems here: we use LTZ_LOCAL in log template format (time-zone() sets LTZ_SEND) and we didn't call `log_template_init()`. I want to finish this tomorrow.

**Comment by ihrwein** [comment]
The PR is ready for review.

**Comment by ihrwein** [comment]
There seems to be some problem with Travis: it didn't check the last commit.

**Comment by ihrwein** [comment]
I'll close this to fix travis.

**Pull request closed without merging**
