### PR TITLE
plugin: decrease the log level of module loading errors

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@pzoleex : could you share the details on why did you request this change?

**Comment by pzoleex** [comment]
@lbudai Because it gives a confusing error message about not existing libjvm.so, when syslog-ng service is started however no java in the configuration.

It's not lucky thing to give a big error message after a brand new installation with a default configuration about something that is not used at all :)

Starting syslog-ng: Error opening plugin module; module='mod-java', error='libjvm.so: cannot open shared object file: No such file or directory'

**Comment by lbudai** [comment]
@pzoleex : thanks!

**Pull request merged**
