### PR TITLE
Update deprecated use of tcp()/udp() to network(). This addresses #2322

### PR DESCRIPTION
**Pull request by mauricetmeyer**

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng test this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mauricetmeyer** [comment]
@szemere Sure, didn't notice that for some reason. Thanks for pointing that out, probably have to check my editor config.

**Comment by MrAnno** [comment]
@mauricetmeyer Thank you!

**Pull request merged**
