### PR TITLE
[wip]remove native module

### LINKED ISSUE #1307: ./lib/logthrdestdrv.h:33:16: fatal error: iv.h: No such file or directory
# syslog-ng

## Version of syslog-ng

```
syslog-ng-3.8.1
```

## Platform

Redhat Linux Enterprise Server 6.8

# Issue

## Failure

I am receiving below error message

```
  YACC     modules/add-contextual-data/add-contextual-data-grammar.c
make --no-print-directory all-recursive
  CC       modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o
In file included from lib/cfg-grammar.y:41:0,
                 from modules/native/native-grammar.y:39:
./lib/logthrdestdrv.h:33:16: fatal error: iv.h: No such file or directory
compilation terminated.
make[2]: *** [modules/native/modules_native_libsyslog_ng_native_connector_a-native-grammar.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

```
$ gdb syslog-ng
 run
```

## Steps to reproduce

1. ./configure --prefix=/path && make

2. ...

## Configuration

Compiling syslon-ng-3.8.1 from source

## Input and output logs (if possible)

N/A

### PR DESCRIPTION
**Pull request by Kokan**
As far as I see this is a deadlift, if anybody uses it please says so.

Fixes #1307
(haven't tested, but *really* *really* hope it is)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
This is a "proxy" module for native language bindings. It only contains abstractions for parsers and is/was used by syslog-ng-rust-modules (https://github.com/balabit/syslog-ng-rust-modules).

**Comment by czanik** [comment]
I have some mixed feelings here. Once upon a time I did some testing, and doing the same parsing in Rust as in Python was almost 10x faster and it scaled almost linearly with CPU cores while Python was actually slowing. Rust also seems to gain a momentum, see Firefox or Suricata IDS. On the other hand I'm not aware of any active users. Probably we were too early adapters. And I can't help maintaining the code...

**Comment by Kokan** [comment]
But syslog-ng-rust-modules has not been updated since Jun 14, 2017; while it does not even compile for me (neither does it compiled with a 10 minutes effort to hack anything to push it compile).

For me that project seems dead, and no reason to keep this.

**Comment by lbudai** [comment]
:-1:

**Comment by lbudai** [comment]
I don't want to merge this right now, of course we can discuss it later, but do not remove now.

**Comment by Kokan** [comment]
We discussed that it would make sense to use it in the long term.

**Pull request closed without merging**
