### PR TITLE
modules/json: Adaptions for json-c v0.13

### PR DESCRIPTION
**Pull request by besser82**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by besser82** [comment]
@Kokan `json-c` has removed `json_parser_private.h` from regular installation in v0.13.  The file might get included for backwards compatibility for some ancient versions, so I conditionalized inclusion for versions <= 0.12.

**Comment by MrAnno** [comment]
@besser82 Thank you.

**Comment by besser82** [comment]
@MrAnno You're welcome  =)

**Pull request merged**
