### PR TITLE
java: export GRADLE_OPTS environment variable

### LINKED ISSUE #640: environment variables not passed on to gradle in 3.7.1
syslog-ng 3.7.1 java modules can't be built when behind a proxy firewall: http proxy environment variables are not passed on to gradle, so it can't download modules.

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #640

Signed-off-by: Tibor Benke <tibor.benke@balabit.com>
Reported-by: Peter Czanik <peter.czanik@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
One of these should be enough. All Makefile.am files are included into a single big Makefile.

**Comment by ihrwein** [comment]
But they are in separate modules (even if the second one depends on the first one). I know `modules/java` is enough, but the second one also shows the intention.

**Comment by bazsi** [comment]
Add it with a comment then. I think having redundant copies is just as bad.

**Comment by ihrwein** [comment]
https://github.com/travis-ci/travis-ci/issues/5301

**Comment by ihrwein** [comment]
I replaced the second export with a comment:
```
# GRADLE_OPTS is also needed here but it is exported by the Makefile in modules/java
```

**Comment by lbudai** [comment]
could you rebase it?

**Comment by ihrwein** [comment]
rebased

**Comment by lbudai** [comment]
Thanks. When travis becomes green, I'll merge it

**Pull request merged**
