### PR TITLE
Stdin driver with file opener refactors

### PR DESCRIPTION
**Pull request by bazsi**
This branch implements the stdin() driver together with a pretty large refactoring step to make this as
simple as possible. This replaces the original #1487 PR, which I've closed a few minutes ago.

The opening of a file, construction of LogTransport and LogProtoServer/Client instances has
been delegated to a new FileOpener interface, making the rest of the code basically independenent of
how a specific file was opened.

This eliminates a large number of conditionals, scattered around the affile code and creates "use-case" specific modules for each specialization of the file driver (named pipes, regular files, /proc/kmsg, /dev/kmsg, and the new one stdin).

The stdin driver does not depend on /dev/stdin as a valid filename anymore, it simply reuses fd 0. The stdin driver also causes syslog-ng to exit once it hits EOF.

There are still rough edges here and there, but I think I could go on with this branch forever :) I believe it is now in a good form so that it is ready for integration.

The patches were split to small baby-steps (albeit a few patches are still huge) to make review easier.

Finally, this is what I've used to test the new stdin() driver:

```
@version: 3.10

log { 
	source { stdin(); };
	destination { file("/dev/stdout"); };
};
```

The stdin() driver supports all parameters that file sources do, e.g. multi-line support, flags(no-parse) all work.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by faxm0dem** [comment]
I'm a bit surprised by this supersession, although I haven't looked at the details.
Does this mean all the CLI functionality is dropped?

**Pull request merged**
