### PR TITLE
dbld: fix pip package versions on older Distro releases

### PR DESCRIPTION
**Pull request by bazsi**
Some packages (e.g.  pylint 2.0.0) declare package tags that are not
supported by ancient setuptools packages, that are available in centos 6 and
7, therefore use fixed versions on ancient distributions.

Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
this should fix #2187

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
Hmm... Ubuntu 17.10 itself an older distro (https://wiki.ubuntu.com/Releases).

I think we should have a dev-image (which could be latest Ubuntu LTS, or just the latest Ubuntu, or even Debian testing). And only in that image should we use the non-versioned requirements.
Every other image should be a kind of 'support' image and on those images we should go with the versioned requirements.

**Comment by bazsi** [comment]
@lbudai I was trying to use unversioned for the latest of all distros (well except CentOS 7).

This is what I've concluded with:
* artful seems to work fine so far, but I can easily foresee that this should use the versioned stuff eventually (maybe a bit newer than what is currently in the requirements.txt file)
* jessie didn't work, so I added version numbers. 
* I've added stretch without versions as a separate PR.

I am using bionic locally, but java does not compile in that, so I am not ready to submit that as a PR.

So as a policy, I would agree, older releases should be using explicit versions, latest should be unversioned so we uncover incompability issues.

**Comment by szemere** [comment]
Since last time we made the `/requirements.txt` to be a symlink on `/dbld/images/required-pip/all.txt` (which is now empty), travis now fails on pylint.
I built the image locally, but somehow I got error messages on the mongodb module during the build of syslog-ng.

(note: The patch perfectly follows the logic behind the dbld structure! Thank You for that!)

**Comment by MrAnno** [comment]
Sorry, my fault. I'm pushing a commit to fix the macOS build.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by czanik** [comment]
/me tested centos7 and xenial and those built without a problem

**Comment by czanik** [comment]
@szemere: I can confirm, that stretch builds. I don't have any .deb based systems to test the results.

**Comment by szemere** [comment]
Discussed IRL with @czanik and @algernon , thanks for the help!

The problem only occurs when we try to build syslog-ng from bare source on Debian stretch.
Using the tarball method works fine. (Because however we include the embedded mongo-c driver into the tarball, we actually do not use it.)
Fortunately the mongoc driver is very good ad backward compatibility, so according to my experience syslog-ng works fine with the system provided version. @algernon already opened an issue #2200 about dropping the built in version. If we decide to accept the proposal naturally it will also affects dbld.

I will remove the requested changes, as a workaround we can add `--with-mongoc=system` to configure during building from the source. (But this issue has to be addressed in an another PR.)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by gaborznagy** [comment]
Can we clear the git tree of the two branches of the 2 PRs #2189 and #2188, please?

It's hard to review, we merge something that we don't want, the other branch got changed, etc.
@bazsi: I think in the past you opened the PR on the other PR's branch, this way it was clear what's actually in the PR.

**Pull request merged**
