### PR TITLE
kv-scanner: move to lib

### PR DESCRIPTION
**Pull request by gaborznagy**
For general availability kv-scanner moved from modules to lib/scanner
next to other scanners.

This pull request is a preparation for a future parser that will use kv-scanner.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
Pls take care about the license change in this case.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
