### PR TITLE
debian: add Debian packaging

### PR DESCRIPTION
**Pull request by lbudai**
Merge http://http.debian.net/debian/pool/main/s/syslog-ng/syslog-ng_3.10.1-3.debian.tar.xz and
https://build.opensuse.org/source/home:laszlo_budai:syslog-ng/syslog-ng-3.11/syslog-ng_3.11.1-3.debian.tar.xz?rev=1eebdb15510796231cca78d7a80773e7.

Changes to the Debian Sid packaging:
 * enable java support
 * prepare Makefile.am
 * Minimum debhelper version is set to 9 (to support Ubuntu Xenial)
 * some kfreebsd related code removed
 * criterion-dev added to Build-Deps (not part of Debian)
 * circular dependency between syslog-ng-core and syslog-ng-mod-journal
   resolved by moving mod-journal to core

New packages from my OBS repo:
 * mod-geoip2
 * mod-http
 * mod-pacctformat
 * Java packages:
   * mod-java, mod-java-common-lib
   * mod-java-http
   * mod-hdfs
   * mod-kafka
   * mod-elastic

### CODE REVIEW

**Comment by lbudai** [comment]
@bazsi: I think we can store these files in master, but we won't include it in the release tarball.
@mochrul : could you take a look at the PR? thanks.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
This is in my queue, I just need some more time to catch up with my TODO list.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
Hi,

I checked the patch. It seems good.

Some minor changes have happened with the Debian packaging since this but nothing serious/important. Except maybe adding the libevtlog.so to the dev package.

**Comment by bazsi** [comment]
It should rather be merged to libsyslog-ng.

**Comment by mochrul** [comment]
For that, I'm still waiting for your patch @bazsi to change the license.

**Comment by bazsi** [comment]
Got it. :)

**Pull request merged**
