### PR TITLE
openssl: replace deprecated thread callback function

### PR DESCRIPTION
**Pull request by pprindeville**
CRYPTO_set_id_callback (openssl<1.0.0) has been replaced by
CRYPTO_THREADID_set_callback.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by pprindeville** [comment]
Fixes option #1396.

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by bazsi** [comment]
I have sent you a pull request to improve the conditionals somewhat, if you can add it on top of yours,  you get my :+1:

@kira-syslogng please test

**Comment by pprindeville** [comment]
What about applying the point fix, then doing a broader refactoring of OpenSSL version specific code paths?

**Comment by bazsi** [comment]
Well, I've submitted a separate patch, so yours will remain the low-touch-point one. No need to fold it in. Just merge it in your branch so I can merge both with a single PR.

Or is there any other problems I might be missing?

**Comment by pprindeville** [comment]
> Just merge it in your branch so I can merge both with a single PR.

Done.

**Comment by presidento** [comment]
@kira-syslogng ok to test.

**Comment by kira-syslogng** [comment]
Build ERROR

**Comment by presidento** [comment]
@kira-syslogng retest this please.

**Comment by kira-syslogng** [comment]
Build ERROR

**Comment by pprindeville** [comment]
I can't see the kira results... the link [Details](http://jenkins.syslog-ng.balabit:8080/job/OSE-PR-JENKINS-TEST/48/) doesn't resolve.

**Comment by pprindeville** [comment]
@kira-syslogng retest this please.

**Comment by pprindeville** [comment]
@bazsi I've rebased without your PR merged, so you can commit it separately per above. Thanks.

**Comment by kira-syslogng** [comment]
Build ERROR

**Comment by pprindeville** [comment]
I'm seeing this message "Kira - 305 tests run, 0 skipped, 2 failed." but I can't figure out how to get a look at what those tests were.

Can someone please explain what I'm doing wrong?

Thanks

**Comment by kira-syslogng** [comment]
Build ERROR

**Comment by bazsi** [comment]
Hi,

Ill take care about that. That's an experimental system, which Balabit
would publish, but right now it runs internally on balabit infrastructure.

**Comment by pprindeville** [comment]
> That's an experimental system, which Balabit would publish, but right now it runs internally on balabit infrastructure.

So, is anything actually failing to build or not?

**Comment by bazsi** [comment]
There's a failing testcase, seems to be unrelated to this PR.

**Comment by MrAnno** [comment]
Hi,

The failing test case is not related to this patch, we're going to fix the problem ASAP.

**Comment by MrAnno** [comment]
@kira-syslogng retest this please.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by pprindeville** [comment]
@bazsi Can you please close your review?  Are we good to merge now?

**Comment by lbudai** [comment]
@pprindeville : thanks for the PR. 
It is ready to merge, so here is my :-1: 
@bazsi: could you approve the changes you've requested? (and merge the PR)

**Comment by pprindeville** [comment]
Thanks!

**Comment by pprindeville** [comment]
BTW, what's the next version of syslog-ng and when is it due out? Thanks

**Pull request merged**
