### PR TITLE
F/ctx template funcs2 - mean operator, further stylistic improvements to #1037

### PR DESCRIPTION
**Pull request by bkil-syslogng**
Further improvements to #1037:
* Rename a few static functions
* Abstract out iteration when finding first element and aggregating
* Implement numeric mean (average)
* Refactor test cases to reduce redundancy

### CODE REVIEW

**Comment by bazsi** [comment]
I would use average instead of mean. I know it's the same but average is
used more often as an aggregator.

**Comment by bkil-syslogng** [comment]
@bazsi I've added aliases for `avg` and `average`. Do you like it this way?

**Comment by bazsi** [comment]
Usually I prefer to have fewer names instead of more, as it makes understanding configs more difficult.

I for one had check if mean is matchematically equivalent to average. It is, but I didn't know for sure. I think the same lack of confidence could apply to others.

That's why I think it is not the best name for it. I can live with mean, but please don't use multiple aliases for the same thing. 

Do you perhaps have a reference in which programming language is this called mean in contrast with average?

**Comment by faxm0dem** [comment]
average has fewer homonyms *i.e.* easier to google

**Comment by bkil-syslogng** [comment]
As a data scientist, I don't use the word `average` often, but it's not me who decides. If you say that the community will understand it better that way, I'd gladly rename it. It's our goal to please our users.

As a side note, we generally use mean and standard deviation at the same time.

Some examples:
* http://sites.fas.harvard.edu/~stat335/overheads/Matlab_IntroII.pdf
* http://www.r-tutor.com/elementary-statistics/numerical-measures/mean
* http://stackoverflow.com/a/20820148
* ...

**Comment by bkil-syslogng** [comment]
By the way, we need to decide whether this should stay as an integer one, change to a floating point version, implement both of them or select between them using a precision argument. That's one of the questions which kept @MrAnno from implementing this in the original, urgent scope.

**Comment by lbudai** [comment]
If we are talking about statistics then `mean` is still not very precise: what you implemented is `arithmetic-mean`. 

So I'd use the `average` ;-)

**Comment by lbudai** [comment]
@bkil-syslogng : at this PR just go with integers, IMHO.

**Comment by bkil-syslogng** [comment]
Renamed `mean` to `average` and removed all aliases.

Backup saved under:
* https://github.com/balabit/syslog-ng/compare/master...bkil-syslogng:t/ctx-template-funcs2-bk0?expand=1

Rebased to `master`.

**Comment by bazsi** [comment]
Thanks for working on this, it looks much better and the $(average) function is really welcome.
Merging this as well.

**Pull request merged**
