### PR TITLE
F/csvparser refinements

### PR DESCRIPTION
**Pull request by bazsi**
This is the first chunk of my work to clean up the code for csv-parser. I only wanted to add a single and simple option, but the code doesn't really help, rather it became rather convoluted.

So instead of adding the new option, I started refactoring what we have there.

There is at least one important bugfix here, one that fixes the clone() method. That should probably be backported to earlier versions as well.

I also have yet another batch of patches, but that still needs some cleanup, so I submit this, hopefully reviewing this in smaller steps is easier.

Cheers,
Bazsi

### CODE REVIEW

**Comment by bazsi** [comment]
I think the latest update of this branch addresses all review comments.

**Comment by u2yg** [comment]
@lbudai Did you review the new force push before merging? He has many code changes since the last reviews.

**Comment by lbudai** [comment]
yep (Bazsi mentioned in his last comment that he made modifications)

( sorry for not waiting to react your own review notes but my plan was to starting releasing the 3.7.2 on today morning, and this PR fixes a possible double-free issue and I wanted to include in 3.7.2 )

**Comment by bazsi** [comment]
Sorry for the force push. I didn't know that github removes the comments in this case (or I knew I just forgot ;).

Next time, I am going to commit followup patches until they are reviewed as well, and then merge back to the base.

I only changed the string-list related stuff for two reasons:

1) addressing review comments
2) I noticed that the string_list may contain non-pointer elements and added handling those to string_list_clone()

I also added some (but still pretty limited) coverage for these functions.

**Comment by u2yg** [comment]
That strategy sounds nice, thank you. Actually, I had asked Laci in person
sometimes later and he told me that he did review the complete diff. The
situation was only unclear to me from the online conversation, but all is
well now.

**Pull request merged**
