### PR TITLE
debian: Adding missed /sbin/syslog-ng-ctl

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
Thank you for your recent contribution. We welcome all third party improvements. For the sake of conventions, may I ask that you please provide a short commit message? It would also be nice if you could squash the pull requests and/or the commits to a single, Debian related one.

**Comment by jpereira** [comment]
@bkil-syslogng like this?

**Comment by lbudai** [comment]
@jpereira : are you using this debian directory for generating deb packages for syslog-ng?
My plan is to make debian packaging scripts located in my [OBS](https://build.opensuse.org/package/show/home:laszlo_budai:syslog-ng/syslog-ng-3.8alpha) project part of syslog-ng.

**Comment by jpereira** [comment]
hi @lbudai! yes, I do!

**Comment by lbudai** [comment]
@jpereira : I've created my PR #1125 for replacing the existing Debian directory.
I'll check your modifications and will use those parts that are still relevant.

This is a huge change that I always wanted to do. Could you check if you can live with the new packaging?

**Comment by lbudai** [comment]
#1125 solve this issue (`syslog-ng.install` takes `usr/sbin/*`)

**Pull request closed without merging**
