### PR TITLE
syslog-format: fix BSD timestamp parsing

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes the broken master (it's December...)

Signed-off-by: Tibor Benke <tibor.benke@balabit.com>
Signed-off-by: MÓZES Ádám István <adam.mozes@balabit.com>

### CODE REVIEW

**Comment by dnsjts** [comment]
This pull request fixes a quite twisted (and incorrect) logic of the BSD year inference.
Next time I shouldn't use the parsed timestamp as the current time for `determine_year_for_month`.

**Comment by ihrwein** [comment]
@lbudai @bazsi This bug breaks the master branch and so every other PRs. Please review it so the other PRs can be rebased.

**Comment by bazsi** [comment]
This looked suspicious even when I copy pasted it to date parser, which has the same logic.

I don't have my computer handy so I really can't review the change in detail, however this was converted to this logic by Adam, and was a very different logic which endured a number of Decembers.

So I would go back to the original solution, time is difficult to get right.

**Comment by ihrwein** [comment]
This was the original code (embedded in syslog-format):
```C
          /* detect if the message is coming from last year. If its
           * month is at least one larger than the current month. This
           * handles both clocks that are in the future, or in the
           * past:
           *   in January we receive a message from December (past) => last year
           *   in January we receive a message from February (future) => same year
           *   in December we receive a message from January (future) => next year
           */
          if (tm.tm_mon > nowtm.tm_mon + 1)
            tm.tm_year--;
          if (tm.tm_mon < nowtm.tm_mon - 1)
            tm.tm_year++;
```

And this is the refactored, currently used code:
```C
/* Determine (guess) the year for the month.
 *
 * It can be used for BSD logs, where year is missing.
 */
gint
determine_year_for_month(gint month, const struct tm *now)
{
  if (month == 11 && now->tm_mon == 0)
    return now->tm_year - 1;
  else if (month == 0 && now->tm_mon == 11)
    return now->tm_year + 1;
  else
    return now->tm_year;
}
```
The bug is in the call site, not in this function. If I remember correctly, there was a bug in the original code as well, but the comments were correct.

I'd keep the new changes, because `syslog-format` was refactored, but write some unit tests for this `determine_year_for_month()` function. What do you think?

**Comment by bazsi** [comment]
There was a change prior to this extraction.

**Comment by dnsjts** [comment]
The wrong behaviour was introduced it in 27259e93d090031c62a3f13ac2d3e2eb5ea694f2.
Here is the wrong sequence of the calls:

1. `cached_localtime(&now_tv_sec, tm);`
2. `scan_bsd_timestamp((const gchar **) &src, &left, tm)`
3. `tm->tm_year = determine_year_for_month(tm->tm_mon, tm);`

The second parameter of the `determine_year_for_month` is the current time. This is no longer true in this sequence.

**Comment by lbudai** [comment]
Hi,

@dnsjts is right, the bug is from a PE refact.
Adam didn't touch the logic, just make it more understandable.

I'd merge this fix as-is, but the main question for me: do we really need this heuristic? :-)

**Pull request merged**
