### PR TITLE
stats-query: lock index before editing it

### PR DESCRIPTION
**Pull request by kvch**
In case of paralell querying through stats_query a race could be possible when editing the index records. But not anymore! :)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
I think we could follow the same pattern as in case of stats lock...
but I can accept this PR now.

**Pull request merged**
