### PR TITLE
pep8_dependency: Switch to package pycodestyle as a dependency from pep8

### PR DESCRIPTION
**Pull request by mitzkia**
* pep8 as package is discontinued, last release version is: 1.7.1
 * references:
   * https://github.com/PyCQA/pycodestyle/issues/466
   * https://github.com/PyCQA/pycodestyle/issues/481
   * https://github.com/PyCQA/pycodestyle/releases/tag/1.7.1

Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
Isn't this change a little bit too early? At least if we want to support older Rh and SUSE releases.

Also from Debian perspective, the still supported jessie does not contain it. And from Ubuntu side, only artful contains the python-pycodestyle package.

**Comment by mitzkia** [comment]
Could we set depends in a control file on a pip package?

**Comment by bazsi** [comment]
I have a related change queued up, which accepts either pep8 or pycodestyle

**Comment by bazsi** [comment]
This is the change I have queued up, now in pr #1913 

https://github.com/balabit/syslog-ng/pull/1913/commits/29c513b6bf9449a17ad2ff2bc6b25e27fa10084e#diff-7e4bb15b173a291ced53c948d7aaa231

I think this can be abandoned in favour of that one.

**Comment by mochrul** [comment]
Unfortunately you can't depend on a pip package when you want to build a Debian/RedHat package. Also, usually the packages are built in a sandbox (with no internet connection), so preinstalling the pip package is a no-go either.

**Comment by mitzkia** [comment]
@bazsi  and @mochrul  Thanks for the notes and answers.
Regarding PR #1913 I am closing this PR

**Pull request closed without merging**
