### PR TITLE
afstomp: fix destination port

### PR DESCRIPTION
**Pull request by bazsi**
Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
This fixes a stomp related issue, reported on the mailing list just now. I've asked the reporter to report back success.

Seems that stomp doesn't work at all in 3.6 as it always tries to connect to the port 0.

Could you pls merge this for both 3.6 and master? Thanks

**Comment by bazsi** [comment]
Any news on this? @talien do you have any comments or it can go in as it is?
thanks

**Comment by talien** [comment]
It's fine, you can merge it.

**Comment by lbudai** [comment]
It's merged for 3.6/master, too.

**Pull request merged**
