### PR TITLE
test_cfg_lexer_subst: rewrite test cases in criterion

### LINKED ISSUE #2598: convert test_cfg_lexer_subst to criterion
Use Criterion to rewrite this unit test.

I am creating this issue as it is mentioned in #2581 by @Kokan.

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #2598

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
Hi,

It's a Travis issue on macOS, a restart should help.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@mehul-m-prajapati Please rebase to master, it'll make Travis green.

**Pull request merged**
