### PR TITLE
F/split misc

### PR DESCRIPTION
**Pull request by bazsi**
While trying to extract the optimized strchr()  I realized that I don't want to add yet another function to misc.

So I split misc first, I think it was well worth it. Now there's a nice & clean place where I can add string related helpers.

### CODE REVIEW

**Comment by bazsi** [comment]
Also, please note that my value-pairs performance stuff is waiting for this to be merged.

**Comment by MrAnno** [comment]
:+1:

**Comment by bazsi** [comment]
Can I merge this with the :+1: from @MrAnno ? It is really a non-functional change.

**Comment by bkil-syslogng** [comment]
If MrAnno has concluded static analysis and unit tests still pass, it's :+1: from me. Bonus points for your macro comment.

**Comment by bkil-syslogng** [comment]
@MrAnno said he'll run through some quick tests on it again in the
afternoon. It can be merged afterwards if all goes well.

**Comment by MrAnno** [comment]
I double checked it, it seems to be OK.
All unit tests passed successfully, there were no new compiler warnings.

**Comment by bkil-syslogng** [comment]
:+1:

**Pull request merged**
