### PR TITLE
F/literal

### LINKED ISSUE #206: Writing a null character at the end of TCP payload
I need to send a null character at the end of a message on a tcp output...
But this null is considered to be an end of string.

My use case is sending a GELF message to a graylog's tcp input.
GELF message is a json syntax quite simple to comply with thanks to format-json.
Graylog needs a null character at the end of a GELF message in TCP but not in UDP.

I tried many combination in the template with \x0, echo \x0, `global_definition_of_null`, etc...
The matter is that null character when interpreted is an end of string, and is not written in the tcp message.
I see truncated messages with ngrep.

[Gelf Specification is not clear about it, but  I have tested it](http://serverfault.com/questions/591758/send-echo-message-to-graylog2-via-gelf-tcp-12201-port)
After finding [a clue in Graylog's issues](https://github.com/Graylog2/graylog2-server/issues/127#issuecomment-17563306)

In syslog-ng's mailling list, we have seen three options with Balazs Scheidler and Gergely Nagy :
1.  the creation of $(format-gelf) which would solve both the NUL issue and makes it easier for someone else to create GELF output
2.  add an option to $(format-json) to add a suffix (and perhaps a prefix) in front of and after the resulting string
3. $(char 0) as a template function? That can be reused outside
of format-json 

A format-gelf as in 1 is missing, but my case and other may be satisfied with a template function that writes raw characters as in solution 3

### PR DESCRIPTION
**Pull request by juhaszviktor**
Fixes #206

### CODE REVIEW

**Comment by algernon** [comment]
\o/

**Comment by bazsi** [comment]
I think we should get rid off the strsplit on space and just use separate arguments.

Also I can't remember the reason literal strings do not work, can you reiterate that?

3rd parse number used base 10 so far, did you check whether this change breaks other call sites?

**Comment by juhaszviktor** [comment]
The literal strings work, except the \0, because it was handled as a string terminate by the parser.

I checked the base 0 with unit tests, I think the only possible problem can be if someone used decimal number starting with 0, because it will be handled as an octal number.

@bazsi do you think something like this: $(literal --separator=': ' "0x00:0x32") ?

**Comment by bazsi** [comment]
No. Syslog-ng will split arguments by space. If this doesnt solve the 0
char issue then I dont really see the usefulness over including \xaa
sequences in template strings?

**Comment by juhaszviktor** [comment]
Sorry, it was a misunderstanding. It solves the 0 char issue.
I just answered your "I can't remember the reason literal strings do not
work, can you reiterate that"  question.

**Comment by bazsi** [comment]
I don't think the --separator argument would be needed. I just figured that
instead of vaidating that you have exactly 1 argument, just go ahead and
process them all, instead of splitting by space within the template
function.

e.g. $(literal 0 0xff 0377) instead of $(literal "0 0xff 0377")


-- 
Bazsi

**Comment by juhaszviktor** [comment]
Ok, understood. I will do it

On Fri, Jun 26, 2015 at 10:59 AM, Balazs Scheidler <notifications@github.com

**Comment by lbudai** [comment]
@juhaszviktor : will you? :-)

**Comment by juhaszviktor** [comment]
Yes, when I will have time for it :)

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by bazsi** [comment]
Closing in favour of #1679

**Pull request closed without merging**
