### PR TITLE
geoip2: test use maxmindb enterprise database

### PR DESCRIPTION
**Pull request by Kokan**
Info: https://github.com/balabit/syslog-ng/issues/2178#issuecomment-419622923

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
So in summary, you replaced our small custom database to an official one, because there was a leak in libmaxminddb and we've triggered it with the custom database.
The leak has been fixed, but it requires time to appear in distros we use for development/testing.

+12 KB is not much difference, I'm OK with that.

**Pull request merged**
