### PR TITLE
[WIP] redis queue plugin

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Hi,

As a part of my ``GSoC 2018`` project, I have developed a redis queue plugin with the guidance of **@Kokan**.

The aim of this project is to develop a Redis based queue interface which could be an alternative to the disk queue.

This is an inner-destination plugin which uses a redis based queue.  The redis queue stores every message on the redis server in a serialized format,

Usage examples,
```
destination d_network {
 	network("127.0.0.1" port(1234) 
             redis-queue( 
               host("192.168.1.4") 
               port (8888) 
               auth("syslog") 
               key_prefix("syslog-ng") 
               conn_timeout(1) 
             )
        );
};

destination d_file {
	file(
             "/var/log/app.log"
	     redis-queue()
	);
};
```

Thanks,
Mehul

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by lbudai** [comment]
@mehul-m-prajapati : hi!

Split the PR into two parts:
1) generalize queue interface (with a very simple alternative queue impl., which is not redis)
2) implement the Redis based queue

**Comment by lbudai** [comment]
I'd suggest to add some kind of integration tests 
(you can run redis in travis : https://docs.travis-ci.com/user/database-setup/#redis, modify your travis.yml, the travis.yml modifications should not be part of the PR )

**Comment by mehul-m-prajapati** [comment]
Hi @lbudai ,

For splitting PR into 2 parts,
1st PR with a branch name queue-interface(B1). It will contain a simple queue
2nd PR with a branch name redis-queue(B2) which is created from B1. It will contain redis methods.

Is it correct?

For integration tests, is it ok to develop python based function test case in tests/functional ?


Thanks,
Mehul

**Comment by lbudai** [comment]
@mehul-m-prajapati: yes, it’s correct and Python based func test is ok.

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
we have discussed this PR with @mehul-m-prajapati and this PR as is can be closed, and he is going to open a new one once ready.

**Pull request closed without merging**
