### PR TITLE
Grouping by fixes

### PR DESCRIPTION
**Pull request by bazsi**
These are fixes to the grouping-by parser that @pzoleex has found, please do not merge until kira is updated with the testcases.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-grouping-by-parser;

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: pzolee-grouping-by-parser and test suite: functions

**Comment by pzoleex** [comment]
@bazsi Bazsi These fixes work, but we have another two other issues:
https://github.com/balabit/syslog-ng/issues/1737
https://github.com/balabit/syslog-ng/issues/1738

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-grouping-by-parser;

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: pzolee-grouping-by-parser and test suite: functions

**Comment by lbudai** [comment]
I'm going to merge this as-is.
There is one issue that is not fixed by this PR (discarded counter), so the code will be better with this PR :)

**Comment by bazsi** [comment]
I was still working on some unit tests, but we could merge those later on as a separate PR.

**Pull request merged**
