### PR TITLE
App parser kill switch

### PR DESCRIPTION
**Pull request by bazsi**
This patch implements auto-parse(yes/no) option into

- the app-paser()
- and through the use of __VARARGS__ system() and default-network-drivers()

this was requested by @czanik

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
With these patches it is not possible to control which applications are processed by auto-parser:

```
# disable completely
system(auto-parse(no));

# all parsers enabled, except a few
system(auto-parse-exclude("foo,bar,baz"));

# only a few specific are enabled
system(auto-parse-include("foo,bar,baz"));
```

The same options should work with the default-network-drivers() stuff as well.

**Comment by bazsi** [comment]
@czanik feedback and testing would be welcome, as always.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by czanik** [comment]
I have tried:
```
system(auto-parse-exclude("iptables"));
```
And iptables logs were no more parsed, but sudo logs were still parsed.

**Comment by czanik** [comment]
```
system(auto-parse-include("iptables"));
```
also worked fine.

**Comment by czanik** [comment]
```
system(auto-parse(no));
```
also worked fine.

I also did a very basic performance test with the above setting: no measurable difference with the system source. My suspicion is, that the journal() source is the bottleneck here.

**Comment by lbudai** [comment]
@czanik : thx for feedbacks.

**Pull request merged**
