### PR TITLE
Remove diskq option from file destinations

### PR DESCRIPTION
**Pull request by gaborznagy**
This pull request is created to disallow the usage of diskq plugin in some destinations (e.g file and pipe destinations). See SYSLOGDEV-3479
For this the diskq module's context in the grammar has to be changed so it will not be generally available for all destination drivers.

Some aspects considered:
- modules which can use the diskq module should be able to use general destination plugins too.
- we want to keep the possibility to have general destination plugins for modules that cannot use diskq.

What has been done:
-   create new context for diskq in lexer and grammar
-  add new plugin_find interface to be able to search with multiple contexts (therefore modules can access to general destination plugins and to diskq module)
- restructured grammar of destination driver options

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Hmm, pipe() should be able to use disk buffers, cant it?

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
I think we agreed that this will not go in this form, at least until we checked if it is simpler to actually support disk queues even in the file destination. So I would close it and reopen at the point we have the solution.

**Comment by bazsi** [comment]
Please open a new PR once there's a decision on how to move forward with this.

**Comment by presidento** [comment]
The team decided to keep it open. Previously we had the "purgatory" label for PRs which have good parts, but we do not want to merge, at all. The team decided that the "blocked" label is enough in this case, this is why we kept it open.

**Pull request closed without merging**
