### PR TITLE
F/turn on werror k

### LINKED ISSUE #776: Eliminate compiler warnings and turn on -Werr
I used the master branch.

```
../modules/afprog/afprog.c: In function 'afprogram_reload_store_item_free':
../modules/afprog/afprog.c:69:3: warning: passing argument 1 of 'log_pipe_unref' from incompatible pointer type [enabled by default]
   log_pipe_unref(reload_info->writer);
   ^
In file included from ../lib/driver.h:29:0,
                 from ../modules/afprog/afprog.h:27,
                 from ../modules/afprog/afprog.c:24:
../lib/logpipe.h:237:6: note: expected 'struct LogPipe *' but argument is of type 'struct LogWriter *'
 void log_pipe_unref(LogPipe *self);
      ^
../modules/afprog/afprog.c: In function 'afprogram_dd_kill_child':
../modules/afprog/afprog.c:329:13: warning: unused variable 'pgid' [-Wunused-variable]
       pid_t pgid;
             ^
../modules/afprog/afprog.c: In function 'afprogram_dd_store_reload_store_item':
../modules/afprog/afprog.c:452:3: warning: passing argument 4 of 'cfg_persist_config_add' from incompatible pointer type [enabled by default]
   cfg_persist_config_add(cfg, afprogram_dd_format_persist_name(self), reload_info, afprogram_reload_store_item_destroy_notify, FALSE);
   ^
In file included from ../lib/logpipe.h:30:0,
                 from ../lib/driver.h:29,
                 from ../modules/afprog/afprog.h:27,
                 from ../modules/afprog/afprog.c:24:
../lib/cfg.h:158:6: note: expected 'GDestroyNotify' but argument is of type 'void (*)(struct AFProgramReloadStoreItem *)'
 void cfg_persist_config_add(GlobalConfig *cfg, gchar *name, gpointer value, GDestroyNotify destroy, gboolean force);

```

To do:
- [x] Eliminate compiler warnings - #779
- [ ] Turn on -Werr #871

### PR DESCRIPTION
**Pull request by bkil-syslogng**
After discussing #843 

Fixes #776

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
We've agreed with @ihrwein that he'll check out and review this final PR in depth now and if he likes it, Laci or Viktor should be the one to merge.

**Comment by ihrwein** [comment]
@lbudai or @juhaszviktor can merge this :)

**Comment by lbudai** [comment]
sorry for late reactions: we have to schedule a merge day then we have to figure out something to avoid blocking situations like this

**Comment by bkil-syslogng** [comment]
I have rebased the extra tests from test_kv_parser.c to #877.

I have left `test_pathutils.c` intact if it is okay with you. (Actually I would simply test whether '`.`' is a directory and "`$0`" is a file)

Travis status: passed

**Comment by bkil-syslogng** [comment]
You can compare the diff before and after the rebase side by side using my private temporary PR:
https://github.com/bkil-syslogng/syslog-ng/issues/14

**Comment by ihrwein** [comment]
:+1:

**Pull request merged**
