### PR TITLE
fix include guard in systemd-journal

### PR DESCRIPTION
**Pull request by abenbachir**
replaced AFPROG_PARSER_H_INCLUDED by SYSTEMD_JOURNAL_PARSER_H_INCLUDED

### CODE REVIEW

**Comment by MrAnno** [comment]
Hi @abenbachir,

Thanks for catching this! :+1:

**Comment by MrAnno** [comment]
Just a minor request:
Please use the following commit message pattern:
```
modulename: short description of the commit

Signed-off-by: Name <email>
```

For example:
```
systemd-journal: fix header defines 

Signed-off-by: Abder Benbachir <anis.benbachir@gmail.com>
```

**Comment by bazsi** [comment]
This pull request **fixes 2 alerts** when merging 560ba6856d7334ef876b600a65c707ef0922310e into f9302be354d2ece3c63a899f644e0553a6069184 - [view on LGTM.com](https://lgtm.com/projects/g/balabit/syslog-ng/rev/pr-b09f891686bf5112bd3b52b08519396564bf15c7)

**fixed alerts:**

* 2 for Duplicate include guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by abenbachir** [comment]
@MrAnno your are welcome.
I have a question, is there a way the compile a destination module outside of syslog-ng tree ?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
This pull request **fixes 2 alerts** when merging 0dc483c330d67baf0c8d44dc8298351b34024f92 into f9302be354d2ece3c63a899f644e0553a6069184 - [view on LGTM.com](https://lgtm.com/projects/g/balabit/syslog-ng/rev/pr-fc7873a721dd757f76f2e0501f9b3fb78dcd50d8)

**fixed alerts:**

* 2 for Duplicate include guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by szemere** [comment]
@kira-syslogng retest this please

**Comment by MrAnno** [comment]
@abenbachir Thanks.

> Is there a way the compile a destination module outside of syslog-ng tree ?

We have a syslog-ng-dev package that contains pkg-config files. It can be used to compile external modules. pkg-config is supported by all known build systems, for example CMake has [pkg_check_modules](https://cmake.org/cmake/help/v3.13/module/FindPkgConfig.html).

Another example (for autotools) can be found in the syslog-ng incubator, it is a discontinued repository, but it's good as an example:

https://github.com/balabit/syslog-ng-incubator/blob/master/configure.ac#L124-L135

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
