### PR TITLE
split test_patterndb_rule testcase

### PR DESCRIPTION
**Pull request by bazsi**
This series splits test_patterndb_rule testcase to smaller functions, making the tested functions easier
to understand. This is a preparatory step to implement create-context action, which will be posted in a separate branch.

### CODE REVIEW

**Comment by lbudai** [comment]
LGTM
(just one small note: there is a typo in correl**_l_**ation)

**Comment by bazsi** [comment]
Where's the typo?

**Comment by bazsi** [comment]
ahh. so the verb correlate is with a simple "l".

that's a pretty big issue though as the entire plugin was consistently named as "correllate".

I would say we should merge this as is and then fix the typo with the appropriate aliases left intact. I would do the rename. I was so sure that it was written with two "l" letters.

**Comment by bazsi** [comment]
So I would do the rename in a later patchset, but do that in the entire plugin,  not just the new additions.

Do you agree?

**Comment by lbudai** [comment]
@bazsi : I absolutely agree.

**Comment by bazsi** [comment]
Is this ok for merging? You said it was ok for you, but shall I wait for other reviewers? Can I press the merge button?

thanks

**Comment by lbudai** [comment]
I think it is ok.

**Pull request merged**
