### PR TITLE
Kv scanner allow using space as pair separator

### PR DESCRIPTION
**Pull request by bazsi**
this should fix the issues pointed out in #1282

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@bazsi: could you resolve the conflict?
Then I think it is ready for merge.

( :+1: )

**Comment by bazsi** [comment]
@kira-syslogng reset this please

**Comment by bazsi** [comment]
I would once @kira-syslogng reports success. This is not yet approved, but I guess I can still merge this with @lbudai's approval, right?

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
