### PR TITLE
afamqp: follow up librabbitmq change

### PR DESCRIPTION
**Pull request by bazsi**
Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
hmm... I'm sure that I saw this change somewhere... @kokan ?

**Comment by bazsi** [comment]
Well, I dont see the change on master and with rabbitmq updated it does not compile. I might be missing something, but this has caused me compile failures after rebase.

**Comment by Kokan** [comment]
Could you please check your rabbitmq-c submodule HEAD ?
It should be the following:

> commit 45e699b7c5bf11168ad325df417fdd18cb86e862
> Author: kokan <peter.kokai@balabit.com>
> Date:   Mon Sep 11 07:42:29 2017 +0200
> 
>     Calling va_start with enum is undefined behavior, replaced enum with compatible int.

**Comment by bazsi** [comment]
This was a mistake, my git rebase reverted one of the librabbitmq-c related changes, causing a compile failure, which I fixed by effectively reverting the other coupled change.

So this is not needed.

**Pull request closed without merging**
