### PR TITLE
Docker based build updates

### PR DESCRIPTION
**Pull request by bazsi**
This branch finally integrates the debian packaging in packaging/ to the docker based build flow, which
basically makes it possible to do snapshots and releases using docker, right from the source, in a controlled environment.

It makes it easy for anyone to compile a binary snapshot without a need to struggle with autoconf and friends.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@bazsi: thanks!!

**Comment by lbudai** [comment]
@bazsi: here two additional patches that fixes your PR: 
 * copyright check fix: https://github.com/lbudai/syslog-ng/commit/7e9133e03cc855904a5497b823523bb7b78cda61
 * dbld/Makefile.am fix: https://github.com/lbudai/syslog-ng/commit/67ed9b39d7b090d72e5a02412454314672915c77

**Comment by lbudai** [comment]
@bazsi: I tested your PR by creating a pkg-tarball.
Some changes were required by OBS (rules, control), but it worked, so I push my changes on your branch and I'd merge this PR.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
:) thanks, this actually makes syslog-ng build like a helloworld application, especially if we publish the images on dockerhub.

Considering the build issues a guy just recently had, this stuff is ballot needed.

**Pull request merged**
