### PR TITLE
F/improve deinit leaks mutex (add missing global deinitialization, Valgrind fixes)

### PR DESCRIPTION
**Pull request by bkil-syslogng**
We missed global deinitialization of various objects. These changes make the code more self contained and fix some Valgrind warnings as well.

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
I've rebased to master and addressed comments raised in:
https://github.com/balabit/syslog-ng/compare/master...bkil-syslogng:t/improve-deinit-leaks-mutex-bk0

Here are the separate old commits for reference:
https://github.com/bkil-syslogng/syslog-ng/commit/857d42a9102b95f924be62f29db7cf240583925d
https://github.com/bkil-syslogng/syslog-ng/commit/d48cda809be9c7202b54e8b37303b85bf1e7eb31
https://github.com/bkil-syslogng/syslog-ng/commit/5570020acd17034c85385cb5c3daf590a6c57bd4
https://github.com/bkil-syslogng/syslog-ng/commit/7b7645f853ad0e9a59f57df5dcd60d72b6faf232

**Comment by bkil-syslogng** [comment]
Rebased to master

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by furiel** [comment]
Closed in favour of https://github.com/balabit/syslog-ng/pull/1649

**Pull request closed without merging**
