### PR TITLE
[wip]Stats autoreset ctr

### PR DESCRIPTION
**Pull request by lbudai**
@bazsi: could you check it if works?
If yes, then we could merge the first part of this PR (without the single-stats), then later, in another PR I'll change the single-stats-cluster.

Note that it is rebased to #2294

(Stats is a little bit complicated.)

### CODE REVIEW

**Comment by lbudai** [comment]
@kira-syslogng : Test this please

**Comment by lbudai** [comment]
@kira-syslogng test this please

**Comment by bazsi** [comment]
This does not add counters but set them, or.am I missing something?

**Comment by lbudai** [comment]
@bazsi: pushed

**Comment by bazsi** [comment]
Thanks, will check it out

On Sep 20, 2018 20:10, "Budai Laszlo" <notifications@github.com> wrote:

@bazsi <https://github.com/bazsi>: pushed

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/balabit/syslog-ng/pull/2297#issuecomment-423280620>,
or mute
the thread

**Comment by lbudai** [comment]
@kira-syslogng retest this please

**Comment by bazsi** [comment]
It still has some issues, but I think is in the right direction.

1) the logqueue initial allocation is strange, the LogQueue interface has disk queue specific fields, that are always zero for memory based queues, thus their memory allocation is lost. This is probably the reason for the kira failure as well. With a simple reload, the memory_usage counter remains zero, even though the addition is there. The "queued" value seems to work.

2) the queues may need to save their original memory usage in an instance variable to be able to be able restore it, should they be still used after reload.

3) we might want to get rid off "use" function, why don't we simply register the counter again with the same key? As far as I see it's basically the same. We could get rid of the "is_registered" style conditionals in the registration functions and most of the bodies of _use and _track is the same anyway.

4) _register_memory_usage_counter seems to ignore its stats_level argument and uses a fixed value instead.

That's it for now.

**Comment by lbudai** [comment]
@bazsi: I’m not sure this is the right way.
If a memory usage counter contains a value, and the counter is not reset during reload, why do we want to save values and then accumulate them again? The stats counters are located in a hashtable(to be precise, the statscluster are stored in this table) which is like persist-config: values are accessible after a reload.

**Comment by bazsi** [comment]
Because we might have multiple queues and the number of queues might change
accross reloads, registered to the same counters.

**Comment by lbudai** [comment]
@bazsi: indeed... then I'll change the code accordingly

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by pzoleex** [comment]
@kira-syslogng test this please;

**Comment by pzoleex** [comment]
@kira-syslogng test this please;

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Pull request closed without merging**
