### PR TITLE
F/some polishments

### PR DESCRIPTION
**Pull request by ihrwein**
This PR contains some polishments on different subjects. All of these modifications are needed to a Rust based filter implementation:

* the static inline functions are not exported from `libsyslog-ng.so`
* it makes a lot of sense to use `const` in Rust
* the getter functions hide the inner structure of `GlobalConfig`
* Rust doesn't have variadic functions (just macros)

### CODE REVIEW

**Comment by bazsi** [comment]
looks good to me.
+1

**Comment by ihrwein** [comment]
Maybe we should repeat the benchmarks and compare the performance of the functions with and without the `static inline` modifier. If the latter one isn't significantly slower, we may omit the `static inline` modifier.

**Comment by bazsi** [comment]
Hi,

you can do that with the test_template_speed test, for me its in
lib/template/tests


-- 
Bazsi

**Comment by ihrwein** [comment]
I run the test 100 times on my machine with and without `static inline` . I calculated the average for each measured value, then calculated the percentage in the form of `functions with static inline`/ `without static inline`. I only modified `log_msg_get_value()` and `log_msg_get_value_by_name()`.

```
![image](https://cloud.githubusercontent.com/assets/1019384/6805801/45f61326-d245-11e4-8a8b-a42a95134feb.png)

```

**Comment by bazsi** [comment]
I don't understand the picture, unfortunately.


-- 
Bazsi

**Comment by ihrwein** [comment]
I updated my last comment.

**Comment by ihrwein** [comment]
Are there problems with the other commits, too?

Should I include my Python script which does the measurement and exports the data in csv? That way you can also test the results.

**Comment by lbudai** [comment]
Those numbers are .... well... hmm... interesting.... but could you attach a simple diagram which shows what did you measure exactly?

So you say, that you didn't see performance penalty when you used `log_msg_get_value()` without `static inline` ?

**Comment by ihrwein** [comment]
I repeated the tests with my laptop and got a little different result.

image

You can find the sheet with the raw data here:
http://home.sch.bme.hu/~btibi/upload/results_1000.ods

**Comment by bazsi** [comment]
Hi,

Based on this I would keep the static inline annotations, the average of
the average speedup is around +9%, only one cases is slower (at 97.5%), but
I guess that's again a measurement problem. The best is +22% and if you
look at the numbers on a chart, clearly the division between "static
inline" present and missing is clearly visible.


-- 
Bazsi

**Comment by ihrwein** [comment]
Then let's just find a proper name for the non-static-inline version. The `optimized` may do it for me, as Laci mentioned.

**Comment by ihrwein** [comment]
I used the `optimized` prefix and updated the files except the unit tests. They use the new functions.

**Comment by lbudai** [comment]
it's ok for me
:+1:

**Comment by ihrwein** [comment]
@bazsi: is it OK for you, too?

**Comment by juhaszviktor** [comment]
Sorry, I don't really like it.
Why do you rename the existing function, instead of create a new one with new name, and use it where you want? (e.g.: log_msg_get_value_non_static or something similar)
With this modification the newly created log_msg_get_value function will be used everywhere, causing possible performance penality. (e.g.: syslog-ng-incubator).
-1

**Comment by ihrwein** [comment]
What's the better function to expose:

* `log_msg_get_value_non_static()` or
* `log_msg_get_value()`?

I don't think we should expose this change through the API. The measurement showed a 9% speedup, but it doesn't mean that it's 9% in production when syslog-ng's job is not just formatting templates, but to parse, filter, receive and send messages.

**Comment by bazsi** [comment]
The best would be to use the same name as the function is the same, we only
need the function body to be defined somewhere. This can be done with an
__attribute__ declaration.

e.g.

```
static inline const gchar * log_msg_get_value(...)
{
...
}
```

And in logmsg.c:
```
static const gchar *__log_msg_get_value()
__attribute__((alias("log_msg_get_value")))
```

This way the __ symbol properly indicates that it is static, but still the
body is available under the same name. A similar effect can be achieved via
Glib's infrastructure to inline functions, but it seems to be a bit too
complicated.

Regarding the point on performance, you are right that syslog-ng does other
things than doing log_msg_get_value() calls, however:
1) the destination thread is usually the bottleneck
2) most of the task of the destination thread is to format the message
3) log_template_format() seems to be about 10% slower without static inline

So albeit it is true, that syslog-ng wouldn't be 10 percent slower as a
whole, I definitely would expect a couple of percent points in real-life
scenarios as well. (basically that's why I did the opimization and
test_template_speed as a micro-benchmark).



-- 
Bazsi

**Comment by lbudai** [comment]
Alias based solution is definitely superior.

**Comment by ihrwein** [comment]
I updated this PR according to Bazsi's suggestion. Thanks!

**Pull request merged**
