### PR TITLE
Add osquery scl to syslog-ng

### PR DESCRIPTION
**Pull request by czanik**
It reads the osquery log file and parses with the JSON parser,
creating name-vaule pairs with an .osquery. prefix by default.

file() and prefix() can be overriden.

Example usage:

source s_osquery { osquery(prefix("micimaci.")); };
destination d_json { file("/var/log/test.json" template("$(format_json --scope rfc5424 --scope nv-pairs)\n\n")); };
log { source(s_osquery); destination(d_json); };

Signed-off-by: Peter Czanik <peter@czanik.hu>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by bazsi** [comment]
@kira-syslogng: ok to test

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by czanik** [comment]
Should I add quotes to nodejs/plugin.conf in a separate PR? I used that as an example and that is missing quotes as well...

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
