### PR TITLE
syslog-ng-ctl: change output format to =

### PR DESCRIPTION
**Pull request by kvch**
The format is changed to make parsing easier.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
why is this making parsing easier?

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kvch** [comment]
@bazsi The goal was to be able to parse `monitoring` source and `syslog-ng-ctl stats` using the same method, because both of them return the same information.

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-stats-change-output-format-to;

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: pzolee-stats-change-output-format-to and test suite: functions

**Pull request merged**
