### PR TITLE
WIP: Dbld kira improvements

### PR DESCRIPTION
**Pull request by bazsi**
This branch builds on top of #2724 and adds a couple of further improvements.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
This pull request **introduces 2 alerts** when merging 2dd3023138bfda1890f4afa1de05a1e25e310239 into cf10b3c4a50d8feda50826b518428719fd974a1c - [view on LGTM.com](https://lgtm.com/projects/g/balabit/syslog-ng/rev/pr-cad3588f6033e0db5e4ce7ecefc0590d0f53c4a0)

**new alerts:**

* 2 for Ambiguously signed bit\-field member

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@bazsi I've pushed a commit to this branch (dbld-kira-improvements) to fix Travis. Sorry, I thought this is the PR that you want to include in 3.22 (in fact, it is #2724), that's why I started to fix the Travis issue.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
I am closing this in favour of smaller, more trivial branches.

**Pull request closed without merging**
