### PR TITLE
tlscontext: make TLSContext refcounted

### PR DESCRIPTION
**Pull request by lbudai**
fixes: #2080

Signed-off-by: Laszlo Budai <stentor.bgyk@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
I modified the original code a little bit: I added an extra `msg_error` call that is called unconditionally... so the possibility of the crash dramatically increased. Of course the PR doesn’t contain this 'improvement' but maybe useful when testing it.

**Comment by lbudai** [comment]
@algernon
@MrAnno: thanks for the very fast reaction :)

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
@algernon We really need this patch on the master, I'm merging it.
If you find anything with valgrind, I'll fix it in a separate PR.

**Pull request merged**
