### PR TITLE
Kv scanner scratch buffers

### PR DESCRIPTION
**Pull request by bazsi**
An alternative for #1787

### CODE REVIEW

**Comment by bazsi** [comment]
Removes a lot of boilerplate, increases performance, and resolves a race. :)

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mitzkia** [comment]
Tested with the reproduction in #1773, syslog-ng did not crash.

**Pull request merged**
