### PR TITLE
Two additional writer options

### PR DESCRIPTION
**Pull request by batk0**
multi-line-to-cr - replace all CR and LF with CR
multi-line-to-lf - replace all CR and LF with LF

### CODE REVIEW

**Comment by bazsi** [comment]
Could you describe your use case for these optiond?

Thanks

**Comment by batk0** [comment]
There are two use cases for me.
1. Basically I have two syslog-ng servers. The first one works as a proxy and the second one as a storage. I set multi-line-to-cr on the first one and multi-line-to lf on the second one, so multi-line messages go to the files untached without syslog headers.
2. I have a SIP server that logs SIP messages with lines separated by '\r', so it helps me to see SIP as it should be.
I've used this patch since 3.3 release.

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by presidento** [comment]
Outdated.

**Pull request closed without merging**
