### PR TITLE
afsocket: using msg_control only when credential passing is supported

### LINKED ISSUE #542: Problems trying to compile syslog-ng 3.6.4 on Solaris 11.2 (SPARC)
From OSE mail list:
```
Have compiled and installed eventlog-0.2.12  (into /usr/local/syslog-ng).
 
Now trying to compile syslog-ng I’m hitting the error shown at the end.
 
Following commands were used to configure the environment for the compile
 
export PKG_CONFIG_PATH=/usr/local/syslog-ng/lib/pkgconfig
./configure --prefix=/usr/local/syslog-ng --enable-sun-streams --enable-tcp-wrapper --enable-ipv6 --enable-sql --enable-ssh --with-ld-library-path=/usr/local/syslog-ng/lib --disable-amqp --enable-sun-door
 
Any suggestions ?
 
Thanks

Ian
 
  CC     modules/afsocket/modules_afsocket_libafsocket_notls_la-transport-mapper-unix.lo
  CC     modules/afsocket/modules_afsocket_libafsocket_notls_la-transport-unix-socket.lo
modules/afsocket/transport-unix-socket.c: In function â_format_proc_file_nameâ:
modules/afsocket/transport-unix-socket.c:50:3: warning: format â%dâ expects argument of type âintâ, but argument 4 has type âpid_tâ [-Wformat=]
   g_snprintf(buf, buflen, "/proc/%d/%s", pid, proc_file);
   ^
modules/afsocket/transport-unix-socket.c: In function â_unix_socket_readâ:
modules/afsocket/transport-unix-socket.c:219:6: error: âstruct msghdrâ has no member named âmsg_controlâ
   msg.msg_control = ctlbuf;
      ^
modules/afsocket/transport-unix-socket.c:220:6: error: âstruct msghdrâ has no member named âmsg_controllenâ
   msg.msg_controllen = sizeof(ctlbuf);
      ^
modules/afsocket/transport-unix-socket.c: In function âlog_transport_unix_dgram_socket_newâ:
modules/afsocket/transport-unix-socket.c:261:3: warning: implicit declaration of function âsocket_set_pass_credentialsâ [-Wimplicit-function-declaration]
   socket_set_pass_credentials(fd);
   ^
modules/afsocket/transport-unix-socket.c: At top level:
modules/afsocket/transport-unix-socket.c:36:1: warning: â_add_nv_pair_intâ defined but not used [-Wunused-function]
_add_nv_pair_int(LogTransportAuxData *aux, const gchar *name, gint value)
^
modules/afsocket/transport-unix-socket.c:102:1: warning: â_add_nv_pair_proc_read_unless_unsetâ defined but not used [-Wunused-function]
_add_nv_pair_proc_read_unless_unset(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file, const gchar *unset_value)
^
modules/afsocket/transport-unix-socket.c:115:1: warning: â_add_nv_pair_proc_read_argvâ defined but not used [-Wunused-function]
_add_nv_pair_proc_read_argv(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file)
^
modules/afsocket/transport-unix-socket.c:135:1: warning: â_add_nv_pair_proc_readlinkâ defined but not used [-Wunused-function]
_add_nv_pair_proc_readlink(LogTransportAuxData *aux, const gchar *name, pid_t pid, const gchar *proc_file)
^
gmake[2]: *** [modules/afsocket/modules_afsocket_libafsocket_notls_la-transport-unix-socket.lo] Error 1
gmake[1]: *** [all-recursive] Error 1
gmake: *** [all] Error 2

The contents of this e-mail are confidential and for the exclusive use of the intended recipient. If you are not the intended recipient you should not read, copy, retransmit or disclose its contents. If you have received this email in error please delete it from your system immediately and notify us either by email or telephone. The views expressed in this communication may not necessarily be the views held by McLaren Technology Group Limited. 
McLaren Technology Group Limited | McLaren Technology Centre | Chertsey Road | Woking | Surrey | GU21 4YH | UK | Company Number: 01967715

```

### PR DESCRIPTION
**Pull request by aneutrals**
fixes #542

Signed-off-by: Adam Arsenault <adam.arsenault@balabit.com>

### CODE REVIEW

**Comment by pasztor** [comment]
I did not tested this yet, but are you sure, that this will solve the problem?
You made the definition of ctlbuf depend on CRED_PASS_SUPPORTED.
Let's assume, that is not defined, so there will be no "ctlbuf".
~5 lines later, the usage of it remained in the code:
"
   msg.msg_control = ctlbuf;
   msg.msg_controllen = sizeof(ctlbuf);
"
So, you just doubled it, since you put this (almost this, you extended it with a dereference at the setting of msg.msg_control), also into the ifdef-ed part.

**Comment by lbudai** [comment]
@aneutrals : @pasztor is right,  you just forgot to remove those lines

**Comment by aneutrals** [comment]
Thank you, oversight on my part. I removed the lines accidentally left in in the original PR.

**Comment by lbudai** [comment]
@aneutrals : I know that we figured out this solution together as a quick fix, but now I have an idea how could we do it even better(?): `AC_CHECK_MEMBER` could help us.

In `unix-credentials.h` where we define `CRED_PASS_SUPPORTED`, we could extend the condition with `HAVE_CTLBUF_IN_MSGHDR` which would be defined with the help of `AC_CHECK_MEMBER` in `configure.ac`. In that way we can say that credential passing is supported only if we have the struct which is for storing the credential information AND if the control buffer is also available for transforming these infos. And when can replace `CRED_PASS_SUPPORTED` around setting ctlbuf to `HAVE_CTLBUF_IN_MSGHDR`.

What do you think?

**Pull request merged**
