### PR TITLE
F/elastic bulk concurrent request option

### PR DESCRIPTION
**Pull request by lbudai**
This PR needs #737 to be merged.
Then I'll rebase the branch against master and update this PR.

### CODE REVIEW

**Comment by ihrwein** [comment]
@lbudai I merged #737

**Comment by ihrwein** [comment]
:+1: (but their original default is 1)

http://javadoc.kyubu.de/elasticsearch/v1.2.0/org/elasticsearch/action/bulk/BulkProcessor.Builder.html#setConcurrentRequests(int)

**Comment by lbudai** [comment]
"A value of 0 means that only a single request will be allowed to be executed."
And that is what we wanted as I know.

**Comment by lbudai** [comment]
Rebased to current master.
So now this is mergeable.

**Comment by ihrwein** [comment]
thanks!

**Pull request merged**
