### PR TITLE
.travis.yml: Java support added

### LINKED ISSUE #612: Enable java build in Travis/Drone.io
The problem is the missing gradle.
I think we can install gradle 2.2.1 from my OBS repo.

### PR DESCRIPTION
**Pull request by lbudai**
Java support requires:
  * gradle-2.2.1
  * openjdk-7-jdk

(gradle-2.2.1 is provided by the OBS repo)

Fixes #612

Signed-off-by: Laszlo Budai <stentor.bgyk@gmail.com>

### CODE REVIEW

**Comment by lbudai** [comment]
Before merging this, please merge #611 .

**Comment by dnsjts** [comment]
#611 has been merged, please update/rebase the pull request.

**Comment by lbudai** [comment]
rebased

**Comment by lbudai** [comment]
yess... Travis passed.

**Comment by ihrwein** [comment]
The name of the referenced issue isn't good because it indicates Drone.io support, too. Please rename it, or create a second commit for drone.io in this PR (and rename this PR).

**Comment by lbudai** [comment]
There is no chance for create a drone.io related commit :-)
Because it could be set on the "settings tab" on the management interface in drone.io.

**Pull request merged**
