### PR TITLE
Try to reopen file after NC_MOVED_EOF occured more than once

### PR DESCRIPTION
**Pull request by juhaszviktor**
…. Fixes: #841

Signed-off-by: Juhász Viktor <viktor.juhasz@balabit.com>

### CODE REVIEW

**Comment by ihrwein** [comment]
:+1:

**Comment by lbudai** [comment]
@juhaszviktor : could you split up this patch (refactor patches, and then the bugfix)?. In that case it will be readable :-) Thanks!

**Comment by ihrwein** [comment]
Nominating for `3.7.3` as the commit can be cherry-picked without conflicts.

**Comment by bazsi** [comment]
@juhaszviktor is this patch still valid? seems that it needs at the very least a rebase. I don't see this merged for 3.7.3 either.

**Comment by juhaszviktor** [comment]
@bazsi Yes I think it is still valid.
I will do the refactoring (asked by @lbudai), when I have time.
And I will also do the rebase.

**Comment by kvch** [comment]
Closing, #1209 merged

**Pull request closed without merging**
