### PR TITLE
WIP: kafka threaded source

### PR DESCRIPTION
**Pull request by Kokan**
Introduces a new kafka source based on librdkafka and threaded source.
This is just a very limited version, subscribes to the topics as consumer group (msg ack are tracked with rdkafka and not with syslog-ng also).

Also the reason why this is wip, because I did not test all the cases and the config part is not finish with passing additional arguments.

Basic config:
```
source {
  kafka( brokers("ip1:port; ip2:port") #the broker list is parsed by librdkafka
              topic("test") # there is no way to specify partition now
  );
};

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
This pull request **introduces 2 alerts** when merging e371350e4f505f51d7b1e3c652161b498583a3c8 into a6a00cbd3c8fb5024281163a5c1f8e1cda293790 - [view on LGTM.com](https://lgtm.com/projects/g/balabit/syslog-ng/rev/pr-121fe6f322e27d509c2789313c1791d948f405b5)

**new alerts:**

* 2 for Duplicate include guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by Kokan** [comment]
I'll close this for now, and possible rework it after #2496 is merged.

**Comment by faxm0dem** [comment]
Hi, I'm interested in testing this, as we're introducing Kafka into our logging stack

**Comment by Kokan** [comment]
hmm, for this to be testable it requires imho:
- [x]  rebase on current master
- [ ]  use the kafka properties code, so it could be configured
- [ ]  bookmarking

I did the rebase, so "only" two task remained.

**Pull request closed without merging**
