### PR TITLE
syslog-format: fixed flag check

### LINKED ISSUE #529: timeQuality isSynced is missing from sdata
Cisco routers can specify some additional information in their timestamp:
- whether the timestamp is accurate
- whether the sender has TZ information

this should be added to SDATA when ietf-syslog protocol is used. PE already knows it:

```
<38>1 1990-01-01T14:45:22+02:00 localhost prg00000 1234 - [timeQuality isSynced="0" tzKnown="1"] test message
```

```
config:
@version: 3.7
options{
};
source s_syslog{syslog(port(1112)
);};

destination d_syslog_file{file("/tmp/output_syslog.txt"
flags(syslog-protocol)
);};

log{
source(s_syslog);
destination(d_syslog_file);
};
options{threaded(yes);};
```

message:

```
echo "73 <38>1 1990-01-01T14:45:22+02:00 localhost prg00000 1234 - - test message" | /opt/syslog-ng/bin/loggen 127.0.0.1 1112 -d -R -
```

### PR DESCRIPTION
**Pull request by dnsjts**
Fixes #529.

### CODE REVIEW

**Comment by bazsi** [comment]
Hmm, this seems to be wrong.

**Comment by dnsjts** [comment]
Was that check intentional (and I do not understand the purpose), or is there a typo?

**Comment by ihrwein** [comment]
I think it this PR needs some clarification (what it solves and why).

**Comment by dnsjts** [comment]
According to the parent issue, the Cisco-specic timestamp should be interpreted regardless of which syslog protocol was used.
Removing the check of the protocol should solve the issue.

**Comment by bazsi** [comment]
stop there, pls. rfc5424 has a very specific time format, whereas rfc3164 doesn't. why would we want to accept Cisco specific timestamps when we are in fact parsing rfc5424?

**Comment by dnsjts** [comment]
In this case @pzoleex should be summoned, as he requested the fix.

**Comment by dnsjts** [comment]
Closing due to a miscomprehension of the original issue.

**Comment by bazsi** [comment]
I would appreciate some more details about this.

Thanks

**Comment by dnsjts** [comment]
The discussion will be continued on the page of #529.

**Pull request closed without merging**
