### PR TITLE
Add PCRE / OpenSSL to INSTALL dependency list

### PR DESCRIPTION
**Pull request by kkirsche**
This will make it clearer / quicker to install for new users

### CODE REVIEW

**Comment by bazsi** [comment]
Thanks for your contribution.

Albeit this change could be integrated, that file is almost completely out of date. Especially the configuration section.

The libraries required/optionally needed is also a much broader list.

Could you perhaps update the list with all the packages that the configure script looks for (should give you a list with configure --help, at the section that discusses environment variables, or you could look at PKG_CHECK_MODULES() invocations in the configure script.

thanks again

**Comment by kkirsche** [comment]
Of course. I'll take a look at doing that as soon as possible

**Comment by bazsi** [comment]
If you can, look at readme.md and harmonize these files.

Thanks for your contribution.
Cheers
Bazsi

**Comment by bazsi** [comment]
I have now decided to remove the INSTALL file in favour of README.md completely. That contained old stuff
most of which is covered in README.md

With that said, I am closing this PR. Thanks again.

**Pull request closed without merging**
