### PR TITLE
syslogformat: If the parsing of a message failed, then we had to find the problem with eyegrep

### PR DESCRIPTION
**Pull request by furiel**
The solution is that print the position where the parsing was failed,
not only a something evil happened message

fixes: #SYSLOGMT-643

Signed-off-by: Juhász Viktor <viktor.juhasz@balabit.com>
Signed-off-by: László Várady <laszlo.varady@balabit.com>
Signed-off-by: Antal Nemes <antal.nemes@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
The code used
gchar sd_param_name[33];
to store the max 32 char param name, but inside the code always used patterns like
if (pos < sizeof(sd_param_name) - 1)
which caused the name length could have been only 31 at maximum.
This is also fixed in the changeset.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by furiel** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by furiel** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
