### PR TITLE
PytestPART2: MessageBuilder updates

### PR DESCRIPTION
**Pull request by mitzkia**
This patch set allows to define various message parts during the message generation from functional tests

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
As discussed IRL, let's remove `create_dummy_message(message_value)`.
And format_message` can be modified that it writes default value for the missing fields.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by mitzkia** [comment]
I have added updates. Removing WIP flag.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
