### PR TITLE
Version/3.12

### PR DESCRIPTION
**Pull request by lbudai**
Please do not merge it, I'm waiting for a bugfix PR I want to merge before this.
But it is ready for review.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
#1687 is the bugfix I waited for.
So this PR can be merged.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
I merge this as I want to prepare for the release.

**Pull request merged**
