### PR TITLE
Fix macOS build (automake + CMake)

### LINKED ISSUE #1866: fmemopen() is not available on BSD/MacOS
# syslog-ng

## Version of syslog-ng
git master

## Platform

MacOS
Darwin 15.6.0

# Issue

## Failure

```
[ 48%] Building C object modules/add-contextual-data/tests/CMakeFiles/test_context_info_db.dir/test_context_info_db.c.o                                                                               
/Users/orion-admin/syslog-ng/modules/add-contextual-data/tests/test_context_info_db.c:204:14: warning: 
      implicit declaration of function 'fmemopen' is invalid in C99
      [-Wimplicit-function-declaration]
  FILE *fp = fmemopen(csv_content, strlen(csv_content) + 1, "r");
             ^
/Users/orion-admin/syslog-ng/modules/add-contextual-data/tests/test_context_info_db.c:204:9: warning: 
      incompatible integer to pointer conversion initializing 'FILE *' (aka 'struct __sFILE *')
      with an expression of type 'int' [-Wint-conversion]
  FILE *fp = fmemopen(csv_content, strlen(csv_content) + 1, "r");
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/orion-admin/syslog-ng/modules/add-contextual-data/tests/test_context_info_db.c:244:9: warning:
      incompatible integer to pointer conversion initializing 'FILE *' (aka 'struct __sFILE *')
      with an expression of type 'int' [-Wint-conversion]
  FILE *fp = fmemopen(csv_content, sizeof(csv_content), "r");
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/orion-admin/syslog-ng/modules/add-contextual-data/tests/test_context_info_db.c:322:9: warning:
      incompatible integer to pointer conversion initializing 'FILE *' (aka 'struct __sFILE *')
      with an expression of type 'int' [-Wint-conversion]
  FILE *fp = fmemopen(csv_content, strlen(csv_content) + 1, "r");
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/orion-admin/syslog-ng/modules/add-contextual-data/tests/test_context_info_db.c:344:9: warning:
      incompatible integer to pointer conversion initializing 'FILE *' (aka 'struct __sFILE *')
      with an expression of type 'int' [-Wint-conversion]
  FILE *fp = fmemopen(csv_content, strlen(csv_content) + 1, "r");
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/orion-admin/syslog-ng/modules/add-contextual-data/tests/test_context_info_db.c:410:9: warning:
      incompatible integer to pointer conversion initializing 'FILE *' (aka 'struct __sFILE *')
      with an expression of type 'int' [-Wint-conversion]
  FILE *fp = fmemopen(csv_content, sizeof(csv_content), "r");
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings generated.
[ 48%] Linking C executable test_context_info_db
Undefined symbols for architecture x86_64:
  "_fmemopen", referenced from:
      _add_contextual_data_test_import_with_valid_csv_impl in test_context_info_db.c.o
      __assert_import_csv_with_single_selector in test_context_info_db.c.o
      _add_contextual_data_test_import_with_invalid_csv_content_impl in test_context_info_db.c.o
      _add_contextual_data_test_import_with_csv_contains_invalid_line_impl in test_context_info_db.c.o
      _add_contextual_data_test_import_with_prefix_impl in test_context_info_db.c.o
ld: symbol(s) not found for architecture x86_64
```

## Steps to reproduce
```
cmake ..
make
```

See https://github.com/martinh/libconfuse/pull/80/files for a similar fix.

### PR DESCRIPTION
**Pull request by MrAnno**
The macOS build guide has also been updated.
Please merge this PR together with balabit/syslog-ng-gitbook#59.

Fixes #1866 (Well technically it doesn't, but it's not worth implementing our compat `fmemopen()` layer for a single unit test in my opinion. fmemopen() is available from macOS version 10.13)

Questions:
1. **Can I make the macOS build mandatory in Travis?** This would be a big commitment, but I would really like to do it. If you have a look at the content of this PR, you'll notice that 6-7 out of 11 commits is about fixing general issues, not macOS specific things (--> macOS is also good for detecting non-portable code and CMake/automake bugs).

-----------------------

TODO:
- [x] 9 unit tests are crashing within Travis (macOS only of course :)) - done, Travis is green now
- [x] Fix CMake build (`cmake -DIVYKIS_SOURCE=system -DENABLE_GETENT=OFF ..`)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
failure

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by furiel** [comment]
I want to approve this, because it contains great changes and fixes the autotools-version of build. However it does not fix 1866, because that issue is about cmake. @MrAnno do you plan to fix cmake as well?

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by MrAnno** [comment]
@furiel You can build syslog-ng on macOS with CMake: `cmake -DIVYKIS_SOURCE=system -DENABLE_GETENT=OFF`. 

I haven't updated the macOS guide to use CMake, but I think it's okay for now (our automake-based build seems to be more stable on macOS).

**Comment by furiel** [comment]
@MrAnno thank you for your hard work!

One last request: please remove
```
allow_failures:
- os: osx
```
from .travis.yaml for quality assurance what you achieved here!

**Comment by MrAnno** [comment]
@furiel I agree, this is part of the description of the PR (as a question). Let's discuss this IRL on Wednesday.

**Comment by gaborznagy** [comment]
I've checked and all requested changes have been made.
I'm approving it, though we still have an open question that will be discussed soon:
>Can I make the macOS build mandatory in Travis?

**Comment by kira-syslogng** [comment]
success

**Comment by gaborznagy** [comment]
Travis fails for the macos build:
https://travis-ci.org/balabit/syslog-ng/jobs/365019953#L1910-L1928
When installing riemann-client's dependency python2 it fails at brew link.
Strange, in previous travis tests python2 dependecy was not seen:
https://travis-ci.org/balabit/syslog-ng/jobs/361299719
```
==> Installing dependencies for riemann-client: json-c, protobuf, protobuf-c
```

Log quote from failing travis job:
```
==> Installing riemann-client dependency: python@2
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.14_3.el_capita
==> Pouring python@2-2.7.14_3.el_capitan.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-2
Target /usr/local/bin/2to3-2
is a symlink belonging to python. You can unlink it:
  brew unlink python
To force the link and overwrite all conflicting files:
  brew link --overwrite python@2
To list all files that would be deleted:
  brew link --overwrite --dry-run python@2
Possible conflicting files are:
/usr/local/bin/2to3-2 -> /usr/local/Cellar/python/2.7.12/bin/2to3-2
/usr/local/bin/2to3-2.7 -> /usr/local/Cellar/python/2.7.12/bin/2to3-2.7
```

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
failure

**Comment by kira-syslogng** [comment]
failure

**Comment by kira-syslogng** [comment]
failure

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
failure

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by MrAnno** [comment]
@gaborznagy @furiel Please have a look at the first and the last 2 commits.

Travis now runs for ~15 minutes instead of ~9-10.

**Comment by kira-syslogng** [comment]
failure

**Comment by kira-syslogng** [comment]
success

**Comment by bazsi** [comment]
\o/

Nice.

**Pull request merged**
