### PR TITLE
afsocket: deprecate udp(), tcp(), udp6(), tcp6() option in favour of …

### LINKED ISSUE #2334: Mark TCP(6) and UDP(6) sources/destinations as deprecated
# Issue

*network* source/destination was introduced in syslog-ng 3.5.6 ([grammar change](https://github.com/balabit/syslog-ng/commit/8cc535f77b0511497dfdaa6ada80ef2278ab4ee9))
Syslog-ng should mark the old ones as obsolote, as the documentation does.

# Configuration

```
source s_udp {
    udp();
};
```

# Input and output logs

We expect to get a warning message about using a deprecated config option. i.e.:

```
The tcp() option is deprecated in favour of network()
```

### PR DESCRIPTION
**Pull request by tsunderino**
…network()
Fix #2334

Signed-off-by: Gergely Tonté <gtonte@gmail.com>

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
As i wrote in the associated issue, I would not do this. I wrote reasons as
well, so please consider those before merging this.

Thanks

**Comment by MrAnno** [comment]
We've discussed internally that we don't want to deprecate the tcp() and udp() sources/destinations.

Sorry for the invalid issue and thank you very much for your work!

**Pull request closed without merging**
