### PR TITLE
afsql: Initialize terminate flag

### LINKED ISSUE #1258: Can't not revert to old config if `cfg_init()` failed when using sql as destination.
version: 3.8.1
OS: Ubuntu 16.04 x86_64

## Configuration
```
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.8
#@include "scl.conf"

source s_local {
    unix-stream("/dev/log");
    #internal();
};

source s_network {
    udp();
};

destination d_local {
    sql(
        type(sqlite3)
        database("/var/log/test.db")
            table("logs")
            columns(
                    "id integer primary key",
                    "time int default NULL",
                    "level text default NULL",
                    "msg text default NULL"
            )
            values(
                    "@@NULL@@",
                    "$UNIXTIME",
                    "$LEVEL",
                    "$MSG"
            )
                null("@@NULL@@")
                flags(explicit-commits)
    );
};

log {
    source(s_local);

    # uncomment this line to open port 514 to receive messages
    #source(s_network);
    destination(d_local);
};
```

## Issue
The program will revert old config if `cfg_init()` return false.
```
202   if (cfg_init(main_loop_new_config))
...
211   else
212     {
213       msg_error("Error initializing new configuration, reverting to old config");
214       service_management_publish_status("Error initializing new configuration, using the old config");
215       cfg_persist_config_move(main_loop_new_config, main_loop_old_config);
216       cfg_deinit(main_loop_new_config);
217       if (!cfg_init(main_loop_old_config))
```

The revert process will reuse old destination drivers, but the terminate flag was set `TRUE` when handled the reload process. After that, `_worker_thread_func()` will terminate immediately and the log won't be written to destination.

```
1116   AFSqlDestDriver *self = (AFSqlDestDriver *) s;
1117   g_mutex_lock(self->db_thread_mutex);
1118   self->db_thread_terminate = TRUE;
```

It may cause some strange behaviors when handling next reload process, such as SEGV or ABRT.

## Input and output logs (if possible)
```
[2016-11-16T17:00:37.425552] Error initializing new configuration, reverting to old config;
[New Thread 0x7ffff4169700 (LWP 14509)]
[Thread 0x7ffff7fe0700 (LWP 14503) exited]
[Thread 0x7ffff4169700 (LWP 14509) exited]
[Thread 0x7ffff4a6b700 (LWP 14505) exited]

[2016-11-16T17:00:40.541876] Incoming log entry; line='<85>Nov 16 17:00:40 sshd[14510]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=182.100.67.248  user=root'
[2016-11-16T17:00:42.424574] Incoming log entry; line='<38>Nov 16 17:00:42 sshd[14510]: Failed password for root from 182.100.67.248 port 39192 ssh2'
[2016-11-16T17:00:44.667021] Incoming log entry; line='<38>Nov 16 17:00:44 sshd[14510]: Failed password for root from 182.100.67.248 port 39192 ssh2'
[2016-11-16T17:00:46.849574] Incoming log entry; line='<38>Nov 16 17:00:46 sshd[14510]: Failed password for root from 182.100.67.248 port 39192 ssh2'
[2016-11-16T17:00:49.643277] Incoming log entry; line='<38>Nov 16 17:00:49 sshd[14510]: Failed password for root from 182.100.67.248 port 39192 ssh2'

```

### PR DESCRIPTION
**Pull request by 0xddaa**
Fixes #1258

Signed-off-by: ddaa <0xddaa@gmail.com>

### CODE REVIEW

**Comment by lbudai** [comment]
Thank you for your PR (and for the awesome issue ;) )!

One nitpick: I'd set the `db_thread_terminate` variable to `FALSE` in the `afsql_dd_start_thread` method.

**Comment by lbudai** [comment]
@0xddaa : I opened a new PR that contains the changes I've requested

#1267

**Comment by 0xddaa** [comment]
Thank you. :)
Do I need to close this PR ?

**Comment by kvch** [comment]
Closing as #1267 was merged to master. Thanks. :)

**Pull request closed without merging**
