### PR TITLE
Edited README

### PR DESCRIPTION
**Pull request by sayantanHack**
Few visual changes done in the readme section ; hope all love this. Thank you.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
Hi @sayantanHack,

Thank you for your contribution.
We prefer to keep our Markdown files simple, without embedding raw HTML or visual changes in header lines.

However, your work is really appreciated, and we would be glad to have you contribute to syslog-ng.
May I recommend you the ["good first issue"](https://github.com/balabit/syslog-ng/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) tag on our issue tracking page? We think they are good starting points.

Please feel free to ask anything, we will actively support you during your work.

**Comment by sayantanHack** [comment]
Thanks for your comment .

**Pull request closed without merging**
