### PR TITLE
SourcePortMacro: Added support for $SOURCEPORT macro

### PR DESCRIPTION
**Pull request by mitzkia**
* With this feature we will be able to parse PROXY protocol v1 messages

Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
hm.. what's the usecase here? what are those PROXY protocol v1 messages, I don't get it, sorry.

Also implementation wise this doesn't work with ipv6.

**Comment by mitzkia** [comment]
Sorry about that. The proposal for the feature already created, but for now it is only internally available. I will send you an URL for it. Of course after the proposal is properly created it will be open for the community. Thanks for mentioning ipv6, i will complete the patch with it.

**Comment by bazsi** [comment]
Hmm why not copy paste the proposal here, so that others could see it as
well?

**Comment by mitzkia** [comment]
Because the code and the proposal is not yet ready I suggest to close this PR.

**Pull request closed without merging**
