### PR TITLE
F/remove msg error etc null sentinel

### PR DESCRIPTION
**Pull request by bkil-syslogng**
* `msg_error("description", evt_tag_str("when", "before"), NULL);`
* `msg_error("description", evt_tag_str("when", "after"));`

Contains a `sed` moster and some `vararg` magic.

### CODE REVIEW

**Comment by MrAnno** [comment]
:+1:

**Comment by bkil-syslogng** [comment]
Rebased to master

**Comment by bazsi** [comment]
I like the change in general, even though I didn't have too much time to
check how it works, and neither did I review the individual call sites.


-- 
Bazsi

**Comment by bkil-syslogng** [comment]
Rebased to master.

Fixed conflicts by dropping the last commit and reapplying the script described in the commit message.

**Comment by ihrwein** [comment]
:+1: (Could you rebase it again? Thanks!)

**Comment by bkil-syslogng** [comment]
@ihrwein Rebased to master. No conflict or omission detected when running the transformation this time.

**Comment by bazsi** [comment]
I am afraid I've just merged code that will not be adjusted for this. I would merge this again and fix up the fallout. The change is trivial, makes sense it's just scattered around.

Do you have a script to run on the "http" destination?

**Comment by bkil-syslogng** [comment]
@bazsi You can re-run the commit message as many times as you'd like. Do take care to remove any extra space if your tools show messages that way. Actually I wrapped a long sed line in the middle, that's the (only) one you need to consider.

I did give this a second thought few days ago, and we may consider saving this under `scripts/` and eventually connect it with our Pull Request examination suite in a way that a bot would notify if you used an extra `,NULL`. It's mostly a matter of whether the `git diff` after the transformation is empty or not. In the long run, we could probably connect a bunch of custom LLVM analysis to catch more important typos/common errors as well.

**Comment by bkil-syslogng** [comment]
@bazsi I ran it on the HTTP module. You can check and merge the result and the script file in #1021.

**Comment by bazsi** [comment]
I don't think we need to add this validation from this point on. We don't need it from now period, it may happen that some as-of-now out-of-tree code contains the extra NULL, but we won't write new ones.

**Comment by bazsi** [comment]
thanks a lot and sorry for breaking things. probably not a good idea to
keep PRs out-of-tree for weeks as the chance of stuff breaking when merging
them in improper order is a lot larger.



-- 
Bazsi

**Pull request merged**
