### PR TITLE
afstreams: get rid of superfluous conditional compilation

### PR DESCRIPTION
**Pull request by ihrwein**
Signed-off-by: Tibor Benke <tibor.benke@balabit.com>

### CODE REVIEW

**Comment by ihrwein** [comment]
@bazsi you did something similar with afsql. Could you check this, please?

**Comment by ihrwein** [comment]
This PR is broken till #818 gets merged.

**Comment by bazsi** [comment]
Yup, this looks good to me.

**Comment by ihrwein** [comment]
rebased to master, ready for review & merge

**Pull request merged**
