### PR TITLE
Bug 1896 fixed

### LINKED ISSUE #1896: error initializing python driver object, init(), takes 1 argument but 2 given
## Error
```
[2018-02-27T00:46:08.751935] Exception while calling a Python function; module='#anon-destination0#0', script='sngexample.DummyPythonDest', function='init', exception='TypeError: init() takes 1 positional argument but 2 were given'
[2018-02-27T00:46:08.751964] Error initializing Python driver object, init() returned FALSE; driver='#anon-destination0#0', class='sngexample.DummyPythonDest'
[2018-02-27T00:46:08.751990] Error initializing message pipeline; plugin name='python', location='/home/syslog-ng/syslog-ng.conf:37:5'
```
## Possible Fix
[github.com/balabit/syslog-ng/blob/master/modules/python/sngexample.py](https://github.com/balabit/syslog-ng/blob/master/modules/python/sngexample.py)
```
#modify modules/python/sngexample.py as 
- def init(self): 
+ def init(self,options):
```
### Why is this fix necessary
* Examples are the first step through which a person start to learn using a software so it should be correct at least.
## Version of syslog-ng
```
syslog-ng 3 (3.13.2)
Config version: 3.13
Installer-Version: 3.13.2
Revision:
Compile-Date: Feb 26 2018 23:14:36
```

## Platform

Ubuntu 16.04

## Steps to reproduce

1. start syslog-ng with configuration file present in *modules/python/python-example.conf*

## Configuration
[github.com/balabit/syslog-ng/blob/master/modules/python/python-example.conf](https://github.com/balabit/syslog-ng/blob/master/modules/python/python-example.conf)
```
@version: 3.5

log {
  source { tcp(port(12345)); };
  destination {
    python(
	class("sngexample.DummyPythonDest")
        on-error("fallback-to-string")
        value-pairs(scope(base)
                    pair("foo.bar" "baz")
                    pair("some-int" int("42")))
    );
  };
};
```

### PR DESCRIPTION
**Pull request by videetssinghai**
Resolves #1896
Signed-off-by: videet <videetssinghai@gmail.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by videetssinghai** [comment]
@Kokan I had a doubt in the local repo from where I made the changes my last commit is on top and is up-to-date with master, while when I cloned another copy of master, the commit logs. Does git creates a different tree for pull request commits ?

**Comment by videetssinghai** [comment]
hey @Kokan, do I need to merge my forked repo and the original repo? because, when I did git commit --amend, it said the branch has diverged and when I pushed the amended commit, it said the tip of the branch is behind. Screenshots attached.

ss1
ss2

**Comment by MrAnno** [comment]
Hi @videetssinghai,

`git commit --amend` actually rewrites your commit history, that's why you are experiencing this behavior.

Since you did rewrite your history intentionally, you can just "force-push" your branch:
`git push --force origin master`

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
