### PR TITLE
default-network-drivers: Use if-else statements

### PR DESCRIPTION
**Pull request by mitzkia**
* replace channels with if-else in SCL

Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by lbudai** [comment]
@mitzkia : can we merge your PR?

**Comment by lbudai** [comment]
I asked Micek, and he said, it is ready to merge... so I'm merging this.

**Pull request merged**
