### PR TITLE
Merging eventlog library to syslog-ng

### PR DESCRIPTION
**Pull request by mochrul**
Eventlog library seems to be abandoned. The last commit was more than a year ago and the last version number bump was more than 5 years ago.

The project has only 8 stars and I have no evidence that any other project depends on that but the syslog-ng.

So, to lower the maintenance I did the merge. But this is only the first step.

Later I would like to eliminate the configure script of eventlog and also thinking of moving the files out from the eventlog directory into the lib directory.

I run the check and it passed in a machine where the libevtlog was not installed, so I fairly confident that it is working.

The first patch added the files of the eventlog project as-is. The next two patch is added to make the syslog compile with the added library.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by mochrul** [comment]
Is the Travis run still relevant?
How can the Travis run be (ever) successful without running autogen.sh?

**Comment by bazsi** [comment]
Hi, yup, travis is - still - relevant, and it does run autogen.sh. As it seems the build errors out because it fails to find configure.gnu/configure scripts in lib/eventlog which should be generated by the autogen.sh script.

Looking at that script, it should be done by autogen.sh, there are a few things that make it not do those initialization steps, but I don't know which one fails.

This is a step in the right direction, eventlog as a standalone library should be dropped, so we are in alignment there.

I'd keep it under lib/eventlog at least until it does not use the same conventions as syslog-ng, and until it is licensed under with a non-LGPL license, but those can come later.

Cheers,
Bazsi

**Comment by mochrul** [comment]
The Travis should be able to successfully test the pull request now but I can not see any evidence that it would have started it.

**Comment by bazsi** [comment]
For some reason Travis is not listed as a verification job here, but it should be. I dont know why... Anyway I am asking kira to test this.

@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
It didn't build for some reason (probably after make dist and extraction):
04:06:09 make -C lib/eventlog/src \
04:06:09 	install-includeHEADERS \
04:06:09 	install-nodist_includeHEADERS \
04:06:09 	includedir="/home/jenkins/workspace/syslog-ng-ose/install/include/syslog-ng/eventlog"
04:06:09 make[5]: *** No rule to make target 'install-includeHEADERS'.  Stop.
04:06:09 Makefile:16659: recipe for target 'install-eventlog' failed
04:06:09 make[4]: *** [install-eventlog] Error 2
04:06:09 Makefile:16448: recipe for target 'install-exec-am' failed
04:06:09 make[3]: *** [install-exec-am] Error 2
04:06:09 Makefile:16137: recipe for target 'install-am' failed
04:06:09 make[2]: *** [install-am] Error 2
04:06:09 Makefile:14972: recipe for target 'install-recursive' failed
04:06:09 make[1]: *** [install-recursive] Error 1
04:06:09 Makefile:16131: recipe for target 'install' failed
04:06:09 make: *** [install] Error 2
04:06:09 + docker commit docker_1 syslog_ng/docker_1

**Comment by mochrul** [comment]
Thank you for copying the logs. Is the full log available somewhere? And/or the tests run by Kira stored somewhere reachable by me?

I will fix this issue,  but I would like to avoid a try-and-fix loop if other issues happen.

**Comment by bazsi** [comment]
Yup, you can see the kira logs in the "Checks" part of the pull request view on github.
 
The current log is here:
https://ci.syslog-ng.com/jenkins/job/OSE-PULL-REQUEST-TEST/255/

**Comment by bazsi** [comment]
I don't really get why travis is disabled for this PR though. It should be listed right next to kira.

**Comment by mochrul** [comment]
Interestingly, that button was not there before. Now I can see it but still have no luck.

Access Denied

mochrul is missing the Overall/Read permission

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
<offtopic> This dynamic page loading is fun. Sometimes I see the old failed Kira check, sometimes I see the travis check with the new success Kira check, sometimes I see no check at all. </offtopic>

**Comment by bazsi** [comment]
btw, I am working on a docker based build env which makes it trivially easy to build a new deb package, locally. I have now built your PR with it and it compiled fine, and I am running those debs on my laptop :)

**Comment by bazsi** [comment]
It still links against libevtlog.so though.

$ ldd /usr/lib/syslog-ng/libsyslog-ng-3.9.so.0
	linux-vdso.so.1 =>  (0x00007ffff7ffd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffff7b2a000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007ffff7926000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007ffff7724000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ffff7410000)
	libevtlog.so.0 => /usr/lib/x86_64-linux-gnu/libevtlog.so.0 (0x00007ffff720a000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007ffff7002000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007ffff6d8f000)
	libivykis.so.0 => /usr/lib/x86_64-linux-gnu/libivykis.so.0 (0x00007ffff6b83000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ffff6afb000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007ffff6892000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007ffff644e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffff622e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffff5e67000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffff5c63000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007ffff5a3b000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ffff5815000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007ffff55fd000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ffff52ec000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ffff50d8000)

**Comment by mochrul** [comment]
This happened because of three reasons.

1. The eventlog by default does not create dynamic so modules 
1. The Debian packaging enforce the dynamic linking
1. And it still depends on the libevtlog, so the dynamic object is there.

```
oot@syslog:~/syslog-ng# /opt/syslog-ng/sbin/syslog-ng --version
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /opt/syslog-ng/lib/syslog-ng
Module-Path: /opt/syslog-ng/lib/syslog-ng
Available-Modules: snmptrapd-parser,afstomp,add-contextual-data,pseudofile,afuser,cef,graphite,cryptofuncs,syslogformat,json-plugin,kvformat,afprog,dbparser,tfgetent,afsocket,map-value-pairs,afmongodb,afsql,linux-kmsg-format,date,system-source,sdjournal,csvparser,afamqp,disk-buffer,stardate,confgen,basicfuncs,affile
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: off
Enable-Linux-Caps: on
```

And also:
```
root@syslog:~/syslog-ng# ldd /opt/syslog-ng/lib/libsyslog-ng-3.9.so.0
	linux-vdso.so.1 (0x00007ffd833df000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f56f286b000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f56f2653000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f56f244e000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f56f224c000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f56f1f3d000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f56f1d37000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f56f1ac9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f56f18c5000)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f56f1663000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f56f1267000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f56f104a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f56f0c9e000)
	/lib64/ld-linux-x86-64.so.2 (0x0000557455cc8000)
	libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007f56f0a99000)
```

But of course, I'll fix this dynamic linking thing.

**Comment by bazsi** [comment]
I think the eventlog build system should be faded away entirely, and merged
into syslog-ng's own Makefile.am stuff just as with other subdirs in /lib


-- 
Bazsi

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
Ok. At least all the compile test is green. The remaining to failed test is the coding style and the copyright check.
And of course, I have no idea if tgz2build is actually working or not. (Most probably not.)

What should be the next step? The style check can be fixed easily, seemingly mostly additional line-end white spaces. But what should I do with the copyright check? I do not want to change the copyright because I'm not the copyright holder. But I do not want to add the BSD license to the "approved" copyrights too.

**Comment by bazsi** [comment]
Hi,

Add it to the ignore list, the first chunk of tests/copyright/policy should
be that.

-- 
Bazsi

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
Done. Everything is green now.

**Comment by bazsi** [comment]
Thanks, let's wait with the 3.10 release, and once that's out, we can merge
this.

@lbudai, do you agree?

**Comment by bazsi** [comment]
Now with 3.10.1 out, let's merge this, as we are better off.

I do see a number of things can be improved, but that can be done even after this is in.

**Comment by bazsi** [comment]
Thanks for the contribution, with this in, probably with 3.11, we can eliminate libevtlog from distros.

**Comment by bazsi** [comment]
@czanik heads up because of the distro related change

**Pull request merged**
