### PR TITLE
F/list functions

### PR DESCRIPTION
**Pull request by bazsi**
This branch is based on f/kv-parser-refinements and is the same as the erroneously closed PR #1225 

The primary goal of this branch is to add $(list-XXX) template functions to manipulate lists.

Once #1271 goes in, this can go in second.

### CODE REVIEW

**Comment by bazsi** [comment]
rebased against master.

**Comment by bazsi** [comment]
The latest should fix the copyright/formatting issues, so once it is green it is good to review/merge.

**Comment by pzoleex** [comment]
kvformat: add support for extract-stray-words() option in kv-parser: This does not work for me.
Example (config below):
I send this line to syslog-ng (the important part is the ID=9434 DF):
Aug  4 13:23:00 centos kernel: IPTables-Dropped: IN=em1 OUT= MAC=a2:be:d2:ab:11:af:e2:f2:00:00 SRC=192.168.2.115 DST=192.168.1.23 LEN=52 TOS=0x00 PREC=0x00 TTL=127 **ID=9434 DF** PROTO=TCP SPT=58428 DPT=443 WINDOW=8192 RES=0x00 SYN URGP=0

output:
<13>1 2017-08-04T13:23:00+02:00 Thor-E5440 kernel - - [iptables IN="em1" OUT="" MAC="a2:be:d2:ab:11:af:e2:f2:00:00" SRC="192.168.2.115" DST="192.168.1.23" LEN="52" TOS="0x00" PREC="0x00" TTL="127" I**D="9434 DF"** PROTO="TCP" SPT="58428" DPT="443" WINDOW="8192" RES="0x00 SYN" URGP="0"][meta sequenceId="1"] stray: IPTables-Dropped:

I would expect this:
ID=9434
and DF should be in stray.

**problem2:**
I think prefix should be applied to the stray to instead of a global. For example, in that case, it should be: .SDATA.iptables.stray

**problem3:**
extract_stray_words_into('stray') -> this should be the default to be compatible with the earlier function.

syslog-ng.conf:
@version: 3.8
@module "kvformat"
options {
    threaded(yes);
};
source s_file_05ab58ce992c4fb188d8c853a20bde7c {
    file("/home/pzolee/var/testdb_working_dir/d216a80c-27fa-4982-97ed-74662854e128.txt");
};

parser p_kv_parser_95a93b020e594c44aff8f3eca1fd56cf {
    kv_parser(extract_stray_words_into('stray')
 prefix('.SDATA.iptables.'));
};

destination d_file_e4c9cec8e9b84f5c9d55c052e8d78144 {
    file("/home/pzolee/var/testdb_working_dir/da361850-ec09-4021-8e5b-44a5ed3ca99e.txt" flags(syslog-protocol) template("stray: ${stray}\n"));
};
log {
source(s_file_05ab58ce992c4fb188d8c853a20bde7c);
parser(p_kv_parser_95a93b020e594c44aff8f3eca1fd56cf);
destination(d_file_e4c9cec8e9b84f5c9d55c052e8d78144);

flags(flow-control);
};

**Comment by bazsi** [comment]
Hi,

Thanks for your feedback, please find my comments inline.


On Wed, Jan 18, 2017 at 10:14 AM, pzoleex <notifications@github.com> wrote:

> kvformat: add support for extract-stray-words() option in kv-parser: This
> does not work for me.
> Example (config below):
> I send this line to syslog-ng (the important part is the ID=9434 DF):
> Aug 4 13:23:00 centos kernel: IPTables-Dropped: IN=em1 OUT= MAC=a2:be:d2🆎11:af:e2:f2:00:00
> SRC=192.168.2.115 DST=192.168.1.23 LEN=52 TOS=0x00 PREC=0x00 TTL=127 *ID=9434
> DF* PROTO=TCP SPT=58428 DPT=443 WINDOW=8192 RES=0x00 SYN URGP=0
>

Well, the default behavior right now is to assume space does not terminate
the value, but rather it is concatenated to the last. If you specify
pair-separator(" ") it should work differently, as it would take space for
a separator, but could you doublecheck, if you have this environment,
please?

> output:
> <13>1 2017-08-04T13:23:00+02:00 Thor-E5440 kernel - - [iptables IN="em1"
> OUT="" MAC="a2:be:d2🆎11:af:e2:f2:00:00" SRC="192.168.2.115"
> DST="192.168.1.23" LEN="52" TOS="0x00" PREC="0x00" TTL="127" I*D="9434
> DF"* PROTO="TCP" SPT="58428" DPT="443" WINDOW="8192" RES="0x00 SYN"
> URGP="0"][meta sequenceId="1"] stray: IPTables-Dropped:
>
> I would expect this:
> ID=9434
> and DF should be in stray.
>
> *problem2:*
> I think prefix should be applied to the stray to instead of a global. For
> example, in that case, it should be: .SDATA.iptables.stray
>

I don't agree, I was using this first, however it should be quite common to
put the stray values in a "temporary" value, like $0, so that you can work
on it some more.

If prefix would be applied, you couldn't do that.


> *problem3:*
> extract_stray_words_into('stray') -> this should be the default to be
> compatible with the earlier function.
>

I don't understand this.

**Comment by pzoleex** [comment]
I changed to this:
parser p_kv_parser_41a584cd7839456a8dfd1970d6ed9dfc {
    kv_parser(extract_stray_words_into('stray')
 pair_separator(" ")
 prefix('.SDATA.iptables.'));
};

But the result is the same:
<13>1 2017-08-04T13:23:00+02:00 Thor-E5440 kernel - - [iptables IN="em1" OUT="" MAC="a2:be:d2:ab:11:af:e2:f2:00:00" SRC="192.168.2.115" DST="192.168.1.23" LEN="52" TOS="0x00" PREC="0x00" TTL="127" **ID="9434 DF"** PROTO="TCP"...

Anyway, the default separators are space and comma with space, isn't?

**Comment by pzoleex** [comment]
A quick fix is here

@@ -189,19 +189,24 @@ _match_delimiter(const gchar *cur, const gchar **new_cur, gpointer user_data)
   if (!self->value_was_quoted &&
       *cur == ' ')
     {
-      _skip_spaces(&cur);
-
-      if (_end_of_string(cur) ||
-          _key_follows(self, cur))
-        {
-          *new_cur = cur;
-          result = TRUE;
-        }
-      else if (_pair_separator(self, cur, new_cur))
+      if (strcmp(pair_separator, " ") == 0)
+        result = TRUE;
+      else
         {
-          result = TRUE;
-        }
+              _skip_spaces(&cur);
+
+              if (_end_of_string(cur) ||
+                  _key_follows(self, cur))
+                {
+                  *new_cur = cur;
+                  result = TRUE;
+                }
+              else if (_pair_separator(self, cur, new_cur))
+                {
+                  result = TRUE;
+                }
 
+        }
     }
   else if (*cur == ' ')
     {
diff --git a/modules/kvformat/tests/test_kv_scanner.c b/modules/kvformat/tests/test_kv_scanner.c
index 4a3fb7c..7d79f8d 100644
--- a/modules/kvformat/tests/test_kv_scanner.c
+++ b/modules/kvformat/tests/test_kv_scanner.c
@@ -550,6 +550,21 @@ Test(kv_scanner, pair_separator_causes_values_to_be_split_at_that_character)
   {"bar", "foo"});
 }
 
+Test(kv_scanner, pair_separator_space_causes_values_to_be_terminated_by_space)
+{
+  ScannerConfig config =
+  {
+    .kv_separator = '=',
+    .pair_separator = " ",
+  };
+
+  _EXPECT_KV_PAIRS_WITH_CONFIG(config, "foo=v1 v2 bar=v3 v4",
+  {"foo", "v1"},
+  {"bar", "v3"});
+}


problem2 and 3: ok

**Comment by bazsi** [comment]
btw, these issues are not related to this branch, but rather the already integrated #1271, but anyway fixes are coming on a separate pull request.

**Comment by bazsi** [comment]
I have now rebased this to current master.

**Comment by bazsi** [comment]
Ah, I've just noticed that this is not opened against master, so I am closing this and opening a new one against master.

**Pull request closed without merging**
