### PR TITLE
Centos6 support

### PR DESCRIPTION
**Pull request by bazsi**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@bazsi: I think we shouldn't use the deprecated `GStaticMutex` on those platforms where glib is newer.
Maybe we should implement a 'syslogmutex' and where `GStaticMutex` is deprecated we can provide a `GMutex` based implementation...

**Comment by bazsi** [comment]
Hi,

I think the code has a lot of gstaticmutex instances already.

I agree that the api of gmutex is nicer though.

Btw looking at the gmutex implementation, it is actually slower, using a
malloc() at first reference, so it might not even apply everywhere, even in
the long run.

Lets discuss this in person.

**Comment by czanik** [comment]
First I tried it as a simple patch, but it did not work, as the patch also changes configure.ac. CentOS 6 has automake 1.11 but as the tgz was created with 1.15 it was not good enough.

Next I patched git head and created a tgz myself. Compilation failed:

```
./lib/stats/stats-counter.h: In function 'stats_counter_add':
./lib/stats/stats-counter.h:41: warning: implicit declaration of function 'g_atomic_pointer_add'
  CC       lib/lib_libsyslog_ng_la-logwriter.lo
In file included from ./lib/stats/stats-cluster.h:27,
                 from lib/stats/stats.h:29,
                 from lib/cfg.h:37,
                 from lib/logpipe.h:30,
                 from lib/logwriter.h:28,
                 from lib/logwriter.c:25:
./lib/stats/stats-counter.h: In function 'stats_counter_add':
./lib/stats/stats-counter.h:41: warning: implicit declaration of function 'g_atomic_pointer_add'
  CC       lib/lib_libsyslog_ng_la-mainloop.lo
In file included from ./lib/stats/stats-cluster.h:27,
                 from lib/stats/stats.h:29,
                 from lib/cfg.h:37,
                 from lib/mainloop.c:29:
./lib/stats/stats-counter.h: In function 'stats_counter_add':
./lib/stats/stats-counter.h:41: warning: implicit declaration of function 'g_atomic_pointer_add'
lib/mainloop.c: At top level:
lib/mainloop.c:93: error: variable 'workers_running_lock' has initializer but incomplete type
lib/mainloop.c:93: warning: excess elements in struct initializer
lib/mainloop.c:93: warning: (near initialization for 'workers_running_lock')
lib/mainloop.c:93: error: extra brace group at end of initializer
lib/mainloop.c:93: error: (near initialization for 'workers_running_lock')
lib/mainloop.c:93: error: extra brace group at end of initializer
lib/mainloop.c:93: error: (near initialization for 'workers_running_lock')
lib/mainloop.c:93: warning: excess elements in struct initializer
lib/mainloop.c:93: warning: (near initialization for 'workers_running_lock')
lib/mainloop.c: In function 'block_till_workers_exit':
lib/mainloop.c:311: warning: implicit declaration of function 'g_cond_wait_until'
make[2]: *** [lib/lib_libsyslog_ng_la-mainloop.lo] Error 1
make[1]: *** [all-recursive] Error 1
```

**Comment by czanik** [comment]
OK. After a bit of spec file editing it compiles now. I still have to fix a few things in the file lists but hope to release a test RPM later this week.

@bazsi : this PR does not apply to the current master as mainloop was changed in the past few days.

**Comment by lbudai** [comment]
After the conflict is resolved, I think we can merge this as-is.

**Comment by lbudai** [comment]
@bazsi : I resolved the conflict, but need to force push this branch.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@bazsi: I had to add an extra patch... 
The `thread_halt_cond` is signalled from mainloop worker which is used by test_disqk, and some other tests, too.
I was thinking on where to move, finally I decided to call in `app_startup` (otherwise test writers would need to call this init function).

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
