### PR TITLE
Add contextual data make filters config plugin aware

### PR DESCRIPTION
**Pull request by bazsi**
the primary goal of this PR is this patch:

```
add-contextual-data: fix missing plugins in the filters configuration
    
It was reported by Mark Bonsack when using add-contextual-data() using the
filters() selector that the secondary configuration file misses all plugins
that the primary one has already loaded.
    
This patch makes this secondary config use the same set of plugins as the
primary one, eliminating the issue.
```

The branch also contains a plugin refactor (basically just moving code around and renaming stuff to make that uglyness somewhat nicer).

The fix relies on the concept of "subordinate" configurations, which by their definition share some things with the main config, this time the set of plugins available to it. Later, this could potentially be extended, but honestly I hope the entire filters() mode of add-contextual-data() can be eliminated completely.

### CODE REVIEW

**Comment by bazsi** [comment]
Here's the reported error message:
```
Error parsing filter expression, Error compiling template (Unknown template function "env") in /opt/syslog-ng/etc/context/filter_host.conf:4:35-4:65:
1       @version: 3.22
2       filter f_test_test {
3           host("testvp-*" type(glob))
4----->     or match("test_test" template("$(env SYSLOG_PRESUME_FILTER)") type(glob)); }
4----->                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
kudos to @kira-syslogng as it caught an actual bug.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by themrkeys** [comment]
Thank you

**Comment by MrAnno** [comment]
I'd like to add this PR to the v3.23 milestone.
Please remove the milestone, if anyone disagrees.

**Pull request merged**
