### PR TITLE
Adding Riak destination for Syslog-ng

### PR DESCRIPTION
**Pull request by hTrap**
This is the project I was working on during the gsoc2015 period.
Here is the wiki for the destination https://github.com/hTrap/syslog-ng/wiki/Riak-Destination
also the implementation steps/blogs are available at http://thetechtrap.com . Please do let me know of the suggested changes or the errors encountered (if any).
## 

Suggested operations before integrating this Pull Request:
- [x] Remove the generated grammar file (`modules/riak/.grammar.y`)
- [x] Remove the generated parser implementation (`modules/riak/riak-grammar.c`)
- [x] Remove the generated parser header file (`modules/riak/riak-grammar.h`)
- [x] Interactive rebase to the current master: part 1
- [x] Interactive rebase to the current master: part 2
- [ ] Remove the limitation of the concurrent jobs in `.travis.yml`
- [ ] for @dnsjts: finish this list

### CODE REVIEW

**Comment by lbudai** [comment]
Hi,
```
riak-grammar.y: In function â€˜riak_parseâ€™:
riak-grammar.y:405:5: warning: implicit declaration of function â€˜riak_dd_get_template_optionsâ€™ [-Wimplicit-function-declaration]
riak-grammar.y:405:29: warning: assignment makes pointer from integer without a cast [enabled by default]
  CC     modules/riak/modules_riak_libriak_la-riak.lo
In file included from ./modules/riak/libriack/lib/riack/riack.h:28:0,
                 from modules/riak/riak.c:12:
./modules/riak/libriack/lib/riack/client.h:30:38: fatal error: riack/proto/riak_kv.pb-c.h: No such file or directory
compilation terminated.
make[2]: *** [modules/riak/modules_riak_libriak_la-riak.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
travis_time:end:02c79d68:start=1439291749589126162,finish=1439291844119421313,duration=94530295
```

any update on this?

**Comment by hTrap** [comment]
This occurred while integrating the makefile, I did inform @algernon about it.

**Comment by algernon** [comment]
Thanks for the ping, I'll have a look at the branch in the next few days, if all goes well.

**Comment by hTrap** [comment]
@algernon @lbudai

**Comment by lbudai** [comment]
Hi @hTrap,

sorry for slow reaction :-(
We are going to start the review on _today_.
My plan is to integrate your PR during the next few weeks.

L.

**Comment by hTrap** [comment]
No problem @lbudai
Let me know if any changes have to be made.

**Comment by lbudai** [comment]
Could you rebase it to the current master?

**Comment by hTrap** [comment]
I tried to rebase it current master but I encountered several conflicts on
the Date module, I resolved all the conflicts of riak module which were
just in modules/Makefile.am
Should I force push to the PR ?

**Comment by dnsjts** [comment]
Iff the resolution is correct (i.e. the PR will contain only the intended changes), then feel free to force push.

**Comment by hTrap** [comment]
Thanks, Force pushed after rebasing to current master and resolving riak
module related conflicts.
Also fixed recent errors that occurred on Travis build regarding renaming
of variable names
VERSION AND SOURCE_REVISION
by prefixing SYSLOG_NG in both.

Travis build passing now

**Comment by dnsjts** [comment]
A TODO list should appear in the description of the PR.
If an item is completed, please commit it as a separate commit, because I really don't want you to lose your work because of some of my stupid ideas.

**Comment by hTrap** [comment]
@dnsjts , Thanks for the pointers, ^ commited each item seperately.

**Comment by dnsjts** [comment]
For the next suggestion you may want to keep a backup of the code, or at least double-check the diff, because this must not introduce new change in your PR.

Hopefully this reduces the number of commits, thus making the remaining more understandable.

Here are the suggested commands of the interactive rebase:
```
pick 4bd2a0b Add the Initial code for Riak Module
pick 3dc1b06 Remove glib functions
pick 90c169c Update example configuration
squash f2e8283 Fixing typo
squash 4f435b5 Fixing Errors
squash adb2f6a removing system() from config source
squash 5317b09 FIX: the LogTemplate of value in the config enclosed in  representing the template function call
pick 595a12d Add header file for the riak parsing functions
pick 3dc2e51 Add configure & automake magic to support compiling the Riak destination
squash 46c0c1c fixed missing quotes
squash 6a23918 fixed missing quotes
squash 8b620f9 Adding automake for the riack library to work with the riack module
squash 2b74012 fixing automake and debug flags
squash b16fdef fixing rebase issues
pick 48abec2 Fixing usage of gboolean, including stdlib, fixing a few errors
pick 7aba968 Adding worker threads' functions (init, deinit, insert)
pick b4436d9 Fixing client errors and changing source to a local port
pick 08a4a6c Adding \n at in debugging statement for it to be flushed
pick e1d6f75 Add support for charset and content-type as suboptions under value option in the syslog-ng.conf
pick 439399e setting up client and adding worker thread insert function to fill the logTemplate data
pick 9565970 fixing typo
pick 84706ed FIX: for linking the riack library
squash 493c0e2 FIX: To detect the riack library without explicit location
pick db77fc3 WIP:filling the LogTemplates
pick e3f81df sending messages to riak using the riack library
pick 25ce6a7 change in client send call and use of riack_message_t
pick f2d6372 renaming ctype to content_type for better readability
pick 719b20d Adding the set mode fuctionality of the Riack library to the syslog-ng riak module
pick 98fba9e bug fix: typo
pick 367f04d Adding the use of optional keys in set mode
pick df8c90f adding feature for flush lines in set mode
pick f085f0a Making libriack a part of the riak module in syslog-ng for ease of development
pick 5a25b9e Fixes for libriack as a snippet library in syslog-ng
pick 9566d3b libriack embedding fixes
pick d12f158 riak/libriack: Fix setop->adds allocation
pick 1d67a0f fixing tests
pick c09331f cleaning up code indentation
pick 180a472 fixing bulk mode iterations
pick 20a6d77 wip: bulk update set fixes
pick 73e76ff Fixed bulk addition of messages in set mode
pick e84d100 fixing memory leaks
pick 9536766 fixing client_connect memory leaks
pick 97d3521 client: making client_connect arguments override the default arguments so that all combinations of addresses can be reached
pick 8715d4d optimizing code so that client_connect is not called on every message, also fixing double free and port conversion to string errors
pick 626cc64 Adding the riak protocol files
pick 875e904 Adding protocol file
pick eb4f7e7 Add protobuf libraries for installation in travis build
pick 78b5240 adding configure.ac from the riack library to satisfy the distdir rule
pick 8e6fdf5 fixing implicit declaration warning
fixup d16f7c7 Removing generated grammar file(modules/riak/riak-grammar.y)
fixup 4734c15 Removing generated parser implementation (modules/riak/riak-grammar.c)
pick 441fa29 renaming VERSION to SYSLOG_NG_VERSION and SOURCE_REVISION to SYSLOG_NG_SOURCE_REVISION
pick bc84de1 Removing generated parser header file (modules/riak/riak-grammar.h)

# Rebase 453e416..bc84de1 onto 453e416 (53 command(s))
```

**Comment by hTrap** [comment]
@dnsjts ^ no changes in diff, fixed couple of conflicts.

**Comment by dnsjts** [comment]
(Don't forget to rebase to the `balabit/master` since the master was broken for days.)
Next rebase suggestion (also, the diff should be unchanged):
```
pick 4bd2a0be92044d527b6921f1909baa960702f054 Add the Initial code for Riak Module
fixup b0dbbd6ca2b858a5b084e5dfba3e45e3852e91b2 renaming VERSION to SYSLOG_NG_VERSION and SOURCE_REVISION to SYSLOG_NG_SOURCE_REVISION
pick 3dc1b0654866852c99b3cd521ee3adba4de2465a Remove glib functions
pick 2f64dc86d33d1885b51b7742bf9b2d4901fa8933 Update example configuration
pick 208e1bb5f81c07d666d65ef29ffc14ac28f878ad Add header file for the riak parsing functions
pick 725c357330e49b0bb1909fb367c2e532f9148b79 Add configure & automake magic to support compiling the Riak destination and commit squashes
pick 60e515fa9a1a8ad2a054d212ccf5f3393fa55643 Fixing usage of gboolean, including stdlib, fixing a few errors
pick b4f793a92970e132d5df394e834eb11b1175efeb Adding worker threads' functions (init, deinit, insert)
pick c3d7e1ed758b411f150dc2895ec984d6d3444a3e Fixing client errors and changing source to a local port
fixup 3240581b639d3888767858e0bf52f091475de3c0 Adding \n at in debugging statement for it to be flushed
pick 2bcc2ed9aa0cbd759b0aeb2e8056ee289c262c43 Add support for charset and content-type as suboptions under value option in the syslog-ng.conf
pick e06242ec36b38c4433c948fd3559cde00faccae4 setting up client and adding worker thread insert function to fill the logTemplate data
pick 5adef9c38334ba68d5b9e4dd8689e711c54626c3 fixing typo
pick 0ffd2ec9979c00db21acb8b6e3211ae0e96ca9a2 FIX: for linking the riack library
pick 85a7901cbd50cb8fb4e7acd0c0359cba4d98096a WIP:filling the LogTemplates
pick c3f7cd35f1f7d175d1e8b9172dae9ce080beb062 sending messages to riak using the riack library
fixup 901213e63c800978ed763adb4077ec0fec781a84 change in client send call and use of riack_message_t
pick d2e19481cb8467ccafc7accbd2e449144591973b renaming ctype to content_type for better readability
pick 48f5ab7f40ba705c80545751e7ffc81477aeff0f Adding the set mode fuctionality of the Riack library to the syslog-ng riak module
fixup 42e069b6e53ca6d5b388b37f818539d212f527fb bug fix: typo
pick 25145653c8854ead788e8f4b9d848a4dcfd6a1fb Adding the use of optional keys in set mode
pick 5bcfb940d014c29f82037227d8aad8cbd86c8556 adding feature for flush lines in set mode
pick 0000816d0d5e3de484e3cc9bc8a2f75e26ca8ade Making libriack a part of the riak module in syslog-ng for ease of development
pick 4e76eb5ea7e8ac0e3883a73d523b5e383ec44b5c Fixes for libriack as a snippet library in syslog-ng
pick c36dc1e77d7d91e569ee94cac3ab78c8029bb8eb libriack embedding fixes
pick 1621d779531de8746317b0ef7681ba0f888f44b1 riak/libriack: Fix setop->adds allocation
pick 37e2a6247c7b29b8899eadc188b77a8530d2334d fixing tests
pick 71bba2f7e409fc61a0de1ee47da0c6ad6f595dda cleaning up code indentation
pick 91fb3485ad392032a470b2834df48855cda5ec4c fixing bulk mode iterations
pick 501c54f9eb1ca25eba13a2e640f7de94f1fffdc0 wip: bulk update set fixes
pick 079d2ce955731f465224f0bf946c2a9ebdf21745 Fixed bulk addition of messages in set mode
pick 1da9dbe0d6e12d41441502fb6c6621fd0e9d9964 fixing memory leaks
pick 9e2fbac38dd6f991f8c168a0aa66a4483843db96 fixing client_connect memory leaks
pick e1f78a9c840739697a13364a8541007ed32057de client: making client_connect arguments override the default arguments so that all combinations of addresses can be reached
pick 30f5a91b93b6a92009ab25911a44cd4a88923705 optimizing code so that client_connect is not called on every message, also fixing double free and port conversion to string errors
pick 4f81f1b86b71a59ac41f3ebd548e71b0d524eda6 Adding the riak protocol files
pick 8a51a9c8076f71ee3a25282b5225a82f2058d2c2 Adding protocol file
pick e197da8f4c935286fd83db04e98ce3e7a6c3ae68 Add protobuf libraries for installation in travis build
pick c00d7069b5391a7d03a27b12da5d09668a0d14a4 adding configure.ac from the riack library to satisfy the distdir rule
pick d4af84e7ffcf4f868f710eee3f3c9c211368baa6 fixing implicit declaration warning
fixup 6612aa87da000cabc82b6a44064898ef1b2e3127 Removing generated parser header file (modules/riak/riak-grammar.h)
```

Sorry for the small steps, I can't oversee this many commits effectively.

**Comment by hTrap** [comment]
@dnsjts ^ no problem, no conflicts, no diff change

**Comment by dnsjts** [comment]
Could you drop 28f53fcdbdd95188819612621485bcb5d3c17b00 and 558757549b77d711f9b1d2ab69ecd79459d134bb?
I think these commits contain generated files by protobuf-c.

Also, please rebase to the master and resolve the conflicts.

**Comment by dnsjts** [comment]
Ugh. I am beginning to understand what is happening.
While I'm fixing the `./autogen.sh` and the configuration/compilation process, please
try to understand how is a module being built, which has an external library, e.g. `modules/afamqp/(rabbitmq-c)`.
After that you can verify the fix, too.

**Comment by dnsjts** [comment]
Done, please provide collaborator level access to your fork.

**Comment by hTrap** [comment]
Initially the plan was to create an external library algernon/riack  but
the library was small enough to be included with the destination.

**Comment by dnsjts** [comment]
I see, and we have to go back to that initial plan, because I don't think we have the capacity of maintaining a brand new library.
Hopefully these new commits solve this issue, please review them.

**Comment by dnsjts** [comment]
Finally works on travis, too, however the number of concurrent jobs had to be limited.

**Comment by hTrap** [comment]
Why is this happening, is it to be handled by the library?? I am sorry for the delay as I have examinations going on, I will review the changes this weekend for sure.

**Comment by hTrap** [comment]
The external library is working fine, it passes all the tests. Also no problems in the changes you made. I still didn't get that why the number of concurrent jobs have to be limited when using the library externally

**Comment by dnsjts** [comment]
I think I couldn't describe the build dependencies as I wanted.
However, our primary concern should be reducing the code as much as possible, and after that, we can work on this issue again.

**Comment by hTrap** [comment]
@dnsjts can you suggest the steps that have to be taken from my end to close this PR?

**Comment by algernon** [comment]
The library is not likely to be used by anything else than syslog-ng. It supports what the destination needs, and not more. It is kind of like the STOMP stuff. While the initial idea of an external library sounded good on paper, it turned out to be an exercise in futility.

By embedding the library, and possibly changing this whole module to use it as additional source, not a separate library - again, see the STOMP module -, you won't have to maintain an extra library. It just part of the source code for the riak syslog-ng module, no different than any other part of it.

I strongly suggest reconsidering the approach, and embedding the library sources instead of trying to force it outside.

**Comment by dnsjts** [comment]
Rebased to e851a4e85, please recheck the resolution of the conflict.
The difference of these commands should be minimal, and must not introduce any change in the riak functionality:
`git diff 042f7e4^ 29b725a` and `git diff e851a4e85 9ff6e876`.

In the meantime the approach of the riack library will be reconsidered.

**Comment by hTrap** [comment]
```
042f7e4^ 
```
^this is not in the working tree,
also I cannot find any conflicts while rebasing this branch to  e851a4e.
and git diff e851a4e 9ff6e87 is minimal to riak

**Comment by dnsjts** [comment]
I have run a beautifier on some part of code and modified some commits.
(The beautified code conforms better with our coding style, however it is far from perfection; I am still experimenting with the automated beautification.)

If you accept the changes, please reset your pull request to the commitid (also, please revoke my access to your repository, requesting access wasn't my best idea).

My `f/riaktest` can be found here:
https://github.com/dnsjts/syslog-ng/commit/03c6aaabb6305ad6d4bbb145e28ec0c751713906

So `git diff 03c6aaa 9ff6e876e` should contain only whitespace changes.
The thorough check is highly recommended, because once the `clang-format` sneakily introduced errors.

**Comment by hTrap** [comment]
@dnsjts I looked through your branch, but the commits you have made are making changes that are already there in this PR. If you could just tell me what to do, I could fix it in the PR itself.

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
I do not see this one to be merged. There are couple of reason for that. The main reason is that riak itself seems to be an abandoned project. That should be enough, but also I have not seen a c client for riak that have been maintained, or released in years or at least once.

**Pull request closed without merging**
