### PR TITLE
redis: Return error result when redis command is failed

### LINKED ISSUE #754: sigsegv in redis module when restart redis server
config:
@version: 3.7

options {
	flush_lines (0);
	time_reopen (10);
	log_fifo_size (1000);
	chain_hostnames (off);
	use_dns (no);
	use_fqdn (no);
	create_dirs (no);
	keep_hostname (yes);
};

destination d_redis {
	redis (
	host("localhost")
	port(6379)
	command("LPUSH", "pixel", "${MSG}"));
};

source s_nginx_20 { 
	file(
		"var/source/access.log" 
		follow-freq(5)
		program_override("nginx-access-log")
	); 
};

filter f_nginx_20 { 
	match("nginx-access-log" value("PROGRAM")); 
};

log { 
	source(s_nginx_20); 
	filter(f_nginx_20); 
	destination(d_redis);
};

reproduction:
just restart redis server 4-5 times while syslog-ng is sending logs to resdis

valgrind output:
==00:00:33:46.611 26449== Thread 2:
==00:00:33:46.611 26449== Invalid read of size 4
==00:00:33:46.611 26449==    at 0x7D327E9: freeReplyObject (in /usr/lib/libhiredis.so.0.10)
==00:00:33:46.611 26449==    by 0x7B25532: redis_worker_insert (redis.c:235)
==00:00:33:46.611 26449==    by 0x4E8E014: log_threaded_dest_driver_do_insert (logthrdestdrv.c:154)
==00:00:33:46.611 26449==    by 0x4E8E472: log_threaded_dest_driver_do_work (logthrdestdrv.c:226)
==00:00:33:46.611 26449==    by 0x4EFCF81: iv_run_tasks (in /home/deirf/zwa/projects/syslog-ng-ose/install/lib/libsyslog-ng-3.7.so.0.0.0)
==00:00:33:46.611 26449==    by 0x4F0011E: iv_main (in /home/deirf/zwa/projects/syslog-ng-ose/install/lib/libsyslog-ng-3.7.so.0.0.0)
==00:00:33:46.611 26449==    by 0x4E8E905: log_threaded_dest_driver_worker_thread_main (logthrdestdrv.c:286)
==00:00:33:46.611 26449==    by 0x4E98ABD: _worker_thread_func (mainloop-worker.c:288)
==00:00:33:46.611 26449==    by 0x51DD9B4: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.3200.4)
==00:00:33:46.611 26449==    by 0x5470E99: start_thread (pthread_create.c:308)
==00:00:33:46.611 26449==    by 0x577938C: clone (clone.S:112)
==00:00:33:46.611 26449==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==00:00:33:46.611 26449==
==00:00:33:46.611 26449==
==00:00:33:46.611 26449== Process terminating with default action of signal 11 (SIGSEGV)
==00:00:33:46.611 26449==  Access not within mapped region at address 0x0
==00:00:33:46.611 26449==    at 0x7D327E9: freeReplyObject (in /usr/lib/libhiredis.so.0.10)
==00:00:33:46.611 26449==    by 0x7B25532: redis_worker_insert (redis.c:235)
==00:00:33:46.611 26449==    by 0x4E8E014: log_threaded_dest_driver_do_insert (logthrdestdrv.c:154)
==00:00:33:46.611 26449==    by 0x4E8E472: log_threaded_dest_driver_do_work (logthrdestdrv.c:226)
==00:00:33:46.611 26449==    by 0x4EFCF81: iv_run_tasks (in /home/deirf/zwa/projects/syslog-ng-ose/install/lib/libsyslog-ng-3.7.so.0.0.0)
==00:00:33:46.611 26449==    by 0x4F0011E: iv_main (in /home/deirf/zwa/projects/syslog-ng-ose/install/lib/libsyslog-ng-3.7.so.0.0.0)
==00:00:33:46.611 26449==    by 0x4E8E905: log_threaded_dest_driver_worker_thread_main (logthrdestdrv.c:286)
==00:00:33:46.611 26449==    by 0x4E98ABD: _worker_thread_func (mainloop-worker.c:288)
==00:00:33:46.611 26449==    by 0x51DD9B4: ??? (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.3200.4)
==00:00:33:46.611 26449==    by 0x5470E99: start_thread (pthread_create.c:308)
==00:00:33:46.611 26449==    by 0x577938C: clone (clone.S:112)
==00:00:33:46.611 26449==  If you believe this happened as a result of a stack
==00:00:33:46.611 26449==  overflow in your program's main thread (unlikely but
==00:00:33:46.611 26449==  possible), you can try to increase the size of the
==00:00:33:46.611 26449==  main thread stack using the --main-stacksize= flag.
==00:00:33:46.611 26449==  The main thread stack size used in this run was 8388608.

### PR DESCRIPTION
**Pull request by deirf**
Fix a SIGSEGV when redis result of command return an error.
Fixes #754

Signed-off-by: Fried Zoltan <zoltan.fried@balabit.com>

### CODE REVIEW

**Comment by deirf** [comment]
#754

**Comment by bkil-syslogng** [comment]
:+1:

**Comment by ihrwein** [comment]
Please update the PR's description with the following text so it will close the issue automatically 
```
Fixes #754
```

Otherwise :+1:

**Comment by bkil-syslogng** [comment]
A null propagation contract through automated correctness verification would have probably caught this.

**Pull request merged**
