### PR TITLE
riemann crashes in flush

### PR DESCRIPTION
**Pull request by Kokan**
I am just stealing a patch from #2291 which fixes a riemann issue caused by #2098 so it could go in faster.

### CODE REVIEW

**Comment by bazsi** [comment]
It's good for me, obviously I am the original author, but I think we can warrant one approver in your name, as you seem to agree with the patch :)

**Comment by Kokan** [comment]
@bazsi I just need to check one thing pointed out by @furiel

**Comment by bazsi** [comment]
I think right now <=1 means no batching.

**Comment by furiel** [comment]
@bazsi @Kokan unfortunately there is still an invalid memory access. The problem comes when flush-lines is not specified:
```
destination d_riemann {
    riemann(description($MESSAGE)
    port(5555)
#    flush-lines(0)
    server("localhost"));
};
```

In that case, after the MAX calculation, there will be only room for one event after the malloc. Though batching is disabled now, and in that case logthrdestrv will send every message she can at the read loop to riemann, that means more than one events will be appended to a fix size array.

You can reliably reproduce with an stdin source:
```(echo "line1\nline2\nline3\n"; sleep 5) | valgrind ./syslog-ng -Fe -f ../etc/riemann.conf```

Now `riemann_worker_insert` can only return with QUEUED after inserting a single message, meaning riemann does not support non-batching mode now. Maybe this is where the problem comes from.

**Comment by bazsi** [comment]
Apart from a small change to use the log_threaded_dest_driver_flush() flush wrapper, this still looks good to me.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
