### PR TITLE
Read old records

### PR DESCRIPTION
**Pull request by lbudai**
This PR supports `read_old_records` only for journal source.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mochrul** [comment]
(slight off topic)Hmm. I "received" similar complaint from the ubuntu, that sometimes the build is hung around the python tests (https://ubuntudiff.debian.net/q/package/syslog-ng). It may worth an issue.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
Now, read-old-records implemented also for file-reader.
(this is not a port from pe, I've re-implemented this feature)

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@furiel: thanks for the review note.
I wouldn't change the code because we would set `read_old_records` to OFF only when there is no existing persist state in the persist file: in this case we would need to override the `read_old_records` value in the options structure... and I think it is not as readable as the current version (it is possible to find a better name than `new_state`, but I don't have such a name at this time).

The key point here is that we applying an existing state or a new one: when existing one is applied then we continue to read logs from the position stored in the persist file, otherwise
the user can set the start position: head(`read_old_records=yes`) or tail(`read_old_records=no`).
When the user does not set this value, the default is `yes`.

**Comment by lbudai** [comment]
Hmm...the affile read-old-records will be handled in a separate PR as it needs some change in functionality.
But systemd-journal part of the PR can be merged.

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-journal-source-read-old-record;

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: pzolee-journal-source-read-old-record and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-journal-source-read-old-record;

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: pzolee-journal-source-read-old-record and test suite: functions

**Pull request merged**
