### PR TITLE
C style checker

### PR DESCRIPTION
**Pull request by kvch**
This PR introduces style checking of C source files. Also contains the formatted sources.

New make targets were added: `style-check`, `style-format` The first checks the sources and the second formats them. Astyle 2.05.1 is needed to get the required format. If you don't want to use make, the script is available under `scripts` folder.

The coding standard is similar to our current style. The only difference is the maximum of the length of lines is 120 chars.

### CODE REVIEW

**Comment by bazsi** [comment]
The only thing I don't really like is the indentation of "case" labels
within switch. Those behave a lot like goto and that's why it is not
indented in, at least in GNU coding standards.

Can we reconfigure that part? Please? It should be the --indent-switches
option that we should remove.

thanks

-- 
Bazsi

**Comment by kvch** [comment]
@bazsi I made a mistake. My original intention was not to interfere with switches, I just simply forgot to remove this line after I realized that this convention is followed. Thanks for pointing this out. :) I fixed the issue and I will rebase again.

**Comment by lbudai** [comment]
@kvch : I think the conflict is my mistake, sorry for that.
( I merged another PR...  )

**Comment by kvch** [comment]
@lbudai i guess i will rebase before it is merged. :)

**Comment by bazsi** [comment]
Hi,

Thanks for your efforts anyway, having a tool to validate this is great, I
am hopeful that the tool will be good enough.

-- 
Bazsi

**Comment by bazsi** [comment]
It might be easier to back out the changes and re-merge it afterwards. Just
a thought.

-- 
Bazsi

**Comment by lbudai** [comment]
Thanks!

**Pull request merged**
