### PR TITLE
bugfix (fixes #1570): use sd_journald_test_cursor() from systemd-jour…

### LINKED ISSUE #1570: Possible loss of log messages when syslog-ng.persist file has cursor "in the future".
## Issue

**Description**
When syslog-ng checks cursor position from syslog-ng.persist file it does not check if saved cursor is "in the future" with respect to the system (i.e. time in the cursor is in the future with the respect to the system time). This causes logging glitch when syslog-ng is started (syslog-ng waits for the "time to come" to continue logging) when there is no systemd journal entries with the given "future time" or later. This is because sd_journald_seek_cursors() seeks to the next closest entry (in terms of time) if no entry matches.

**Possible fix**
Use sd_journal_test_cursor() to test the validity of the cursor.

**Side note**
This issue won't occur normally unless someone or something mess up with system time and systemd journal. Consider following example, how one can reproduce this bug:
1. stop syslog-ng and systemd-journald services
2. cleanup/remove journal logs
3. set the time in some past with respect to given time
4. reboot machine

## Version of syslog-ng

3.10.0

## Platform

linux debian

### PR DESCRIPTION
**Pull request by lbudai**
…nal API for additional cursor test in syslog-ng.presit file

short bug description: when syslog-ng checks cursor position from
syslog-ng.persist file it does not check if cursor is "in the future" with
respect to the system.  This causes logging glitch when syslog-ng is started
(syslog-ng waits for the "time to come" to continue logging) when there is no
systemd journal entries with the "future time". This is because
sd_journald_seek_cursor() seeks to the next closest entry (in terms of time)
if no entry matches.

reopen PR #1571  (it has been reverted as it caused some problems, see #1587 )
(reopen #1570)

### CODE REVIEW

**Comment by lbudai** [comment]
@kira-syslogng test this please test branch=pzolee-enable-journal-tests;

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: pzolee-enable-journal-tests and test suite: functions

**Comment by pzoleex** [comment]
@kira-syslogng test this please

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
I'm closing this...

**Comment by faithlesstomas** [comment]
Can you tel me why this issue have been closed, and bugfix removed eventualy from the code? 
Is there any other fix for this?

For me this problem still seems to be potentially quite dangerous... see e.g. discussion with Lennart Poettering about this: https://github.com/systemd/systemd/issues/6213.

**Comment by lbudai** [comment]
@faithlesstomas : this is the PR, not the issue... but I think I answered your question: even if the bug is dangerous, the patch itself is also dangerous... as  it caused segfault on some systems. 
I marked the PR as [WIP] , won't close it, but it's not ready to merge.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by faithlesstomas** [comment]
OK, I see, thank you! 
Is it possible, by any chance, that someone will revise this patch
and/or figure out better solution if this one cause that much trouble?

**Comment by lbudai** [comment]
@faithlesstomas : yes, that's the plan. I hope that next release will contain the fix.

**Comment by lbudai** [comment]
@faithlesstomas : could you test my latest changes?

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by MrAnno** [comment]
So after calling `sd_journal_seek_cursor`, `sd_journal_next` sets the position which makes it possible to use `sd_journal_test_cursor` correctly.

That's fine, but it is possible that we lose a message because `_fetch_log()` calls `sd_journal_next()` again right after `_seek_to_saved_state()`?

**Pull request merged**
