### PR TITLE
Functional test framework

### PR DESCRIPTION
**Pull request by mitzkia**
The following patch set will provide a new python based functional test framework. 
In a long term it wanted to replace the previous python based functional tests (tests/functional/). 
A Readme.md file will contains a detail description of the framework.

### CODE REVIEW

**Comment by mitzkia** [comment]
I know about the Travis failing, I will correct the copyright failings.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by pzoleex** [comment]
Just a few notes at first glance:
psutil is missing from dependencies

the unit test expects installed syslog-ng and valgrind. They should be mocked.

**Comment by pzoleex** [comment]
and tristam hostname is burned in the unit tests that cause fails on other hosts :)

**Comment by mitzkia** [comment]
@pzoleex  Thanks, for the review notes. I will fix them soon. 

About the whole test framework: 
 * The API how test cases should look like is under internal discussion. 
 * After it was discussed and we have consensus I will update this PR

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by mitzkia** [comment]
I am closing this PR now. 
I will open a new one soon.

**Pull request closed without merging**
