### PR TITLE
[WIP] Increase the default value of log-fetch-limit() to 100

### PR DESCRIPTION
**Pull request by MrAnno**

### CODE REVIEW

**Comment by MrAnno** [comment]
@kira-syslogng do perftest

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@pzoleex Help me please, what happened here? :smiley:

**Comment by pzoleex** [comment]
Memory usage was doubled. I don't know if increasing log fetch limit can cause such a high memory usage, we should investigate if this is normal or a possible leak.

**Comment by lbudai** [comment]
@MrAnno: why would we need to increase this limit?

**Comment by MrAnno** [comment]
We've measured previously that this increases the performance of the wildcard file source, so an internal issue has been created to change the default.

**Comment by MrAnno** [comment]
Just a note:
The documentation is currently incorrect: it says the default is already 100.

**Comment by MrAnno** [comment]
Outdated.

**Pull request closed without merging**
