### PR TITLE
File source dont change perms by default

### PR DESCRIPTION
**Pull request by bazsi**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE, the tests were executed on test branch: master and test suite: functions

**Comment by furiel** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE, $TEST_DESC_COMMENT

**Comment by mitzkia** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
