### PR TITLE
RPM:  Add feature flags for Java and DBI components

### PR DESCRIPTION
**Pull request by duckfez**
Fix for https://github.com/balabit/syslog-ng/issues/2713

Signed-off-by: Duane Waddle <duane.waddle@defpoint.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
"add to whitelist" add author of a Pull Request to whitelist (globally, be careful, it means this user can trigger kira for any PR)
do nothing -> CI won't start)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
Thank you for the PR! I agree it is a reasonable request to be able to install syslog-ng with partial features. I am just not sure if this is the right approach.

With deb packaging, we build all available features of syslog-ng, but the individual parts are separated into different packages, like syslog-ng-core, and syslog-ng-mod-java, etc. This way, users can install the full feature set, but they can also use a subset by selectively installing packages.

The best would be if there were similar packages for rpm as in case of the debian packages. We already provide a convenient way to generate rpm (`$ dbld/rules rpm`), that will start an environment with every dependency available, and generate a monolithic package. The same command could generate individual packages too, which would support your use case.

I think the upstream should contain an rpm spec file that is best for general usage. The proposed approach is more like a specialization for an environment, and with that a wrong direction of dependency appears: the general solution depends on a specialization. So I would not merge the proposed version as it is.

**Comment by duckfez** [comment]
The current-in-master RPM spec file does make the different packages already.  Or, at least the one I patched does.  (Is there a different spec file that `dbld/rules` uses?)  So in general, the ability to install specific sub-components was already there.  What I added was the ability to pick whether some sub-components are actually built at build-time.  

The whole PR began in our environment as basically, "I don't need the java stuff, and things like the Gradle build dependency is a pain in the neck so I'd rather just not even try to compile it!"

What I did is really a half-measure only dealing with the DBI and Java sub-packages.  But, I think making all of the other optional components changeable via build-time feature flags would be further in the direction you don't want to go.

**Comment by furiel** [comment]
You are right. Overlook from my side. The current rpm spec file is not monolithic. Also, the current spec file already contains an `0%{?rhel}` compile switch in similar fashion. The purpose is similar: on some platforms the current spec file does not want to bother bringing dependencies. Compared to the rhel macro, your version with the per-package excludes feels cleaner. In short, I am convinced.

Let me tag @czanik for review and opinion, as he is also using these same spec files.

PS: I just tried dbld/rules rpm, and it is currently broken unfortunately. I will open an issue for it.

**Comment by bazsi** [comment]
I agree with the intention too. As I see, rpm has conditional builds supported: https://rpm.org/user_doc/conditional_builds.html

May I ask why are you not using that feature?

Thanks

**Comment by duckfez** [comment]
> May I ask why are you not using that feature?

@bazsi I had no idea that feature existed.  Assuming it's available in older versions of RPM, this is clearly a much better approach.  I will rework my patch to use this.  How old of an RPM-based distro do you think is reasonable to support?   My personal interests are only in Centos 7 and up, but am willing to test with an older version of RPM if you want.

**Comment by Kokan** [comment]
@duckfez I think centos:6 as of now is reasonable. (at least till 2020 something)

So please test it with centos:6 as well.

**Comment by bazsi** [comment]
in the meantime i worked on this on the dbld-kira-build branch, its also
opened as a pull request.

I covered Java and libdbi myself, so at this point I don't think there's
anything else left to do, apart from testing.

I am not yet finished with the branch, but centos-7 should work just fine.

**Comment by duckfez** [comment]
@bazsi so should I abandon work on this then?

**Comment by bazsi** [comment]
Yes, I think the changes in #2724 will resolve your problem as well. I have the following build options:

%bcond_with python3
%bcond_without python2
%bcond_without sql
%bcond_without mongodb
%bcond_without systemd
%bcond_without redis
%bcond_without riemann
%bcond_without maxminddb
%bcond_without amqp
%bcond_without java
%bcond_without kafka
%bcond_without snmpdest

by default we'd try to compile all this optional features, but you can disable them using the `--without <whatever>` option to rpmbuild.

**Pull request closed without merging**
