### PR TITLE
F/java scls

### PR DESCRIPTION
**Pull request by ihrwein**
This PR contains wrappers for the following Java destinations:
* HDFS
* Elastic
* Kafka

Some additional tweaking were also needed to handle the case when the default value in the block definition is the empty string. If `B`'s value in an `option(A, B)` parameter is the empty string then we handle it as this `option` actually wasn't specified.

# Example configurations

## HDFS
```
destination d_hdfs {
    hdfs(
        client_lib_dir(/root/hdfs-libs/lib)
        hdfs_archive_dir("")
        hdfs_file("/workdir/file.txt")
        hdfs_uri("hdfs://10.0.0.1:8020")
        template("$MSG\n")
    );
};
```

## Elastic

```
destination d_elastic {
    elasticsearch(
        client_lib_dir(/root/elastic-libs/lib)
        client_mode("transport")
        cluster("elasticsearch-syslog-ng-test")
        index("index")
        port("9300")
        server("10.0.0.1")
        type("slng_test_type")
    );
};
```

## Kafka

```
destination d_kafka {
    kafka(
        client_lib_dir(/root/kafka-libs/lib)
        kafka_bootstrap_servers("10.0.0.1:9093")
        topic("topic")
    );
};
```

### CODE REVIEW

**Comment by ihrwein** [comment]
@faxm0dem IMHO you will like this :)

**Comment by faxm0dem** [comment]
Awesome!
I don't think type and index should default to nil, as they are required parameters for ES. Let's default them both to `syslog-ng`.
Also,  can I pass `time-zone('UTC')` in `VARARGS`?

**Comment by juhaszviktor** [comment]
@faxmodem: yes you can pass anything in VARARGS even the time-zone('UTC')

index and type are required but if they are remain nil the syslog-ng won't
start because of missing required option(s).

**Comment by faxm0dem** [comment]
all right! what about `client_libdir`?

**Comment by ihrwein** [comment]
It should contain the directory where your `*.jar` files are. So if you have:
```
/tmp/a$ ls
a.jar  b.jar  c.jar
```

Then `client_libdir` should be `client_libdir(/tmp/a)`. The `/*.jar` will be automagically appended to it and inserted into the class path.

**Comment by faxm0dem** [comment]
Yes of course. I was asking what happens if it is left out

**Comment by ihrwein** [comment]
I think syslog-ng will load the `*.jar` files from `/`...

@juhaszviktor what do you think? Maybe we need to remove those `client_library` defaults.

**Comment by lbudai** [comment]
@ihrwein: for kafka, hdfs and elasticsearch won't work if the client lib jars are not available, and, IMHO, we cannot set a good default value for `client_library`.

**Comment by juhaszviktor** [comment]
+1
We can't remove hose client_library defaults, because if the client_library
doesn't exist in the block's parameters it will be handled as a VARARGS,
won't it?

**Comment by ihrwein** [comment]
It will. An other option would be to make `client_option` as a real parameter of the Java destinations and they would append its value of the "effective" classpath. This sounds hackish to me.

**Comment by bazsi** [comment]
I like this stuff a lot. There are two open questions:

1) Whether scls should be separated (I think yes)
2) whether we can provide defaults for client-lib-dir()

The defaults could be as simple as finding the proper party for a popular distribution (debian?), and provide an easy means to customize it on a per distribution (eg. Distro specific define files that can be customized at package build time). Once this is in place we can rely on contributors to fix up the paths for popular distros.

**Comment by faxm0dem** [comment]
FYI  elastic.co provide debs and rpms on their website, but debian has its own package with different paths

**Comment by ihrwein** [comment]
What if the default value is like `client_libdir(KAFKA_CLIENT_LIBDIR)`. This `KAFKA_CLIENT_LIBDIR` is an environment variable and is set by the init scripts.

**Comment by faxm0dem** [comment]
interesting idea
IIRC there's no `configure` switch yet which could set this, right?

**Comment by ihrwein** [comment]
I think we don't have an option for it. This heavily depends on the distros: we have to put those variables in the configure script in different files based on the distro/init system.

**Comment by ihrwein** [comment]
@bazsi The PR is updated:
* SCLs are separated
* missing license header is added
* `message_template()` is renamed to `template`

We couldn't decide what should we do with `client_lib_dir()`. 

I didn't squash the changes, because I need the commits for backporting. (I'll squash the old fixup commits as well).

**Comment by lbudai** [comment]
I'd merge this as is, and later we can talk about the `client_lib_dir()`... :-)

**Comment by bazsi** [comment]
Ok, as long as it stays compatible.

**Comment by faxm0dem** [comment]
BTW the java destination is **very** stable congratulations to all the people involved!!!

**Comment by lbudai** [comment]
@faxm0dem : we're glad to hear it, thanks!

**Pull request merged**
