### PR TITLE
[wip]Http load balancer

### PR DESCRIPTION
**Pull request by lbudai**
I've rebased Bazsi's branch against upstream.
Now, we are going to test...

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-http-load-balancer;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by pzoleex** [comment]
@kira-syslogng test this please test branch=pzolee-http-load-balancer;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request closed without merging**
