### PR TITLE
scl: install cim scl only when syslog-ng is compiled with json support

### LINKED ISSUE #673: cim depends on json support
The default syslog-ng.conf includes scl.conf which includes scl/_/_.conf

If syslog-ng is built without json support, after install, using the default config file, syslog-ng will fail to start because cim/template.conf uses format-json which isn't available.

One work-around would be to only install cim/template.conf if ENABLE_JSON is set in scl/Makefile.am.

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #673 

Signed-off-by: Tibor Benke <tibor.benke@balabit.com>

### CODE REVIEW

**Comment by lbudai** [comment]
What if json is a hard dependency for syslog-ng?
I know, that this could be a problem for package maintainers, distros, etc... but we also have internal json library...

**Comment by algernon** [comment]
In that case, this PR is pointless, and configure should error out in this case.

**Comment by czanik** [comment]
I'd definitely to keep it optional for this release: don't do dependency changes after beta phase.

Even if install JSON support in all my distro packages, many people have strong feelings against new mandatory dependencies, and in many cases they are right (Gentoo, FreeBSD, embedded).

**Comment by lbudai** [comment]
@algernon : yep, that's what I wanted to point out. What I'm not sure is when we make it as a hard dep.

@czanik : what beta phase? 3.7 is out, that is a final release, and of course it won't be affected such dependency changes (and sometimes we need to make decisions if we want to move forward... )

**Comment by ihrwein** [comment]
@algernon what if the the modules are able to install SCLs? So `modules/json` would install the `cim` SCL and `modules/python` the `mbox` parser.

**Comment by bazsi** [comment]
I would prefer to use a solution where scl modules can opt-out if their
dependencies are not available, as in that case SCLs could be distributed
independently of the main syslog-ng release.

What about a pragma that aborts the current include file if a module is not
available.

@module-dependency json

If this is not met, the entire include file is skipped. or just using the
current @module directive and extend its behaviour (it currently ignores
errors).

What do you think?



-- 
Bazsi

**Comment by ihrwein** [comment]
I like the pragma thing but for these cases maybe it's too heavy. AFAIK we don't distribute SCLs independently from syslog-ng. We may move the Java related SCLs under `modules/java` so a simple `apt-get install syslog-ng-mod-java` installs them along the Java bindings. It also makes sense to keep the SCLs close to their implementation so if the code changes we didn't forget them so easily. This approach works if there is one non-core module dependency for a given SCL.

So IMHO this would be enough for the short term and the pragma based approach is good for the long term.

**Comment by lbudai** [comment]
I think the `@module-dependency` is better solution.

@ihrwein : What if you have an SCL that have several dependencies? In that case it you cannot decide (automatically) where to put that SCL...

**Comment by lbudai** [comment]
After talked to @ihrwein , we just close this.
(real solution will be implementing the @module-dependency, #827 )

**Pull request closed without merging**
