### PR TITLE
Various fixes for issues reported by LGTM

### PR DESCRIPTION
**Pull request by smortex**
Just discovered LGTM while submitting another issue.  Had some time so I patched a few trivial issues :smile:.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build?
(admin: you have the next options (make sure you checked the code):
"ok to test" to accept this pull request (and further changes) for testing
"test this please" for a one time test run
do nothing -> CI won't start)

**Comment by smortex** [comment]
Just forced commit after a `git rebase --signoff master`.

Let me know if you spot another problem.

**Comment by furiel** [comment]
@kira-syslogng ok to test

**Comment by bazsi** [comment]
This pull request **fixes 8 alerts** when merging 71c979783848e6b7d60519ce8f7a222e0f9d608f into 4486329c2bc920c3803d6faf3c41643dac4cab3b - [view on LGTM.com](https://lgtm.com/projects/g/balabit/syslog-ng/rev/pr-2883c3ca8286a7140149bc04dde7742c1636e374)

**fixed alerts:**

* 6 for Duplicate include guard
* 2 for Missing header guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by Kokan** [comment]
@smortex thanks

**Pull request merged**
