### PR TITLE
F/logmsg serialize

### PR DESCRIPTION
**Pull request by deirf**

### CODE REVIEW

**Comment by lbudai** [comment]
Hi,

this is actually a ported code and I think some of the patches could be squashed (eg.: rename some variables) and other patch-reworking also required (and also commit message polishment).
When you port something you don't have to mimic all the mistakes we made in the past :-)
We can talk about it this IRL on tomorrow.

A question regarding to processed timestamp... : do you really need that? I mean it is just a synomim of the received timestamp so I think it should be removed from this PR.

**Comment by deirf** [comment]
Hi, thanks a lot, the "logmsg-serialize: *" patches are created only for better review-able codes and with this cut patches is easyer fixable if it it need.
The processed timestamp is an interesting question. Let us talk about it tomorrow.
I wrote 2 testcases for older version serialized message readers. There are working too anyway.

**Comment by czanik** [comment]
Hi, Is this code already a preparation for enabling the disk buffer code in OSE?

**Comment by lbudai** [comment]
Hi,

logmsg serialization is one of the very first step what we have to make in order to support the diskbuffer, so the answer is yes.

( As you can see there are some unprocessed review notes, so maybe this PR won't be merged, but we are definitely working on the diskbuffer port into OSE. )

**Comment by lbudai** [comment]
I'll close this as @juhaszviktor will send a new PR addressing this...

**Pull request closed without merging**
