### PR TITLE
Refactor of syslog-format

### PR DESCRIPTION
**Pull request by dnsjts**

### CODE REVIEW

**Comment by ihrwein** [comment]
The commits are small, they address specific problems. They are in a good order and I think we should spend more time to refactor old smelling codes so I really like this refactor. 

You can find my notes, after those are corrected you get the :+1:  from me.

**Comment by dnsjts** [comment]
I think the review notes have been corrected, please review the pull request again.

**Comment by lbudai** [comment]
@dnsjts : thanks for re-working the commit messages!!!
I'll re-review the whole patch soon.

**Comment by lbudai** [comment]
@dnsjts : before the merge I'd run some extra tests on this change
Talk to PZoli about this.

**Comment by lbudai** [comment]
I checked it and passed on some extra tests, so I merge it.
Thanks.

**Pull request merged**
