### PR TITLE
F/debugger cli in python

### PR DESCRIPTION
**Pull request by bazsi**
This branch actually completes the initial batch to support command completion in the syslog-ng interactive debugger.

Right now it is able to use completion on:
 * the debug commands themselves
 * in the template string argument to various debug commands (print and display)

The support for template strings is pretty comprehensive, it understands macros (both with and without braces, e.g. ${MSG} and $MSG), template functions and literal strings. It understands three template functions a bit deeper: format-json, echo and geoip

The support for format-json goes as far as understanding all its keyword arguments and providing completion for macros within the command line.

The entire implementation is based on the Python work I did earlier and I intend to add support for further completions as I see this functionality of becoming really useful for interactive syslog-ng configuration development.

The code itself is pep8 and pylint warning free, has a pretty good unit test coverage (96%, with most of the unsupported portions is in hooking into the readline subsystem).

It could still be improved, but I feel it is good enough to integrate it. I am going to deal with further development in subsequent patches.

Please merge.

### CODE REVIEW

**Comment by bazsi** [comment]
Hmm... I seem to lack some signed-off-by-s and also hooking the Python unit tests into the syslog-ng unit test machinery.

Any comments are welcome, anyway.

**Comment by bazsi** [comment]
I added the signed-off-bys and expanded the commit comments. There was another breakage with travis due to a missing dependency, which I have also fixed now hopefully.

So if travis passes, please consider this for merging.

**Comment by bazsi** [comment]
Finally travis agrees. I am going to clean up the patches, then the branch is ready for merging.

**Comment by bazsi** [comment]
Travis finally agrees, I've cleaned up the patches, so at this time, this is really ready for merging.

Please merge!
Thanks.

**Comment by lbudai** [comment]
`sudo pip install nose ply pep8 pylint` added to drone.io settings (Commands)

Hope the best :-)

**Comment by bazsi** [comment]
Great, Thanks a lot. This means that we finally have useful tab completion
in the debugger.


-- 
Bazsi

**Comment by bazsi** [comment]
btw, when do we plan to have a release?


-- 
Bazsi

**Comment by lbudai** [comment]
My plan is that during next we will have a 3.7beta. 

(I wanted HDFS destination to be released in final 3.7, but it needs some work - gradle build, find/setup maven repo for 3rd party HDFS client libraries[jar files], etc...  But, well, we will see... I think debugger feature will steal the show, so HDFS needs another release :-) Talk about it on next week. )

**Pull request merged**
