### PR TITLE
Lexer test coverage improvements

### PR DESCRIPTION
**Pull request by bazsi**
This patch vastly improves coverage in test_lexer, which I did as a preparation for @if/@else/@endif support. Since I now had a more important project, I've shelved the preprocessor improvements, and submit only the testing bits.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by furiel** [comment]
Hmmm I wonder why this is only triggered with the clang+cmake combination.
```
/home/travis/build/balabit/syslog-ng/lib/tests/test_lexer.c:265:3: error: 
      format specifies type 'long long' but the argument has type 'gint64'
      (aka 'long') [-Werror,-Wformat]
  assert_parser_number(12LL);
```

**Comment by furiel** [comment]
@bazsi I checked the patchset, and I do not have any comment or request changes. I like these new unit tests! When travis is green, approve from my side.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
@furiel I've mistakenly clicked on the request review button, I am not against a review per se but didn't intend to push you. :)

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by bazsi** [comment]
Sure, I was just fighting with travis but will do so soon that it finally
has become green.

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
