### PR TITLE
Geoip quiet

### LINKED ISSUE #663: geoip: spurious and wrongly routed messages
When the geoip parser fails to match an entry in the database, _e.g._ `127.0.0.1`, it complains with `Invalid database type GeoIP City Edition, Rev 1, expected GeoIP Country Edition`.
- this message is spurious
- and should flow through the internal message queue

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #663 

Note, that this PR sets the minimal supported geoip version to 1.6.3.

You can find fresh geoip debian packages here: https://launchpad.net/~maxmind/+archive/ubuntu/ppa

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
Please prefix using single underscore instead of double underscores in `__open()`. It was recently mentioned in `F/logmsg serialization` . Otherwise :+1:

**Comment by bazsi** [comment]
why do we need to make this configurable?

**Comment by ihrwein** [comment]
Maybe a system administrator wants to see those messages. Ofc, we can enable silencing by default.

**Comment by bazsi** [comment]
where would they become visible? if they are printed to stderr/stdout those
are usually redirected to /dev/null when syslog-ng is running.


-- 
Bazsi

**Comment by ihrwein** [comment]
I talked with @bazsi IRL and we come up with the following proposal:
* if syslog-ng's stderr isn't a TTY, we use geoip in silenced mode, otherwise we don't make it quiet

**Comment by faxm0dem** [comment]
But they *do* show up in my log path!

**Comment by ihrwein** [comment]
I got confused :) If they are spurious I guess we can drop these messages. Or did you test the branch and it didn't work?

**Comment by faxm0dem** [comment]
I didn't test any branch.
My remark was answering @bazsi's comment:

| where would they become visible? if they are printed to stderr/stdout those are usually redirected to /dev/null when syslog-ng is running

I confirm that in the 3.7.2 release, the geoip messages do appear in the log path, and not on stdio

**Comment by ihrwein** [comment]
I've checked how GEOIP_SILENCE is used: https://github.com/maxmind/geoip-api-c/blob/4f487bf95532e0bba7783d591faff178ab0aa462/libGeoIP/GeoIP.c#L1467

Actually, the `printf` calls are untouched.

Based on this fast I think this PR can be closed...

**Pull request closed without merging**
