### PR TITLE
F/fix lexer

### LINKED ISSUE #714: plugin loading anomalies
I've some problems with how `LL_IDENTIFIER` works in the grammar. I'd like to load external plugins where the plugin's parser definition doesn't start with say `KW_FOO` but with `LL_IDENTIFIER`. 

External parser plugins are loaded from the grammar:
```
parser_expr
        : LL_IDENTIFIER
          {
            Plugin *p;
            gint context = LL_CONTEXT_PARSER;

            p = plugin_find(configuration, context, $1);
            CHECK_ERROR(p, @1, "%s plugin %s not found", cfg_lexer_lookup_context_name_by_type(context), $1);

            last_parser = (LogParser *) plugin_parse_config(p, configuration, &@1, NULL);
            free($1);
            if (!last_parser)
              {
                YYERROR;
              }
            $$ = last_parser;
          }

        ;
```
This says that here is an `LL_IDENTIFIER`, plugin system please look up the parser plugin with that name. It works, but...

When the plugin successfully looked up we got back it's config parser function (the one which is generated from a grammar). The interesting thing is that I cannot start the grammar definition with `LL_IDENTIFIER` because I get back an error:
```
[2015-09-24T10:14:01.849642] Module loaded and initialized successfully; module='kutya'
Error parsing kutya, syntax error, unexpected $undefined, expecting LL_IDENTIFIER in /home/tibi/install/syslog-ng/etc/syslog-ng.conf at line 17, column 5:

    kutya (
    ^^^^^
```

My parser plugin grammar definiton starts with the following code:
```
start
  : rust
    {
      *instance = $1;
      if (yychar != YYEMPTY)
        cfg_lexer_unput_token(lexer, &yylval);
      YYACCEPT;
    }
  ;

rust
  : LL_CONTEXT_FILTER rust_filter { $$ = $2; }
  | LL_CONTEXT_PARSER rust_parser { $$ = $2; }
  ;

rust_filter
  : LL_IDENTIFIER '(' rust_filter_params ')' { $$ = *instance; }
  ;

rust_parser
  : LL_IDENTIFIER '(' rust_parser_params ')' { $$ = *instance; }
  ;
...
```

If this grammar works I will be able to use the same grammar definitions for every Rust based plugins. I just need to generate different `ModuleInfo` and `Plugin` structures for them so the plugin system can find the proper plugin by its name. So the Rust plugins don't have to generate their own grammar just link against a static library (almost a full module without the `plugin.c`).

### PR DESCRIPTION
**Pull request by ihrwein**
Fixes #714 

Suggested-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by bazsi** [comment]
fyi, this is the documentation of %destructor

 -- Directive: %destructor { CODE } SYMBOLS
     Invoke the braced CODE whenever the parser discards one of the
     SYMBOLS.  Within CODE, '$$' (or '$<TAG>$') designates the semantic
     value associated with the discarded symbol, and '@$' designates its
     location.  The additional parser parameters are also available
     (*note The Parser Function 'yyparse': Parser Function.).

     When a symbol is listed among SYMBOLS, its '%destructor' is called
     a per-symbol '%destructor'.  You may also define a per-type
     '%destructor' by listing a semantic type tag among SYMBOLS.  In
     that case, the parser will invoke this CODE whenever it discards
     any grammar symbol that has that semantic type tag unless that
     symbol has its own per-symbol '%destructor'.

     Finally, you can define two different kinds of default
     '%destructor's.  (These default forms are experimental.  More user
     feedback will help to determine whether they should become
     permanent features.)  You can place each of '<*>' and '<>' in the
     SYMBOLS list of exactly one '%destructor' declaration in your
     grammar file.  The parser will invoke the CODE associated with one
     of these whenever it discards any user-defined grammar symbol that
     has no per-symbol and no per-type '%destructor'.  The parser uses
     the CODE for '<*>' in the case of such a grammar symbol for which
     you have formally declared a semantic type tag ('%type' counts as
     such a declaration, but '$<tag>$' does not).  The parser uses the
     CODE for '<>' in the case of such a grammar symbol that has no
     declared semantic type tag.

And example use:

     %union { char *string; }
     %token <string> STRING1 STRING2
     %type  <string> string1 string2
     %union { char character; }
     %token <character> CHR
     %type  <character> chr
     %token TAGLESS

     %destructor { } <character>
     %destructor { free ($$); } <*>
     %destructor { free ($$); printf ("%d", @$.first_line); } STRING1 string1
     %destructor { printf ("Discarding tagless symbol.\n"); } <>


Right now, the following  types are allocated on the heap by the lexer:

LL_BLOCK, LL_STRING & LL_IDENTIFIER contains a cptr that must be freed (right now using free())

This is as far as the current grammar goes. There are rules that allocate values (source_stmt for example), which are currently leaked if the grammar fails. Those could be handled properly using %destructor, but can be done as a separate step as well.

LL_IDENTIFIER

**Comment by ihrwein** [comment]
@bazsi thanks for your extra investigations.

Does it mean, that I have to add a `%destructor { free($$); } LL_IDENTIFIER LL_STRING LL_BLOCK` to `lib/cfg-grammar.y`?

That doesn't solve this memleak. After some coffee I think we leak the cloned `YYSTYPE` pointer. We use `cfg_lexer_free_token()` to free the cloned token, but it just frees the allocated fields, like `cptr` (This is mentioned in a comment).

Should I create a `_token_free()` function which frees `cptr` then `self` and use it in `cfg_lexer_unput_token()`?

**Comment by ihrwein** [comment]
I began to change `tokens` to `GPtrArray` which would only store cloned `YYSTYPE` pointers. It still needs some tweaking because one unit test fails (it uses `cfg_lexer_free_token() directly`). I hope this is the right way.

**Comment by ihrwein** [comment]
@bazsi I cleaned up the ownership stuff related to `YYSTYPE` (at least I hope). Could you review it, please?

**Comment by bazsi** [comment]
sorry for not looking at this for long. I think we shouldn't use pointers to YYSTYPE instead of just the struct. maybe "clone" was a bad term and I should have used "copy" instead.

By not allocating YYSTYPE instances (as the grammar uses a local copy anyway), but taking care of proper copying, we can ensure ownership rules and not complicate the lexer too much.

let me check if I can create an alternative branch.

**Comment by bazsi** [comment]
hmmm... as it seems destructors work differently than I thought. they will only invoke the free automatically in case the grammar itself destructs the token and not for individual rules. unfortunately there's no mechanism to do that :(

anyway, you can find my take on f/fix-lexer-bazsi

it does away with the explicit YYSTYPE allocation, but differentiates between an "add_and_consume" and a simple "add" operation when transfering the ownership of tokens. The first will borrow the embedded pointers, the add copies them.

the CfgTokenBlock will always "own" its tokens, e.g. it always frees them if they are not fetched.

the grammar is always responsible for freeing tokens:
1) either automatically by %destructor
2) or explicitly by rules

cfg_lexer_unput_token() always copies, as the lookahead token will be automatically freed by the grammar as well.

plugin_parse_config() uses the consume API, so it doesn't have to free it.

I am not entirely sure though. I initially added "copy" to the names of the copying versions of the functions, but it seemed out-of-place.

What do you think?

**Comment by ihrwein** [comment]
If this problem can be solved this way then it's ok for me, though I've some unclear parts:

1. `cfg_lexer_copy_token()` takes `dest` as a pointer. Why can't we return a non-pointer `YYSTYPE`?
1. the `cfg_token_block_add_and_consume_token()` name is a little confusing for me: the `consume` word indicates that it takes over the ownership of the token, but it borrows it. What if we call it `cfg_token_block_add_borrowed_token()`? And if `tokens` cotnains owned tokens why do we add borrowed tokens to them as well?
1. If the previously mentioned function borrows the token, then I suppose `cfg_token_block_add_token()` should take over the ownership. But it copies the token (which is borrowed) and I can't figure out a good name for it...
1. We use `cfg_token_block_add_and_consume_token()` to add a borrowed token two times to `tokens` in `plugin.c` which will end up in double free (consume don't call `copy()`). IMHO the first call should take a copied token and the second can take over the ownership of the original token.

**Comment by bazsi** [comment]
On Oct 13, 2015 12:20 PM, "Tibor Benke" <notifications@github.com> wrote:
>
> If this problem can be solved this way then it's ok for me, though I've
some unclear parts:
>
> cfg_lexer_copy_token() takes dest as a pointer. Why can't we return a
non-pointer YYSTYPE?

Hmm, I don't like struct returns because that involves an extra copy. But I
guess it's just an old habit. OK the other hand I think it is clearer as we
only copy the contents, not the struct itself.

> the cfg_token_block_add_and_consume_token() name is a little confusing
for me: the consume word indicates that it takes over the ownership of the
token, but it borrows it.

It takes care about freeing it, thus it also consumes the token. The
pointer value itself is not borrowed (well, it is but only as a parameter)

What if we call it cfg_token_block_add_borrowed_token()? And if tokens
contains owned tokens why do we add borrowed tokens to them as well?

The token block is owning the memory associated in the tokens it stores.
Thus it has to duplicate cptr unless the caller used the _consume version.

> If the previously mentioned function borrows the token, then I suppose
cfg_token_block_add_token() should take over the ownership. But it copies
the token (which is borrowed) and I can't figure out a good name for it...

add_token gets a token the caller wants to remain responsible for, so that
one copies.

> We use cfg_token_block_add_and_consume_token() to add a borrowed token
two times to tokens in plugin.c which will end up in double free (consume
don't call copy()).

No, simply the YYSTYPE structure is reused, those are independent tokens.
The first add_and_consume() transfer ownership of all fields to the token
block, the struct can be reused.

We don't allocate the YYSTYPE struct, that made the code more complicated.

IMHO the first call should take a copied token and the second can take over
the ownership of the original token.

>
I hope I could make it a bit clearer.

**Comment by ihrwein** [comment]
Thanks, I see.

Do you want to finish you branch or should I prepare it for a PR?

**Comment by bazsi** [comment]
I am ok with either. I have some csv-parser cleanup patches in the queue,
then I wanted to work on the aws proxy protocol, this could come third or
in between.

If you have some review bandwidth, it'd be great if you could review the
CSV parser stuff, maybe I'd submit that partially as it is already roughly
10 patches and more is to come.

**Comment by ihrwein** [comment]
Then I'll prepare it, you need the your strength for csv-parser :) And ofc I'll review that.

**Comment by ihrwein** [comment]
I'm closing this in favor of https://github.com/balabit/syslog-ng/pull/740.

**Pull request closed without merging**
