### PR TITLE
Add support of Kafka 0.9.0.0

### PR DESCRIPTION
**Pull request by ihrwein**
Add Kafka 0.9.0.0 support.

Fixes: #839

### CODE REVIEW

**Comment by ihrwein** [comment]
Although this PR compiles, I'll have to try it out. However, it is useful for our users who want to test the SSL support.

**Comment by MrAnno** [comment]
I tried this patch with `kafka_2.11-0.9.0.0`, it works perfectly (I haven't checked with SSL yet).

**Comment by MrAnno** [comment]
:+1: 
It is also working with SSL (TLSv1/SSLv3, DHE-DSS-AES256-SHA cipher).

**Comment by bkil-syslogng** [comment]
Can anyone else review this? I doesn't look bad to me, but I'm not qualified to vote in this case.

**Pull request merged**
