### PR TITLE
Fix possible crash in afsocket

### PR DESCRIPTION
**Pull request by furiel**
This patchset contains a fix initialization related crash in afsocket.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
success

**Comment by bazsi** [comment]
Why do we need the controller passed to the LogProto layer? I don't see it actually being used.

**Comment by MrAnno** [comment]
One of our internal protos has multiple idle/command/etc. timers that can, for example, close the connection. We didn't want to contaminate `LogReader` with such timeout logic (which would produce more "dead code" on the OSE side), so we passed the controller and notified the controller pipe directly to close the connection (NC_CLOSE).

**Comment by furiel** [comment]
@bazsi I dropped down the two controversal patches : virtual deinit and passing control pipe to constructor. It now only contains only a single patch: @MrAnno 's bugfix. I believe when the tests pass, this can be merged.

**Comment by bazsi** [comment]
agreed. looks good to me.

**Pull request merged**
