### PR TITLE
Clang compile error because of -Werror

### PR DESCRIPTION
**Pull request by Kokan**
Signed-off-by: kokan <peter.kokai@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
what was the issue here? I can't deduce that from the patch alone.

**Comment by Kokan** [comment]
@bazsi The initial issue is that the master does not compile with clang.

But as it turned out, this is not the only issue with the clang compiling. This is a WIP till I fix all compile related issue. (the title is misleading because I thought this is the only issue.)

As for the utmp part:
During configure we try to detect if *modern* utmp is used via checking if the _ut.ut_user_ field exists.
But in clang the code which checked contained warnings, the travis compiles it with -Werror, thus the check always said *modern* utmp is not supported, cause latter compile error.

**Comment by Kokan** [comment]
The rest of this issue is actually comes from https://github.com/alanxz/rabbitmq-c .
This library does not compile with clang-3.9 and -Werror.
See the details in alanxz/rabbitmq-c#440

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Can we merge this ASAP? This causes travis to be red for me as well. Thanks. 

the configure change looks ok to me. I don't know about librabbitmq.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
