### PR TITLE
wildcard-source: fix memleak when directory removed

### PR DESCRIPTION
**Pull request by gaborznagy**

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please

**Comment by mitzkia** [comment]
@kira-syslogng retest this please;

**Comment by mitzkia** [comment]
@kira-syslogng test this please

**Comment by mitzkia** [comment]
@kira-syslogng test this please;

**Pull request merged**
