### PR TITLE
F/remove msg error etc null sentinel.sh, run on http module

### PR DESCRIPTION
**Pull request by bkil-syslogng**
msg_error("description", evt_tag_str("when", "before"), NULL);
msg_error("description", evt_tag_str("when", "after"));

This was the automated transformation done in this pull request:
#941 "F/remove msg error etc null sentinel"

f36548b
"dropped extra NULL sentinel at msg_*() call sites"

It was copied from the commit message verbatim, but it may be improved
in the future.

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
There are copyright declaration omissions, I will add these shortly.

**Comment by bkil-syslogng** [comment]
Ready for review. This fixes master breakage. @MrAnno is already reviewing it. Any takers for a second reviewer? E.g.: @dnsjts @bazsi @lbudai ?

**Comment by MrAnno** [comment]
:+1:

**Comment by lbudai** [comment]
@bkil-syslogng : thanks!
[ meanwhile I've fixed the drone.io,  so I hope it will be also green ]

**Pull request merged**
