### PR TITLE
F/ci log improve c

### PR DESCRIPTION
**Pull request by bkil-syslogng**
Clean up build log, mostly in Travis.

### CODE REVIEW

**Comment by bazsi** [comment]
I wouldn't want to do a detailed review at this point, but if it improves Travis logs I am all for it.

**Comment by bazsi** [comment]
This seems to have been left behind, can this be merged?

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by presidento** [comment]
Left behind, I'll close it.

**Comment by furiel** [comment]
I reviewed the diff and it contains many valuable changes. I propose for merge.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
