### PR TITLE
Fix disabling MongoDB destination support in syslog-ng 3.8

### PR DESCRIPTION
**Pull request by ihrwein**
You can use --with-mongoc=no configure option to disable
this destination.

Signed-off-by: Tibor Benke <tibor.benke@balabit.com>

### CODE REVIEW

**Comment by MrAnno** [comment]
:+1:

**Comment by MrAnno** [comment]
```
AC_ARG_WITH(mongoc,
              [  --with-mongoc=[system/internal/auto]
                                         Link against the system supplied or the built-in mongo-c-driver library. (default: auto)]
              ,,with_mongoc="auto")
```
Is it OK that the arg description is not updated with the `no` value?

**Comment by bkil-syslogng** [comment]
:+1: Now the fix looks good to me. I agree that it would be nice to extend the arg description.

Just a side note, don't block on this one. It would be beneficial to refactor so as the recommended way to disable MongoDB could be `--enable-mongodb=no`, because it sounds much more intuitive. In this case, I would update the other arg description instead.

**Comment by ihrwein** [comment]
@MrAnno `no` added

**Comment by MrAnno** [comment]
:+1:

**Comment by lbudai** [comment]
could you rebase it?

**Comment by ihrwein** [comment]
rebased, auto squashed, force pushed

**Pull request merged**
