### PR TITLE
F/afsql warning fixes

### LINKED ISSUE #776: Eliminate compiler warnings and turn on -Werr
I used the master branch.

```
../modules/afprog/afprog.c: In function 'afprogram_reload_store_item_free':
../modules/afprog/afprog.c:69:3: warning: passing argument 1 of 'log_pipe_unref' from incompatible pointer type [enabled by default]
   log_pipe_unref(reload_info->writer);
   ^
In file included from ../lib/driver.h:29:0,
                 from ../modules/afprog/afprog.h:27,
                 from ../modules/afprog/afprog.c:24:
../lib/logpipe.h:237:6: note: expected 'struct LogPipe *' but argument is of type 'struct LogWriter *'
 void log_pipe_unref(LogPipe *self);
      ^
../modules/afprog/afprog.c: In function 'afprogram_dd_kill_child':
../modules/afprog/afprog.c:329:13: warning: unused variable 'pgid' [-Wunused-variable]
       pid_t pgid;
             ^
../modules/afprog/afprog.c: In function 'afprogram_dd_store_reload_store_item':
../modules/afprog/afprog.c:452:3: warning: passing argument 4 of 'cfg_persist_config_add' from incompatible pointer type [enabled by default]
   cfg_persist_config_add(cfg, afprogram_dd_format_persist_name(self), reload_info, afprogram_reload_store_item_destroy_notify, FALSE);
   ^
In file included from ../lib/logpipe.h:30:0,
                 from ../lib/driver.h:29,
                 from ../modules/afprog/afprog.h:27,
                 from ../modules/afprog/afprog.c:24:
../lib/cfg.h:158:6: note: expected 'GDestroyNotify' but argument is of type 'void (*)(struct AFProgramReloadStoreItem *)'
 void cfg_persist_config_add(GlobalConfig *cfg, gchar *name, gpointer value, GDestroyNotify destroy, gboolean force);

```

To do:
- [x] Eliminate compiler warnings - #779
- [ ] Turn on -Werr #871

### PR DESCRIPTION
**Pull request by bazsi**
This one resolves #776 by fixing warnings in the afsql module. It bumps the libdbi requirement to
0.9.0 but that should already be available on all major distributions.

### CODE REVIEW

**Comment by bazsi** [comment]
hmm... travis seems to run on precise where only 0.8.x is available, which does not compile with this change. :(

**Comment by ihrwein** [comment]
Shouldn't the `configure` script disable the sql module with your change?

**Comment by bazsi** [comment]
Yeah it should (a bug in itself) but then we'd not test afsql in travis.

I'll check that.

**Comment by ihrwein** [comment]
:+1:

**Comment by dnsjts** [comment]
:+1:

**Comment by bazsi** [comment]
@lbudai it seems that we don't have the libdbi dependencies in OBS yet and until that happens this PR would disable SQL tests in travis.

What should we do? I see three options:
1) not merge this
2) merge this now and open an issue to add libdbi to OBS
3) wait until libdbi 0.9 is in OBS and then merge this.

What do you think?

**Comment by lbudai** [comment]
@bazsi: I think OBS shouldn't be a problem. 
(I can release the libdbi 0.9.x in OBS, like other deps, so I'd merge this now.)

**Comment by ihrwein** [comment]
The rebased version of this PR (https://github.com/balabit/syslog-ng/pull/829) has been merged. I'm closing this.

**Pull request closed without merging**
