### PR TITLE
declaration related warnings fixes

### LINKED ISSUE #1962: warning elimination: declaration related warnings
As the result of #1302 we want to eliminate some special warnings. For this reason I open issues with the different warning types to split the problem into subtasks.

The resolution would be a PR that fixes the mentioned warnings, and - to defend against reintroducing such warnings - these kind of warnings should be added in the top level Makefile.am, to the end of AM_CFLAGS in the ENABLE_EXTRA_WARNINGS block. As travis transforms such warnings to errors, we can be sure no new warnings will be added in the future from these types.

This issue should cover the declaration related warnings.
```
      2 [-Wimplicit-function-declaration]
      1 [-Wnested-externs]
      2 [-Wold-style-declaration]
     16 [-Wstrict-prototypes]
```
(The numbers in the statistics are just an approximate)

Hint: extra warnings can be enabled with --enable-extra-warnings configure option.

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
Resolves #1962.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by Kokan** [comment]
@kira-syslogng ok to test

**Comment by furiel** [comment]
@mehul-m-prajapati about ivykis: can you try to add an exception for that specific warning in lib/Makefile.am for ivykis? I am fine with not applying all these warnings for such modules.
```
lib/ivykis/src/libivykis.la:
	${MAKE} CFLAGS="${CFLAGS} -Wno-error" -C lib/ivykis
```

**Comment by furiel** [comment]
@mehul-m-prajapati about the clang error for unknown warning:
you can try to cherry-pick cac74376a74aea5cdf0feffdb2fcea34a4fd3344 (.travis.yml: only enable extra warnings on gcc) from #1302, which should switch off enable-extra-warnings for clang.

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

I am still getting error for iv.h evn after adding -Wno-error=strict-prototypes
```
In file included from ../lib/logthrdestdrv.h:33:0,
                 from lib/cfg-grammar.y:41,
                 from modules/native/native-grammar.y:39:
./lib/ivykis/src/include/iv.h:57:14: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 const struct timespec *__iv_now_location_valid();
```

**Comment by furiel** [comment]
Oh I see I overlooked it, we are not failing while building ivykis, but when we include the ivykis headers.

After googling a bit, I found gcc will ignore warnings if header directories are added by `-isystem` instead of `-I`. Actually it seems vendor provided headers should use -isystem anyway, so maybe you found a bug?

https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options
> You can use -I to override a system header file, substituting your own version, since these directories are searched before the standard system header file directories. However, you should not use this option to add directories that contain vendor-supplied system header files; use -isystem for that. 

After replacing `-I` with `-isystem` in three places at `IVYKIS_CFLAGS` and `INTERNAL_IVYKIS_CFLAGS`, gcc did not complain anymore for ivykis. So this can be one option. Though I am interested in your and other's opinion if we are fine to change this. I am low on xp on this topic, what other effects this can have.

Another alternative I found is to temporarily disable warnings with `#pragma`, such includes could be decorated with it. Though this needs a little experiment, because such options are only available from a specific version of gcc, and it would be unfortunate to fail to compile do to this on older platforms. As I counted, iv.h is included in 31 places, so in this option probably it would be better have a special include file in lib/compat, something like 'syslog-iv.h', which encapsulates this ugly pragma detail, and that header should be used in the code at those 31 places.

All that said, I still ran into trouble with sql source... The libdbi driver has the same problem. Now the problem is we cannot touch that with -isystem, the options come from a .pc file, we do not have control on that. Maybe the pragma version would work there, but: as travis compiles without sql support, I think we can delay solving it now. When you test locally, just pass `--disable-sql` to configure, the same way as travis does.

Unfortunately, that's not all, jsonc also emits warning but for another very strange reason, it signals error saying my system does not have strdup. Let alone, travis does not compile jsonc, it instead installs it from deb, and uses the system version of jsonc: adding `--with-jsonc=system` to configure, so it is not an issue to solve now (though I am utmost interested why it cannot detect my strdup). With jsonc from system, I could finally build locally your patchset without error.

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

Is there any other way to commit following change ?
```
-const struct timespec *__iv_now_location_valid();
+const struct timespec *__iv_now_location_valid(void);
```

**Comment by furiel** [comment]
As ivykis is a submodule, I am afraid the only way would be a local patch over the vendor code. I would like to avoid this, because it further increases the complexity to maintain these modules.

You can try to contribute to ivykis upstream, and with a stable ivykis release, we can update the submodule version. Though it would not be future proof, we cannot enforce appliance for submodules from a syslog-ng build script, ivykis can break it later on. Also, there might be other warnings that need to be managed. So we need a general solution without enforcing anything to the ivykis code.

(But this should not hold you back to contribute to ivykis, it would still be a good patch :) )

**Comment by gaborznagy** [comment]
@mehul-m-prajapati! Can you rebase your branch against latest master, please? 
We have just merged a warning related PR.

**Comment by mehul-m-prajapati** [comment]
Hi @gaborznagy ,

I have rebased my branch against latest master. Thanks for the update.

@furiel : 
```
After replacing -I with -isystem in three places at IVYKIS_CFLAGS and INTERNAL_IVYKIS_CFLAGS, gcc did not complain anymore for ivykis.
```
I see these flags in **configure.ac** .

Is it the correct place where I need to replace  ```-I with -isystem.```

**Comment by furiel** [comment]
@mehul-m-prajapati that's right, two in the IVYKIS_CFLAGS line, one in the INTERNAL_IVYKIS_CFLAGS line:
```
--- a/configure.ac
+++ b/configure.ac
[...]
-               IVYKIS_CFLAGS="-I\$(top_srcdir)/lib/ivykis/src/include -I\$(top_builddir)/lib/ivykis/src/include"
-                INTERNAL_IVYKIS_CFLAGS="-I\${includedir}/syslog-ng/ivykis"
+               IVYKIS_CFLAGS="-isystem \$(top_srcdir)/lib/ivykis/src/include -isystem \$(top_builddir)/lib/ivykis/src/include"
+                INTERNAL_IVYKIS_CFLAGS="-isystem \${includedir}/syslog-ng/ivykis"
```

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

All warning related errors are removed.

There are still 2 things which fails in Travis CI,
1. In gcc compiler, 
```
mkdir: cannot create directory ‘syslog-ng-3.14.1/_build’: File exists
make: *** [distcheck] Error 1
```
2. In clang compiler,
```
lib/scanner/kv-scanner/kv-scanner.c:264:24: error: initializer overrides prior
      initialization of this subobject [-Werror,-Winitializer-overrides]
    .match_delimiter = _match_delimiter,
                       ^~~~~~~~~~~~~~~~
lib/scanner/kv-scanner/kv-scanner.c:263:5: note: previous initialization is here
    0,
    ^
1 error generated.
```

Do you have any idea on this?

Thanks,
Mehul

**Comment by kira-syslogng** [comment]
success

**Comment by furiel** [comment]
About the gcc: 
Yes it is unfortunate that our distcheck part in travis is bug-ish.
The long story: we want distcheck run fast, so start with -j3. But if parallel build is used, it is hard to spot the problem because of the interleaving build logs. So when a make -j3 distcheck fails, we restart make distcheck with -j1, hoping that the already compiled parts are skipped, so the first error will be the error we are looking for. This tecnique works fine with simple make command, but not with distcheck, because distcheck locks the _build directory, so the second round cannot even start. Essentially, any problem during distcheck results in this strange error _build exists.

Short story, you need to scroll up a little bit to see the problem:
make[4]: Nothing to be done for `../modules/python/pylib/test_pylib.sh'.
```
../lib/secret-storage/tests/test_secret_storage.c:39:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 secret_storage_testsuite_init()
 ^
../lib/secret-storage/tests/test_secret_storage.c:46:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 secret_storage_testsuite_deinit()
```

About clang, me seems the problem is as if StrReprDecodeOptions options would be initialized two times: first with zero, and then all fields are enumerated and initialized separately. So in the end the `,0` does not make sense and it probably causes the problem. But it is just a guess, I did not test it.

**Comment by mehul-m-prajapati** [comment]
Hi @furiel,

You are right on both the cases.

1. I have made changes in test_secret_storage.c to remove warnings.

2. I have remove double initialization to resolve clang error.

Thanks,
Mehul

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by furiel** [comment]
Well done! I just have some cosmetic requests.

Please use `Signed-off-by: ...` in your commit message. Commits are cherrypicked, ported, rebased, moved around time to time, so the author of the commit can change. However Signed-off-by is eternal, maintaining your fame and glory forever as contributor to syslog-ng. You can find example for the format in almost every commit messages, or you can generate it with git commit -s/--signoff command line option.

And this leads to the cherry-picked part of your patch, please revert it to a separate patch, maintaining the original signed-off-by line. (As in this case that patch is an ugly hack because we cannot do better, you are better of not linking your name to commit :)) 

Finally, please add a space after -isystem. Strangely enough I tried and it works as it is now, though I'm not sure why. In my previous experiences, I always seen space when others used -system includedir, moreover the manual of gcc does not explicitely enables this: while`-Idir...` is allowed without space, all occurrences I found in the gcc manual uses space. It is safer to follow it.
```

**Comment by kira-syslogng** [comment]
success

**Comment by kira-syslogng** [comment]
success

**Comment by mehul-m-prajapati** [comment]
Hi @furiel ,

Done the changes. Please look at it now ...

Thanks,
Mehul

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by kira-syslogng** [comment]
success

**Pull request merged**
