### PR TITLE
Fix automake warnings in native and diskq modules

### PR DESCRIPTION
**Pull request by ihrwein**

### CODE REVIEW

**Comment by ihrwein** [comment]
This PR depends on #936 . Please merge that so I can update this PR, there will be some conflicts.

**Comment by ihrwein** [comment]
@bkil-syslogng I had to force push the branch, because (IMHO) I had too many steps.

Now, the first commit eliminates the automake warnings.

**Comment by bkil-syslogng** [comment]
:+1:

**Comment by ihrwein** [comment]
rebased, force pushed

**Comment by lbudai** [comment]
thanks!

**Pull request merged**
