### PR TITLE
stats-counter: json formatter implemented

### LINKED ISSUE #272: syslog-ng stats as value pairs
There are now multiple outputs which forward value pairs and enable administrators to create graphs, collect statistics or send alerts from these value pairs (graphite, redis, riemann, etc.). Many different statistics are collected by syslog-ng, but right now these are presented in a way, which can't be easily forwarded to these systems.
Statistics should be available as value pairs, making it easy to forward to these systems or even as a JSON formatted message.

### PR DESCRIPTION
**Pull request by gregory094**
Issue #272 mentioned it would be great to be able to
extract queue stats in json format.
The formatter is implemented but there is no option
for changing between csv and json formatters yet.
I'll implement the options and mechanism to do that.

fixes #272

Signed-off-by: Gergő Nagy <gergo.nagy@balabit.com>

### CODE REVIEW

**Comment by algernon** [comment]
There's only one issue I have with this solution: to use this, one needs to link libsyslog-ng.so against json-c. That means that - for a distribution - I'd need a json-c dependency for the smallest -core package too. I wouldn't be too happy about that.

Would it be possible to make stats pluggable? That way one would be able to keep core package small(ish), yet, still offer json stats if and when needed.

**Comment by algernon** [comment]
FWIW, we don't use json-c for json formatting in `$(format-json)`, so perhaps it would make sense to reuse parts of that code here too?

**Comment by gregory094** [comment]
Your issue is absolutely valid. Although, let's say we will have some more formatters, making all of them pluggable seems to be a little bit weird for me. While using a program I'd not be happy if I had to use plugins in order to print the output in some specific formats. (csv, json, xml outputs are basic features for me) 

As far as I can see the pros and cons:

**pros**
* "smallest core package" / dependency
* customizable

**cons**
* complexity 
* weird to plug formatters for stats

Possible solutions:

1) possibly we could use the code around `$(format-json)`
2) we can write a very simple json format output
3) we can move the formatting logic to `syslog-ng-ctl`
    * `syslog-ng` would answer in `csv` format for the requests of the `ctl` and that would reformat it according to the option given in the cmdline.
    * although, this solution would just move the dependency to the `ctl` from the `core`

What do u think?

**Comment by algernon** [comment]
Yeah, making stat formatting pluggable is an overkill, I agree. Moving it to `syslog-ng-ctl` doesn't help me much, because that's in the same `syslog-ng-core` package in pretty much every distro, so the dependency would still be there.

So I'd suggest using a custom JSON formatter, like in `$(format-json)`. In the case of `$(format-json)`, it uses `value-pairs()`. So if stats would emit a structured LogMessage, we'd be able to use the regular template functions and stuff.

So how about making stats emit a LogMessage, with a special tag (for easy filtering)? Its `$MSG` part would be what we have now, but it'd have `.stats.*` fields with all the relevant stuff neatly picked apart. Then a user could write a filter+rewrite combo to format stats the way they want.

**Comment by faxm0dem** [comment]
:+1: for LogMessage

**Comment by gregory094** [comment]
Good idea! I'll check out how to implement this solution.

**Comment by bazsi** [comment]
Yeah, making stats a structured message was an idea some time ago and
should be the best solution.

**Comment by gregory094** [comment]
'syslog-ng-ctl stats' would emit a 'LogMessage' in the format suggested by @algernon that can be filtered and rewritten in the format you want. I think it would be nice to create a 'monitor()' source that would do this periodically or introduce  '--periodical=N' option for 'syslog-ng-ctl' to generate internal stat messages.  This information can be used for 'sharding' and 'balancing' syslog-ng instances if needed.  

I've only two questions:
* if 'syslog-ng' gets a 'stat' request it emits a 'LogMessage' that can be used in the pipeline but how do we want to transfer this reformatted stat to the 'syslog-ng-ctl'? Or 'syslog-ng-ctl' would only be able to print in 'csv' format and any other formats for monitoring can be reached by rewrites?
* Wouldn't this filter-rewrites have a serious impact on performance if I use them periodically? Especially if I want to rewrite in 'json'.

**Comment by algernon** [comment]
Reformatting to JSON once every 5-10 minutes is not going to cause any noticeable impact on performance. When you do a couple thousand JSON serialisations second, once every few minutes doesn't count.

**Comment by bazsi** [comment]
I don't see why a monitor() source would be needed. A stats is genetated
every stats-freq() seconds from the internal sourcr
.

**Comment by gregory094** [comment]
okey. I'll drop this PR then and start to implement this new solution.

**Pull request closed without merging**
