### PR TITLE
loggen: change message rate at runtime using signals

### PR DESCRIPTION
**Pull request by MrAnno**
This is a quick implementation of changing message rate at runtime.

`SIGUSR1` doubles, `SIGUSR2` halves the message rate.

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by MrAnno** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
