### PR TITLE
syslog-format: add a lot more comments on how the zone-offset calcula…

### PR DESCRIPTION
**Pull request by bazsi**
…tion works

Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by lbudai** [comment]
@bazsi: thanks for adding these comments to the code

**Comment by bazsi** [comment]
I have just readded them, as it was removed by a cleanup patch. I was trying to add a bit more detail with Micek, so that both of us understood.

**Pull request merged**
