### PR TITLE
HDFS destination: Added kerberos support

### PR DESCRIPTION
**Pull request by pzoleex**
Example:

```
destination d_hdfs{
    hdfs(client-lib-dir(/hdfs-libs)
 hdfs-uri("hdfs://myhdp.com:8020")
 hdfs_file("/hdfs/text.txt")
 kerberos_keytab_file("/opt/syslog-ng/etc/hdfs.headless.keytab")
 kerberos_principal("hdfs-hdpcluster@MYREALM"));
};
```

Signed-off-by: Zoltan Pallagi <pzoleex@gmail.com>

### CODE REVIEW

**Comment by pzoleex** [comment]
@kira-syslogng retest this please

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Comment by lbudai** [comment]
@pzoleex : thanks!

**Comment by bazsi** [comment]
nice

**Pull request merged**
