### PR TITLE
ISSUE_TEMPLATE: add one to make issue handling more effective

### PR DESCRIPTION
**Pull request by kvch**
Sometimes vital information is missing from issues. To avoid unnecessary roundtrips in issue fixing this template is introduced.

Signed-off-by: Noémi Ványi <sitbackandwait@gmail.com>

### CODE REVIEW

**Comment by mochrul** [comment]
If I remember correctly a script also has been developed to make issue reporting easier. Is that script abandoned?

**Comment by fekete-robert** [comment]
You mean syslog-debun? https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/syslog-debun.1.html

Good idea, it could be referenced in the template

**Comment by lbudai** [comment]
@kvch : could you refer to that script in your template?
Otherwise I liket it.
:+1:

**Comment by kvch** [comment]
@lbudai donz

**Comment by lbudai** [comment]
thanks!

**Pull request merged**
