### PR TITLE
Fix/debian packaging

### PR DESCRIPTION
**Pull request by vincentbernat**
Short version: more concise and simple Debian packaging. Not aligned with official Debian packages to minimize maintenance burden (notably people wanting one extra module or not wanting another one don't have to modify anything in Debian packaging to get that).

The first three commits are very small changes, not really related to the rework. The fourth commit is the most important and here is its description. The last one is an extra bonus.

The goals of this rework are:
- make the packaging work again
- try to minimize maintenance burden
- try to be standard-compliant (but less important than second goal)

Unlike the packages officially shipped in Debian, we keep only two
binary packages: syslog-ng with all modules and syslog-ng-dev for
development headers. The official Debian source package ships many
binary packages (one for each non-core module). This is useful to avoid
to get a syslog-ng with many dependencies but this is harder to
maintain. The downside of not following the official Debian package is
that upgrading from this package to the official one is not seamless.

Use of debhelper >= 7 to get "dh" which allows to use a smaller
`debian/rules`. This version of debhelper is available since Ubuntu
Lucid and Debian Squeeze (also available in Debian Lenny through
official backports).

Update init-script to match the one provided in the official Debian
package.

Use the upstream syslog-ng.conf configuration file instead of the one
previously shipped in Debian. This is a derivation of what is done in
the official Debian package, but again, less stuff to maintain.

Extra options for configure need to be passed through
EXTRA_CONFIGURE_OPTS environment variables. Configure options used with
`./configure` are ignored. A user getting a release tarball can just use
`dpkg-buildpackage -us -uc` to get a Debian package. A user using a git
tarball need to use `./autogen.sh && ./configure && dpkg-buildpackage
-us -uc`. In both cases, extra configure options need to be passed
through `EXTRA_CONFIGURE_OPTS` environment variable.

There are many other small changes.

### CODE REVIEW

**Comment by vincentbernat** [comment]
Hum, I think I now understand why debian/changelog is a special target. I'll amend my commits.

**Comment by bazsi** [comment]
@algernon and @talien has separated the current Debian packaging into its own repository, which is copied into the source tarball before uploading it to the archive.

It is at github.com/talien/syslog-ng-debian/

@ihrwein has an OBS project to deliver latest-greatest stuff to various distros, here:

https://build.opensuse.org/project/show/home:ihrwein

There are generally pros and cons wrt maintaining packaging files within the source tree of a project, but so far it usually resulted in conflicts when trying to maintain the official Debian packaging and the one in the upstream source. Thus we decided to separate them.

The current debian/ directory is only in the source tree as some of my internal build tools use it (but not for Debian purposes...), I'm not entirely sure what the best course of action is though. I would prefer to have one packaging, which is the same regardless if you build stuff yourself (e.g. from source) or use it for Debian, but it should be done in a manner that lets people work without conflicts.

Any opinions?

**Comment by vincentbernat** [comment]
The packaging by @algernon and @talien is great to get syslog-ng into distros. First, it only works with pretty recent distros due to strict source dependencies. Second, if you want to add a module or remove one, you need to fiddle with files in `debian` directory and many people may find that difficult. I mean, you need to add/remove an option to `./configure` in `debian/rules`, you need to add/remove a package in `debian/control`, you need to symlink some files and you need to provide a `.install` file. With the packaging proposed in the PR, you only need to add/remove the option to an environment variable. Whenever a new module appears or disappears, no change is needed in packaging.

I don't think that we can reconcile the two styles.

We can be more compatible with the official Debian packaging by adding a few lines to `debian/control` to turn `syslog-ng` into a metapackage and introduce `syslog-ng-core` package. By compatible, I mean that someone can switch from a package generated from sources to an official distro package without much pain. Currently, the transition can still be done by first uninstalling then reinstalling.

For files that you use for your internal build tools, what are they? If I look at the configuration files, they are outdated as they don't use a version, so I don't think that's the one.

We can also keep the `debian/` directory in git only (not in release tarballs). However, the conflicts between official Debian packaging and the one in the upstream source is history. This doesn't exist anymore with the 3.0 source format.

**Comment by bazsi** [comment]
Hi Vincent,

I think the upgrade path is pretty important in both ways, in some cases people want to upgrade to a newer syslog-ng than what their distro provided. In other cases they want to migrate to the distro provided one in case the distro gets the new version. Is that doable?

I would love to have something in shape within the source tree, however I didn't have much energy to maintain it lately. I think the internal build tools can be adapted to pretty much anything that can produce a source tarball using "dpkg-buildpackage -s". Is that right @lbudai, @juhaszviktor ?

**Comment by vincentbernat** [comment]
I have pushed an additional commit introducing `syslog-ng-core` package. This enables users to switch to/from official Debian packages. The package doesn't provide an ABI since we don't expect people to use it to build additional module packages. If they care about doing that, it is likely they have the skill and want to use official Debian packages.

**Comment by algernon** [comment]
Another option would be to have a script in the [syslog-ng-debian](https://github.com/algernon/syslog-ng-debian) repo, that merges the split packages into syslog-ng-core. That way, if you want to build a monolithic package, you'd do something like `DEB_BUILD_OPTIONS=monolithic dpkg-buildpackage -b`, and `debian/rules` would do its magic.

The downside is that you wouldn't be able to build a source package from this, and an additional option must be set when building (but only once, the merge is one-way, and only a git reset can undo it). But the upside is that it's reasonably easy to implement (in a forward-compatible way, that does not need updates whenever we add a new module), all packaging is maintained in a single repository.

What do you think?

**Comment by vincentbernat** [comment]
I don't have a strong opinion on this solution. Another downside is you have to add compatibility with older distributions: Ubuntu without systemd, systems where debhelper 9 is not available. Also, build dependencies may be too strong for some people who do not want to compile most modules (mainly because the packages needed for that are not available in their distro).

My main point is that people are more likely to have problems when tweaking the official packaging than with a stripped down version. If they fail to build a package, they are likely to use fpm and shout at how complex Debian packaging is.

We can add some warning that it is better to use syslog-ng-debian repository to build packages because it is more modular and complete and that the `debian/` directory in git is just here as a simple fallback.

About the current complexity, for the syslog-ng-debian repo:

```
 wc -l control rules *.dirs *.install *.{post,pre}*(.)
  331 control
  316 rules
    2 syslog-ng-core.dirs
   23 syslog-ng-core.install
    6 syslog-ng-dev.install
    1 syslog-ng-mod-amqp.install
    1 syslog-ng-mod-geoip.install
    1 syslog-ng-mod-json.install
    1 syslog-ng-mod-mongodb.install
    1 syslog-ng-mod-redis.install
    1 syslog-ng-mod-smtp.install
    1 syslog-ng-mod-sql.install
    1 syslog-ng-mod-stomp.install
    7 syslog-ng-core.postinst
   22 syslog-ng-core.postrm
   31 syslog-ng-core.preinst
   12 syslog-ng-core.prerm
  758 total
```

In this PR:

```
 wc -l control rules *.dirs *.install *.{post,pre}*(.)
 106 control
  23 rules
   1 syslog-ng-core.dirs
   7 syslog-ng-core.install
   6 syslog-ng-dev.install
   7 syslog-ng-core.postinst
  19 syslog-ng-core.postrm
  14 syslog-ng-core.preinst
 183 total
```

(the "(.)" in globbing is to not match symbolic links)

**Comment by algernon** [comment]
Hrm, good point. Making syslog-ng-debian overly complex (it already is a bit involved, although less than it was before) is likely worse than having two kinds of packaging.

**Comment by vincentbernat** [comment]
Sorry for the noise. I am also getting something similar for syslog-ng-incubator. I have also added a commit to this PR to steal the ABI versioning from the official Debian packaging. I don't intend to go further. I will also propose the syslog-ng-incubator packaging in a PR shortly.

**Comment by algernon** [comment]
Another idea to consider, that may satisfy both parties: have a separate, monolithic debian packaging repo, similar to `algernon/syslog-ng-debian`, and drop all packaging stuff from the upstream repo. Then people can choose which one they want to use, by copying the debian/ directory over (and it would be trivial to provide Debian DSC files built with the monolithic packaging, to have something similar to what we have today).

For the record, I don't really care either way. My main motivation is to nuke out any upstream packaging from the official repo, because that's been on my TODO list literally for years (approaching its fifth birthday now). From an Debian-official packaging PoV, upstream `debian/` is a pain either way. One we learned to live with, and one we work around, but still a stinging sensation in places we really prefer not to feel such things.

From a user point of view, if official .dsc + orig.tar.gz + debian.tar.gz trio is provided, that'd be the best. How that gets generated, is not really important, imo. And a split repo setup has reasonable tooling, works fine for the official builds. Updating internal BalaBit tools shouldn't be too hard, either. ;)

**Comment by vincentbernat** [comment]
Other than `debian/changelog` that could be erased (but it should not since `debian/changelog` should always be more recent), what's the problem with an upstream `debian/`? Since the official packages are using 3.0 (quilt), the upstream `debian/` directory is just replaced by the content of `debian.tar.gz`.

Another option is to not ship the Debian packaging in the release tarball (that's what I do in the projects I am upstream).

As for a separate repository, I would be worried that the target users (those not savvy enough with Debian to use the official packaging) would just not find it, not use it and use fpm instead. My personal goal is to show that Debian packaging is not hard. ;-) But I wouldn't interfere with your own goals. Keeping everything in this PR is fine for me. In a few months, I will likely base my work on the official Debian packaging, it's just I can't do that right now.

**Comment by lbudai** [comment]
Hi all!

@Vincent: your PR casting light on our (sometimes)dirty and (sometimes)unclear packaging and distribution solutions :-)

* we have an OBS repo (to be honest, OBS is not my cup of tea: there are some unresolved issues)
* @algernon has a git repo for building deb packages, he also created a nice description on
  how to create a Debian package (it is a modularized packaging)   [1]

* and now, you have a solution on how to create a monolithic deb package

If it is not possible to have one single (and, of course maintainable) solution for supporting both kinds of packaging, then we have to figure out something else... 

What if we keep packaging repos in separated git repos? Different packaging solutions could be accessed via these repos. What we need is a script which is able to prepare the debian directory.

eg.:
```
./prepare-deb-packaging --repo=debian-modularized --branch=debian/experimental
./prepare-deb-packaging --repo=debian-monolithic --branch=debian/experimental
./prepare-deb-packaging --repo=syslog-ng-debian --branch=debian/experimental
```
What do you think?


[1] https://github.com/algernon/syslog-ng-debian

**Comment by algernon** [comment]
@lbudai different repos is what I proposed a few comments above. Having a script to automatically pull down the selected one would be nice, yep. A prominent note about it in README.md would likely point users to the right direction, too.

**Comment by lbudai** [comment]
@algernon: ah, indeed... I started to write my comment a few hours ago, but having lots of interruptions.

But, if both of us have the same idea... it should work :-)

**Comment by vincentbernat** [comment]
I am also convinced with the multiple repo situation as long as there is some way for the user to discover them easily (through README or a script). I'll try to propose something.

**Comment by lbudai** [comment]
I agree: main target of this work should be providing an easy way for creating those packages, easy for every users. README is a must have (I think, the script is also a must-have : it could help a lot - but it can be added later, in a separate work).

Thank you for helping us solving this issue!!

**Comment by algernon** [comment]
If there's a repo for the monolithic packaging, I'm happy to provide a very short script to set up the tree for either.

**Comment by vincentbernat** [comment]
Well, you can use https://github.com/vincentbernat/syslog-ng/tree/fix/debian-packaging. I'll find some time (tomorrow?) to move that to a repository.

**Comment by vincentbernat** [comment]
Here is an overlay-only repository: https://github.com/vincentbernat/syslog-ng-debian-monolithic

I am expecting that you call `dch --newversion ...` at some point since `debian/changelog` is incorrect otherwise.

**Comment by algernon** [comment]
Thanks, will have a go at the script as soon as I have a little free time.

**Comment by bazsi** [comment]
Having two external packaging with proper tooling would be nice to have. The default in the source tree should probably be the one which is easier to tweak/modify.

Thanks for the great work.

**Comment by vincentbernat** [comment]
It seems that we are headed to having none in the source tree. Right?

**Comment by algernon** [comment]
My aim would be none in the source tree, indeed.

**Comment by lbudai** [comment]
What if we rename current debian directory to debian_default(which will contain the default packaging solution...) and the tool (the script) knows about it?

Then we can call the script like this:
`./prepare-deb-packaging --default`

**Comment by lbudai** [comment]
to my previous note: it is not necessary to having that default dir - that would be the same as one of the external repos :-)

**Comment by algernon** [comment]
Having the packaging *anywhere* in this repo, and having two external packaging options doesn't make much sense. In that case, @vincentbernat's one should be merged here (and perhaps moved to `contrib/`, where most other packaging stuff are).

**Comment by bazsi** [comment]
Do we have a conclusion here?

**Comment by lbudai** [comment]
We have a conclusion... I think.
Two external repos: one is for monolithic[1] and one is for modularized[2] packaging.
What we don't have: the script  (what I called `prepare-deb-packaging`).

[1] https://github.com/vincentbernat/syslog-ng-debian-monolithic
[2] https://github.com/algernon/syslog-ng-debian

**Comment by vincentbernat** [comment]
I suppose that @algernon did pause because the conclusion was not obvious. BTW, the monolithic packaging can be moved under balabit organization if needed (to let Balabit people keep control on it).

**Comment by algernon** [comment]
Yep, and I ran out of free time for the time being. I'll try to sketch something up in the next few days, but if anyone beats me to it - please be my guest.

**Comment by bazsi** [comment]
There's #1215 at this point, which is newer but touches the same things. Is this still valid?

**Comment by vincentbernat** [comment]
This is still valid but would need an update. @algernon didn't have time to move forward and I don't have time myself.

**Comment by kira-syslogng** [comment]
Can one of the admins verify this patch?

**Comment by presidento** [comment]
The debian packiging is completely reworked.

**Pull request closed without merging**
