### PR TITLE
Clean up configure directory

### PR DESCRIPTION
**Pull request by bazsi**
following up PR #628 that tries to address issue #587.

this PR solves the issue and also cleans up related configure.ac/Makefile.am machinery a bit.

Please note @lbudai, @czanik that once this gets integrated, the --datadir configure option should be removed from debian/rules and rpm specfiles, as it will generate paths like:

/usr/share/syslog-ng/syslog-ng/scl & /usr/share/syslog-ng/syslog-ng/tools

I am not sure where and how we should open tickets about the packaging files to avoid getting lost.

### CODE REVIEW

**Comment by lbudai** [comment]
The best would be to create a dedicated github project for the OBS packaging files (both rpm and deb) and in that case, issues could be opened.

**Comment by bazsi** [comment]
why don't we merge those into syslog-ng? at least those that we maintain.


-- 
Bazsi

**Comment by ihrwein** [comment]
I'd also prefer a dedicated project for packaging, because syslog-ng's code can be untouched while working on packaking.

**Comment by czanik** [comment]
There are too many variations in packaging, depending on the distribution, which release we use, if we enable only features supported by the base distribution or we also provide missing dependencies in separate package, etc. So, even if we put packaging into git, it should be separate from the syslog-ng package.

**Comment by bazsi** [comment]
I think we are on agreement on the code in this PR. @algernon, @ihrwein both showed support in #587 

The only discussion is about whether to merge packaging or not. That should be handled separately.

So I am merging this now.

**Comment by czanik** [comment]
@bazsi @ihrwein The "xsd" directory is now messed up. If I keep the old configure parameter ( --datadir="%{_datadir}/syslog-ng" ) then all files are installed under /usr/share/syslog-ng/syslog-ng except for the "xsd" directory.
If I remove the trailing "syslog-ng" from it, the most of the files are placed under /usr/share/syslog-ng/ but the xsd directory is placed under /usr/share/xsd
``
abuild@linux-fsdl:/home/abuild/rpmbuild/BUILDROOT/syslog-ng-3.8.0alpha0-1.x86_64/usr/share/syslog-ng> ls *
syslog-ng:
include  tools

xsd:
patterndb-1.xsd  patterndb-2.xsd  patterndb-3.xsd  patterndb-4.xsd
abuild@linux-fsdl:/home/abuild/rpmbuild/BUILDROOT/syslog-ng-3.8.0alpha0-1.x86_64/usr/share/syslog-ng> 
``

**Comment by bazsi** [comment]
This should be fixed up by defining xsddir just like the others.

I am trying to fix that up, thanks for opening the ticket.

**Comment by czanik** [comment]
As discussed with @ihrwein the following problem seems to be related too:

``
linux-fsdl:/etc/syslog-ng # syslog-ng -Fvd
[2016-02-02T15:56:59.233862] Unable to detect fully qualified hostname for localhost, use_fqdn() will use the short hostname;
[2016-02-02T15:56:59.235337] Systemd is detected as the running init system;
[2016-02-02T15:56:59.236420] Starting to read include file; filename='/etc/syslog-ng/scl.conf', depth='1'
[2016-02-02T15:56:59.237012] Global value changed; define='scl-root', value='/usr/share/include/scl'
[2016-02-02T15:56:59.237452] Global value changed; define='include-path', value='/etc/syslog-ng:/usr/share/include'
[2016-02-02T15:56:59.237871] Finishing include; filename='/etc/syslog-ng/scl.conf', depth='1'
[2016-02-02T15:56:59.238301] Reading path for candidate modules; path='/usr/lib64/syslog-ng'
[2016-02-02T15:56:59.238731] Reading shared object for a candidate module; path='/usr/lib64/syslog-ng', fname='afsocket.so', module='afsocket'
[...]
[2016-02-02T15:56:59.261423] Reading shared object for a candidate module; path='/usr/lib64/syslog-ng', fname='graphite.so', module='graphite'
[2016-02-02T15:56:59.261522] Registering candidate plugin; module='graphite', context='template-func', name='graphite_output', preference='0'
Error parsing source, source plugin system not found in /etc/syslog-ng/syslog-ng.conf at line 32, column 2:

	system();
	^^^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-
``

**Pull request merged**
