### PR TITLE
Make the default for RLIMIT_NOFILE equal to the current system limits.

### PR DESCRIPTION
**Pull request by avleen**
--fd-limit can still override this, but the default will be configured based on
existing system limits.

Issue: https://github.com/balabit/syslog-ng/issues/646

Signed-off-by: Avleen Vig <avleen@gmail.com>

### CODE REVIEW

**Comment by bazsi** [comment]
I think the cygwin specific value was there because it didn't support more than 256fds but with this code it shouldn't be needed. So please drop the cygwin part.

Also please use your own name for signed-of-by.

Otherwise it's a great contribution thanks a lot.

:+1:

**Comment by avleen** [comment]
Done! Thanks @bazsi !

**Comment by bazsi** [comment]
Looks good. Can you pls fix up the commit messages?

Both should include a signed-of-by with your own name. Also, the summary itself should contain a prefix that defines the patch scope somewhat, and it shouldn't be longer than a line. 

The first summary is OK it just needs the prefix part. The second though us a bit too verbose and continues into the body

We also usually fold and squash patches if they iterate on the same code, however I think it is better to keep the two changes separate, they are independent changes in their own right.

**Comment by lbudai** [comment]
Thanks!

**Pull request merged**
