### PR TITLE
DBLD: Allow to use redirect for wget in add_obs_repo()

### PR DESCRIPTION
**Pull request by mitzkia**
Signed-off-by: Andras Mitzki <andras.mitzki@balabit.com>

### CODE REVIEW

**Comment by furiel** [comment]
Can you explain where the redirect goes to? If it is just a http->https upgrade, it would be better update the url itself instead.

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
```
$ wget --max-redirect=1 http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04/Release.key
--2018-10-03 08:10:18--  http://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04/Release.key
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2620:113:80c0:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://provo-mirror.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04/Release.key [following]
--2018-10-03 08:10:25--  http://provo-mirror.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/xUbuntu_16.04/Release.key
Resolving provo-mirror.opensuse.org (provo-mirror.opensuse.org)... 130.57.72.10
Connecting to provo-mirror.opensuse.org (provo-mirror.opensuse.org)|130.57.72.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
```

**Comment by mitzkia** [comment]
The server (download.opensuse.org) is up again.

**Pull request closed without merging**
