### PR TITLE
sudo: filter out incorrectly parsed logs

### PR DESCRIPTION
**Pull request by bazsi**
sudo may generate some log messages through libpam, drop those messages.

Signed-off-by: Balazs Scheidler <balazs.scheidler@balabit.com>

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by bazsi** [comment]
@kira-syslogng test this please test branch=sudo-testcase-fixes;

**Comment by kira-syslogng** [comment]
Build FAILURE

**Comment by mitzkia** [comment]
@kira-syslogng test this please test branch=sudo-testcase-fixes;

**Comment by mitzkia** [comment]
Thanks for the catch. I have added a minor testcase fix ().

**Comment by mitzkia** [comment]
@kira-syslogng retest this please test branch=sudo-testcase-fixes;

**Comment by kira-syslogng** [comment]
Build SUCCESS

**Pull request merged**
