### PR TITLE
configure: add --disable-python option to configure

### PR DESCRIPTION
**Pull request by ihrwein**
Signed-off-by: Tibor Benke <tibor.benke@balabit.com>

### CODE REVIEW

**Comment by ihrwein** [comment]
# Explicitly disabling Python

```
--disable-python
```

Output at the end of configure:
```
  python                      : no (none)
```

# Explicitly enabling Python

```
--enable-python
```

Output at the end of configure:
```
  python                      : yes (python)
```

# Requesting specific Python version 2.7

```
--with-python=2.7
```

Output at the end of configure:
```
  python                      : yes (python-2.7)
```

# Requesting specific Python version 3.4

```
--with-python=3.4
```

Output at the end of configure:
```
  python                      : yes (python-3.4)
```

# Requesting Python support


```
--with-python
```

Output at the end of configure:
```
  python                      : yes (python)
```

# Requesting not existing Python support


```
--with-python=3.8
```

Configure fails with the following error message:

```
configure: error: Did not find the requested Python development libraries
```

**Comment by ihrwein** [comment]
@bazsi FYI, you use Python most frequently in syslog-ng

**Comment by ihrwein** [comment]
@lbudai This might be useful before the release.

**Comment by lbudai** [comment]
@ihrwein : agree, but this not affects 3.6.3

**Comment by bazsi** [comment]
I like both the functionality and the way it is implemented.

:+1:

**Pull request merged**
