### PR TITLE
elasticsearch: Change default value of flush_limit and concurrent_req…

### PR DESCRIPTION
**Pull request by pzoleex**
…uests

For flush_limit -> 5000 as it is already changed in SCL
For concurrent_requests -> 1

### CODE REVIEW

**Comment by faxm0dem** [comment]
What does `concurrent_requests` do? Is it documented?

**Comment by pzoleex** [comment]
https://www.elastic.co/guide/en/elasticsearch/client/java-api/1.6/bulk.html
"Set the number of concurrent requests. A value of 0 means that only a single request will be allowed to be executed. A value of 1 means 1 concurrent request is allowed to be executed while accumulating new bulk requests. "

Basically, it will increase the performance if flush_limit > 0.

**Comment by faxm0dem** [comment]
Excellent, will try this ASAP. Is this available in 3.7.1?

**Comment by pzoleex** [comment]
I think only from 3.7.2

**Comment by lbudai** [comment]
yep, this changes available only from 3.7.2

**Pull request merged**
