### PR TITLE
afprog: do not send SIGTERM when getpgid() fails

### PR DESCRIPTION
**Pull request by lbudai**
Fixes: #586

Signed-off-by: Laszlo Budai <stentor.bgyk@gmail.com>

### CODE REVIEW

**Comment by lbudai** [comment]
after it is merged, it should be ported to current master

**Comment by bazsi** [comment]
:-1:

**Comment by bazsi** [comment]
Sorry I meant :+1:

**Comment by ihrwein** [comment]
:+1:

**Comment by ihrwein** [comment]
Thanks!

**Pull request merged**
