### PR TITLE
AFInter: Proper wakeup function handling for deinitialized AFInterSou…

### PR DESCRIPTION
**Pull request by juhaszviktor**
…rces

The wakeup() callback can be called even if a AFInterSource is
deinitialized (when the Writer is deinitialized _after_ the internal source, and
some messages are flushed out in the deinit path), in
which case we shouldn't trigger the schedule_wakeup event.

Signed-off-by: Juhász Viktor <viktor.juhasz@balabit.com>

### CODE REVIEW

**Comment by lbudai** [comment]
Could you also send this PR to master?

**Comment by juhaszviktor** [comment]
Of course :)

**Comment by juhaszviktor** [comment]
The PR on master is #509

**Comment by lbudai** [comment]
Thanks!

**Pull request merged**
