### PR TITLE
Fix misspeling in an error message

### PR DESCRIPTION
**Pull request by morrowc**
A simple spelling error correction.

### CODE REVIEW

**Comment by bkil-syslogng** [comment]
:+1: Thanks. Do you perhaps know a tool or method to do a spell check on all of our constant text and/or comments inside the code? (Perhaps even by following leads generated by `sed`)

**Comment by morrowc** [comment]
I imagine that the simplest first stab at 'check all the spelling' is really just to use the unix 'aspell' utility. Using aspell:
   aspell --mode ccpp -c cfg.c

gets the next pull-request's content ... it's a bit manual in the mode there, but maybe there's another flag to (given some dictionary work) just auto-fix things, or auto-fix MOST things with some manual revert (and consequent dictionary update).

**Comment by morrowc** [comment]
I think there should be a new pull with an example of using the aspell utility.

**Comment by bkil-syslogng** [comment]
Yes, this is a nice proposal. We sure could use some native speakers to double check our language. Do note that `PersistentConfig` in this context refers to the camel-case class name that the file implements, but the other fix is valid. So you will need to undo this one from the commit.

I guess you could squash all changes/commits to a single one or at most a few. We could give some pointers if you haven't done any git rebasing before. It's a lot of fun after you get the hang of it.

We can merge all your great improvements at once via this pull request, you don't need to create a separate pull request for each file. :)

We usually organize our commits by areas touched and/or function to make it easier to understand, double check and cherry-pick later on. I guess you could submit all changes in about 3 commits, but it's up to you and the nature of your improvements. Note that according to our commit conventions, the format of your commit messages should be something like:

```
*: improve spelling in error messages

Signed-off-by: Chris Morrow <your-email-address@example.com>
```

```
*: improve spelling in comments

Signed-off-by: Chris Morrow <your-email-address@example.com>
```

```
scripts: added custom spelling dictionary and spell checking script

(You can describe it a little here if you want to, up to 72 chars/line)

Signed-off-by: Chris Morrow <your-email-address@example.com>
```

I advocate separating the first two commits as shown because changes in error messages is a user visible change, while at other places, it's only refactoring.

We have been considering creating a custom domain-specific dictionary for a while now. We would need to white list common abbreviations, these camel-case identifiers, function names, and so on. Do you know how other project do this? If you could come up with something, we would welcome your additions. 

You could also go through all files like so:
`find . -iname '*.[ch]' -type f -exec aspell --mode ccpp -c {} \;`

I'm not sure in which folder we should put the dictionary, maybe we could find place in `scripts`. The root folder is starting to get a bit cluttered.

Note that if you help us create a dictionary (and show us how it can be used), we could connect automatic spell checking later on to the system which would add great value to all of us. So in the future, if one wants to add code, they would be automatically warned if the additions seem to have an issue with spelling and could be fixed on the spot.

**Comment by bazsi** [comment]
I would split the automatic spell-check off from the fixes in these patches, as the first is obviously a lot larger task to do.

@morrowc could you please squash all your commits into a single patch, so I can merge it? It should have a proper commit message as @bkil-syslogng explained, and a signed-off-by line. You can force push it into this branch so that we only need to press the merge button. thanks a lot.

**Comment by morrowc** [comment]
I'll give it a whirl tomorrow. Work has had me busy on "not fun projects", sorry for the delay.
On May 7, 2016 2:49 AM, Balazs Scheidler <notifications@github.com> wrote:I would split the automatic spell-check off from the fixes in these patches, as the first is obviously a lot larger task to do.

@morrowc could you please squash all your commits into a single patch, so I can merge it? It should have a proper commit message as @bkil-syslogng explained, and a signed-off-by line. You can force push it into this branch so that we only need to press the merge button. thanks a lot.

**Comment by morrowc** [comment]
I think I botched up the git process somewhere along the way :(
At this point it is probably simpler to just backup and restart from the beginning for me.

**Comment by morrowc** [comment]
Ok, back on track I hope, there should be a pull request with the original change in place.

**Comment by bazsi** [comment]
I have closed PR #1050 and thus I am closing this as well.

**Pull request closed without merging**
