### PR TITLE
Read configuration variables from sysconfig

### PR DESCRIPTION
**Pull request by faxm0dem**
Both directories /etc/sysconfig and /etc/default are searched for by
systemd and if syslog-ng exists it will be used for extracting env
variables. This should cover debian and redhat based systems and is
convenient to migrate from sysvinit to systemd

### CODE REVIEW

**Comment by faxm0dem** [comment]
BTW this can be used to add `LD_PRELOAD=.../libjvm.so` see #596

**Comment by deirf** [comment]
:+1:

**Comment by ihrwein** [comment]
Here is the docs: http://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=

And my :+1:

**Comment by lbudai** [comment]
Thanks!

**Pull request merged**
