### PR TITLE
python-dest: value-pairs reference leak

### PR DESCRIPTION
**Pull request by furiel**
There is a reference leak in python destination when fields are added
to the message through value pairs. The leak happens per message, so
the memory usage of syslog-ng can increase considerably in a short
period of time.

Also, original implementation led to crash when python destination was fed with binary data (for example loggen -U). This patch also checks if the conversion from char*/long to pyobj was successful.

Example configuration:
```
@version: 3.13

destination d_python {
    python(class("Foo") value-pairs(scope(everything)));
};
log {
    source{tcp(port(10514));};
    destination(d_python);
    flags(flow-control);
};

python {
import sys
class Foo(object):
    def init(self, options):
        return True
    def send(self, msg):
        return True
};
```
Fixes: https://github.com/balabit/syslog-ng/issues/1253

### CODE REVIEW

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by furiel** [comment]
As @Kokan pointed out IRL, it is easy to feed python destination with binary data, for example loggen -U (tls), which will lead to PyUnicode_FromString return with NULL, resulting in a crash when adding NULL to the dictionary.
I force pushed a new version when we check the return value of the conversion function as well, and fetch the generated error in case of conversion failure.

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by bazsi** [comment]
Maybe we should feed bytes to python?

**Comment by furiel** [comment]
Right, I will replace PyUnicode with PyBytes to maintain consistency with the index operator in syslog-ng.

**Comment by furiel** [comment]
I force pushed a new version. In the end I used PyBytes_FromStringAndSize, thus I could resolve the following comment in the code: `/* TODO escape '\0' when passing down the value */`
I could test it with the recently added $(binary) template function:
`value-pairs(scope(everything) pair("TESTSTRING" string("TESTS $(binary 0x00) TRING")))`

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Pull request merged**
