### PR TITLE
F/fix filter numeric ops

### LINKED ISSUE #772: lib/filter/filter-cmp.c:116: missing break ?
[lib/filter/filter-cmp.c:116] -> [lib/filter/filter-cmp.c:118]: (warning) Variable 'cmp_op' is reassigned a value before the old one has been used. 'break;' missing?

Source code is

    case KW_NUM_LT:
      self->cmp_op = FCMP_NUM;
    case KW_LT:
      self->cmp_op = FCMP_LT;
      break;

### PR DESCRIPTION
**Pull request by bazsi**
Well, it is embarassing but the numeric side of comparison operators in filter expressions never really worked. The aim of this patch series is to fix them up.

This one should fix #772, thanks for reporting that.

There's a compatibility tradeoff in this series, that is shown by the warning message that I was adding, we might want to discuss that before merging.

Cheers,
Bazsi

### CODE REVIEW

**Comment by ihrwein** [comment]
:+1:

**Comment by lbudai** [comment]
Hmm... interesting question. I'd say it can be merge as-is, but we are in a lucky situation: we already opened 3.8 ...

So I think we should answer the following question : What if someone will report the same bug for 3.7? 

a) we accept the bug and fix (and remove the warning from versions >= 3.8)
b) don't accept due to compatibility issues and we will suggest an upgrade

I think both of them could be a good choice. My vote is `b)` .

**Comment by bazsi** [comment]
I agree.

**Comment by lbudai** [comment]
ok, then it is mergeable :-)

**Pull request merged**
