### PR TITLE
Syslog-ng-debun improvements

### PR DESCRIPTION
**Pull request by jszigetvari**
Fixed bugs in the area of file size parsing for the PKI CSV and hash generation for the manifest
Also added the outputs of top, netstat -lunp, and sar (CPU and disk)

### CODE REVIEW

**Comment by kira-syslogng** [comment]
This user does not have permission to start the build. Can one of the admins verify this patch and start the build? (admin please type: ok to test)

**Comment by MrAnno** [comment]
@kira-syslogng ok to test

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by MrAnno** [comment]
@jszigetvari Can you rebase your branch to master, please?

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by kira-syslogng** [comment]
Build SUCCESS, the tests were executed on test branch: master and test suite: functions

**Comment by MrAnno** [comment]
Thanks.

**Pull request merged**
